### ISSUE TITLE
Uploading NFT n°99/100. An error occured. Message: File doesn't exist or path is incorrect. Please help

### ISSUE THREAD

**Issue by shirazdelhi** [maximedrn/opensea-automatic-bulk-upload-and-sale#100]
![Screenshot_1](https://user-images.githubusercontent.com/97992025/153897745-dd5eb049-ac7c-489d-9a4b-862ea853707b.png)
@maximedrn

**Comment by maximedrn** [comment]
It must be a path to each file, not to the folder.
replace the "\" by "/" or "\\\\".

**Comment by shirazdelhi** [comment]
sorry for bothering you again I am just new to this  :(

**Comment by maximedrn** [comment]
No problem ;)
