### ISSUE TITLE
IndexError: List Index out of Range

### ISSUE THREAD

**Issue by tenumars** [maximedrn/opensea-automatic-bulk-upload-and-sale#101]
I have all of the required fields and the ones not required empty as well, but am still getting an error. Also how can I remove the custom fields from the hashlips metadata? I think the error might be related to that, with the custon fields. I cannot remove it though.

`Traceback (most recent call last):
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 744, in <module>
    structure.get_data(nft_number)  # Structure the data of the NFT.
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 107, in get_data
    eval(f'self.structure_{self.extension}()')
  File "<string>", line 1, in <module>
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 115, in structure_json
    self.structure_data([self.dict_to_list(
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 177, in structure_data
    self.blockchain: str = str(nft_data[11]).capitalize()
IndexError: list index out of range`

**Comment by maximedrn** [comment]
It seems that your file has an incorrect format. Please send me an excerpt of your file, I will help you.
```python
self.blockchain: str = str(nft_data[11]).capitalize() 
IndexError: list index out of range
```
It is clearly stated that an element is not mentioned so Python cannot get the 12th element in the list.

**Comment by tenumars** [comment]
`{
  "nft":[
  {
    "file_path": "C:/Users/mclou/OneDrive/Documents/NFT Creator/build/images/1.png",
    "nft_name": "Dino Struggle Is Real #1",
    "external_link": "",
    "description": "Dinosaurs failing to do things considered common today with their stumpy arms",
    "collection": "The Dino Struggle Is Real",
    "properties": [
      {
        "trait_type": "Background",
        "value": "Light Blue Grey"
      },
      {
        "trait_type": "Scenery",
        "value": "BLANK "
      },
      {
        "trait_type": "DinoColor",
        "value": "LightGrey DarkGrey "
      },
      {
        "trait_type": "DinoActivity",
        "value": "BLANK "
      },
      {
        "trait_type": "Hats",
        "value": "TopHat "
      }
    ],
    "unlockable_content": false,
    "explicit_and_sensitive_content": false,
    "supply": 10000,
    "blockchain": "Polygon"
  },
  {
    "file_path": "C:/Users/mclou/OneDrive/Documents/NFT Creator/build/images/2.png",
    "nft_name": "Dino Struggle Is Real #2",
    "external_link": "",
    "description": "Dinosaurs failing to do things considered common today with their stumpy arms",
    "collection": "The Dino Struggle Is Real",
    "properties": [
      {
        "trait_type": "Background",
        "value": "Dark Blue"
      },
      {
        "trait_type": "Scenery",
        "value": "BLANK "
      },
      {
        "trait_type": "DinoColor",
        "value": "LightGrey DarkGrey "
      },
      {
        "trait_type": "DinoActivity",
        "value": "BLANK "
      },
      {
        "trait_type": "Hats",
        "value": "BLANK "
      }
    ],
    "unlockable_content": false,
    "explicit_and_sensitive_content": false,
    "supply": 10000,
    "blockchain": "Polygon"
  },`

there is an excerpt of one of the metadata files, the error is now
`Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.

Traceback (most recent call last):
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 744, in <module>
    structure.get_data(nft_number)  # Structure the data of the NFT.
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 107, in get_data
    eval(f'self.structure_{self.extension}()')
  File "<string>", line 1, in <module>
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 115, in structure_json
    self.structure_data([self.dict_to_list(
  File "C:\Users\mclou\OneDrive\Documents\opensea-automatic-bulk-upload-and-sale-master\main.py", line 176, in structure_data
    self.supply: int = nft_data[10]
IndexError: list index out of range`, so I don't know if that is the same thing or if it is different

**Comment by maximedrn** [comment]
You should have this:
```json
         "file_path": "C:/Users/Admin/Desktop/NFT/nft_0004.png",
         "nft_name": "NFT #4",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": "",
         "levels": "",
         "stats": "",
         "unlockable_content": "",
         "explicit_and_sensitive_content": "",
         "supply": "",
         "blockchain": "",
```
Levels and stats are missing

**Comment by tenumars** [comment]
It works now, thank you so much, but is there a way to 'trick' it into using coinbase wallet? I have both, but prefer coinbase

**Comment by tenumars** [comment]
That worked, and is there a way with the 'stats' to get it to be a value, instead of the from x to y?
