### ISSUE TITLE
Will not choose collection even though it is pulled up

### ISSUE THREAD

**Issue by tenumars** [maximedrn/opensea-automatic-bulk-upload-and-sale#104]
I put the correct collection name in the metadata, but it is not working, it pulls up the collection when choosing but will not select it.

![image](https://user-images.githubusercontent.com/98669318/154171804-372faa53-e12e-4756-bbeb-f02a8514deb6.png)

```
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.

Uploading NFT n°1/10000. An error occured. Message: Collection doesn't exist or can't be found.
```

**Comment by maximedrn** [comment]
Capitals letters are important.
"The Dino Struggle **i** Real"
"The Dino Struggle **I**s Real"

**Comment by tenumars** [comment]
ok, it got it, thanks so much, I'm uploading now!
