### ISSUE TITLE
Worker restart causes duplicates to be created.

### ISSUE THREAD

**Issue by mar3ksoftware** [maximedrn/opensea-automatic-bulk-upload-and-sale#107]
Hi !

After the recent update, in which you restart the worker when the bot can't login to opensea it'll simply duplicate all the NFT's that were uploaded beforehand.

Currently I've no time to create a pull request or to fix that myself. When I do get the time, I'll create it in the meantime could you look into this ?

**Comment by maximedrn** [comment]
It's fixed!
