### ISSUE TITLE
NFT creation hangs on description

### ISSUE THREAD

**Issue by SolidsnakeIT** [maximedrn/opensea-automatic-bulk-upload-and-sale#108]
Hi, I've set the excel file to "upload only".
By running the script, it connects correctly to metamask and uploads the files (the main one is a 3d GLB and the secondary one is a PNG).
After compiling the extended description the script freezes: it seems unable to continue compiling the name of the collection.
Attached is the screen shot of the error.

What am I doing wrong?

thank you
<img width="654" alt="Schermata 2022-02-17 alle 10 18 24" src="https://user-images.githubusercontent.com/28677994/154444939-6068b1e5-cdfc-427c-805c-0640b26b3b5f.png">

**Comment by maximedrn** [comment]
Send me an excerpt of your file. I'll tell you what is wrong :)

**Comment by SolidsnakeIT** [comment]
Hi, in attachment the file.
Thank you very much :)
[xlsx_structure_upload_and_sale.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8088063/xlsx_structure_upload_and_sale.xlsx)

**Comment by SolidsnakeIT** [comment]
> Send me an excerpt of your file. I'll tell you what is wrong :)
Hi, in attachment the file.
Thank you :)

[xlsx_structure_upload_and_sale.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8096458/xlsx_structure_upload_and_sale.xlsx)

**Comment by maximedrn** [comment]
Strings do not required " in XLSX files :)
Remove the " for the NFT name, description and collection.
It should work.

**Comment by SolidsnakeIT** [comment]
> Strings do not required " in XLSX files :)
> Remove the " for the NFT name, description and collection.
> It should work.

Sorry but it still not working.
In attachment I re-send the excel without quotes and a little video toe explain the problem. 
I tried to clear the description but the cursor remain to "external link field"
[xlsx_structure_upload_and_sale.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8096708/xlsx_structure_upload_and_sale.xlsx)

https://user-images.githubusercontent.com/28677994/154674518-426f53ff-8f90-41e8-937a-9536fcafbee8.mp4

**Comment by SolidsnakeIT** [comment]
> Line 452, replace with this:
> 
> ```python
>             if not structure.is_empty(  # Input collection and select it.
>                     '//*[@id="collection"]', structure.collection):
> ```
> 
> OpenSea update this part by adding an id to the input. So my bot didn't find the input. I'll update the code later.

YES!
toy's more faster than me... 

Now works fine. Thank you very much :)
