### ISSUE TITLE
NFT sale cancelled. HTTPConnectionPool(host='localhost', port=60598): Max retries exceeded with url

### ISSUE THREAD

**Issue by gatekendo** [maximedrn/opensea-automatic-bulk-upload-and-sale#112]
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.
Sale of the NFT n°1/9. NFT put up for sale.
Sale of the NFT n°2/9. NFT sale cancelled. HTTPConnectionPool(host='localhost',
port=60598): Max retries exceeded with url: /session/79a41100b479d438299f45f36db
ab9aa/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obje
ct at 0x000000B0F087E230>: Failed to establish a new connection: [WinError 10061
] No connection could be made because the target machine actively refused it'))

**Comment by maximedrn** [comment]
This is an issue that has occurred with Selenium when using the urllib3 module.
I don't know if this is occasional, so let me know if you have it often.

**Comment by nabeelsaleem** [comment]
I am having this issue,
all sale cancelling. 




![image](https://user-images.githubusercontent.com/6704727/155602588-ada286bc-2dcc-4807-8e9e-35b9001b6557.png)
