### ISSUE TITLE
Upload but don't sell

### ISSUE THREAD

**Issue by Terlain1** [maximedrn/opensea-automatic-bulk-upload-and-sale#113]
I did however tell the bot to sell them and upload them but that only makes me upload them without selling them so I have to enter the urls of my thousands of nfts on the excel table cvs_structure_sale_only.cvs ... Do you have any fix?

**Comment by maximedrn** [comment]
Can you send me an excerpt from your file. The error could be there.

**Comment by maximedrn** [comment]
Change the price from 0,015 to 0.015

**Comment by Terlain1** [comment]
the console tells me :

Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.
An error occured. list index out of range

**Comment by maximedrn** [comment]
You used the xlsx_structure_upload_and_sale.xlsx file?

**Comment by Terlain1** [comment]
thank you very much ;)
