### ISSUE TITLE
After logging in to OpenSea, I receive this message in the script.... Launch error. list index out of range

### ISSUE THREAD

**Issue by themichaelvannote** [maximedrn/opensea-automatic-bulk-upload-and-sale#119]
The script runs, logs in the OpenSea with no issues, and then after the browser logs in, it instantly closes, and I receive the error....

"Launch error. list index out of range"

I am use a data.json file with the correct template that was provided. I have updated and installed all requirements.

Any suggestions are appreciated. Thanks!

**Comment by maximedrn** [comment]
Send me an extract of your file, you forgot some data because the list is too short (list index out of range)

**Comment by themichaelvannote** [comment]
Good afternoon. Thank you so much for getting back to me. I cleaned up my data file and found a few errors. I have fixed those and still receive the same error. “List Index out of range”

 

Is  it because I don’t have as many trait types under properties?

 

I really appreciate your help for looking at this.

 

Thank you,

 

Michael

**Comment by maximedrn** [comment]
You forgot some details. You should have 18 details (download and sale), 12 details (download), 9 details (sale). Whether they are empty or not, they should be mentioned.

**Comment by themichaelvannote** [comment]
Ok, that makes sense. Thank you again! The script is very nice!

**Comment by themichaelvannote** [comment]
UPDATE:

Script is working flawlessly now.!

**Comment by maximedrn** [comment]
Nice! I close this issue.
