### ISSUE TITLE
GeckoDriver wrong sell date, always defaults to 7 days, when using duration of len 2

### ISSUE THREAD

**Issue by mar3ksoftware** [maximedrn/opensea-automatic-bulk-upload-and-sale#121]
**Describe the problem:**
Here is my data structure for duration:
```
      "duration": [
        "22-02-2022 14:00",
        "22-04-2022 15:00"
      ],
```

The issue is that the bot while using GeckoDriver aways sets the data to 7 days, i tried to move things around where the bot navigates the website by div, it did not work.

**System Information:**
 - Operating system: Windows 11 64Bit
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
- Python version used.
 - 3.10.2
- Version of the bot: 1.5.6

**Comment by maximedrn** [comment]
I just released version 1.5.7 which seems to fix this problem :)

**Comment by mar3ksoftware** [comment]
Seems to work fine but there's a lot of errors, when it comes to selling items. Fortunately the sale data is saved. I do not know if anything can be done about this.

![obraz](https://user-images.githubusercontent.com/49950703/154855977-944949ec-ef9b-4a87-a42e-be00a2d10f02.png)

**Comment by maximedrn** [comment]
Sometimes this error happens (second image), but the first one is unknown :/

**Comment by mar3ksoftware** [comment]
Yeah it's not a big deal, and the second one might be on my end. So it's all good. I can use the generated data to put the items on sale anyway. Thanks for your hard work man !
