### ISSUE TITLE
Fail at Ethereum contract signing. 

### ISSUE THREAD

**Issue by supertech4321** [maximedrn/opensea-automatic-bulk-upload-and-sale#122]
When trying to upload NFT, and sell with Ethereum it fail at signing contract at the very end.

**Comment by maximedrn** [comment]
Do you use the last version of the bot (1.5.6)?

**Comment by supertech4321** [comment]
Just updated to 1.5.7 and that fixed the Ethereum signing problem. 

Now gettting posting to 7 days by default when i am trying to post for 1 month. Using Chrome extension

Here's my structure. 

"duration": "1 month",

**Comment by maximedrn** [comment]
Send me an extract of your file.
See this error too: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/126

**Comment by Kisnobeats** [comment]
Hey, back again (sadly). I, too, get an error when trying to sign the Wyvern Exchange Contract sale. Everything goes smoothly up until that point. Here is what the code says for me.

Sale of the NFT n°5/2995. NFT sale cancelled. Message: chrome not reachable
  (Session info: chrome=98.0.4758.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x00F37AC3+2587331]
        Ordinal0 [0x00ECADD1+2141649]
        Ordinal0 [0x00DC3A80+1063552]
        Ordinal0 [0x00DB8222+1016354]
        Ordinal0 [0x00DB8A58+1018456]
        Ordinal0 [0x00DBA292+1024658]
        Ordinal0 [0x00DB3F79+999289]
        Ordinal0 [0x00DC4EF0+1068784]
        Ordinal0 [0x00E181D2+1409490]
        Ordinal0 [0x00E084A6+1344678]
        Ordinal0 [0x00DE53F6+1201142]
        Ordinal0 [0x00DE62E6+1204966]
        GetHandleVerifier [0x010DDF22+1680738]
        GetHandleVerifier [0x01190DBC+2413564]
        GetHandleVerifier [0x00FCD151+563089]
        GetHandleVerifier [0x00FCBF13+558419]
        Ordinal0 [0x00ED081E+2164766]
        Ordinal0 [0x00ED5508+2184456]
        Ordinal0 [0x00ED5650+2184784]
        Ordinal0 [0x00EDF5BC+2225596]
        BaseThreadInitThunk [0x75A3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77837A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77837A4E+238]

**Comment by supertech4321** [comment]
> Send me an extract of your file. Look at this error too: #126

Your reference in another bug help fixed my problem. I had the wrong order in my metadata. 

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/126
