### ISSUE TITLE
JSON Upload Only Completed. Use the CSV file it has created to sell now?

### ISSUE THREAD

**Issue by Kisnobeats** [maximedrn/opensea-automatic-bulk-upload-and-sale#125]
I understand it produces a CSV file after using the "upload only.json" file. I ran the script and chose the CSV file it had created, and it just logs me into Opensea and closes. What am I doing wrong, exactly?

I also used the "sale only.json" and had just one NFT block with details, etc....am I supposed to manually fill 3000 NFTs and their respective data in that file for it to work? 

I love the code to death as its the only one that works perfectly for uploading, but today is the first time trying to actually using the sale file, but clearly am doing something wrong. Thank you all for everyting!

**Comment by maximedrn** [comment]
> I understand it produces a CSV file after using the "upload only.json" file. I ran the script and chose the CSV file it had created, and it just logs me into Opensea and closes. What am I doing wrong, exactly?
> 
> I also used the "sale only.json" and had just one NFT block with details, etc....am I supposed to manually fill 3000 NFTs and their respective data in that file for it to work?
> 
> I love the code to death as its the only one that works perfectly for uploading, but today is the first time trying to actually using the sale file, but clearly am doing something wrong. Thank you all for everyting!

If you want to use the generated file to sell your NFTs, you must complete it with essential information (such as price and duration).

**Comment by Kisnobeats** [comment]
> > I understand it produces a CSV file after using the "upload only.json" file. I ran the script and chose the CSV file it had created, and it just logs me into Opensea and closes. What am I doing wrong, exactly?
> > 
> > I also used the "sale only.json" and had just one NFT block with details, etc....am I supposed to manually fill 3000 NFTs and their respective data in that file for it to work?
> > 
> > I love the code to death as its the only one that works perfectly for uploading, but today is the first time trying to actually using the sale file, but clearly am doing something wrong. Thank you all for everyting!
> 
> If you want to use the generated file to sell your NFTs, you must complete it with essential information (such as price and duration).

Hey, thank you for such a quick response! So to clarify, I do not need to update the "sale_only.json" file? When I run the script, do I run the now updated CSV (with the price and duration and such) file it produced after the bulk upload?

**Comment by maximedrn** [comment]
In the data folder, you should have a file named `generated_[numbers_and_letters].csv`. You need to fill it in with the type of sale, method, price, duration, quantity, etc. The URL, blockchain and offer are already present.

If you can't find it, you may have deleted it. In this case, you will have to use the `sale_only` files and fill in all the necessary information (including the URLs of **each** NFT - which is very long).

**Comment by maximedrn** [comment]
> In the data folder, you should have a file named `generated_[numbers_and_letters].csv`. You need to fill it in with the type of sale, method, price, duration, quantity, etc. The URL, blockchain and offer are already present.
> 
> If you can't find it, you may have deleted it. In this case, you will have to use the `sale_only` files and fill in all the necessary information (including the URLs of **each** NFT - which is very long).

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#sale-only
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#configuration-of-the-sale-part-of-the-nfts

**Comment by Kisnobeats** [comment]
> In the data folder, you should have a file named `generated_[numbers_and_letters].csv`. You need to fill it in with the type of sale, method, price, duration, quantity, etc. The URL, blockchain and offer are already present.
> 
> If you can't find it, you may have deleted it. In this case, you will have to use the `sale_only` files and fill in all the necessary information (including the URLs of **each** NFT - which is very long).

Yes, I did get that random number/letter generated file with all the links to my asset and Blockchain. I do see I have to manually put in the price and duration in each. So I run this script when completed, correct? Thanks again for your time and efforts.

**Comment by maximedrn** [comment]
Yes, you have to do it. You can use Microsoft Visual Studio Code to complete many lines at once. (https://kencenerelli.wordpress.com/2018/03/25/visual-studio-code-multi-line-and-multi-cursor-editing/#:~:text=To%20employ%20multi%2Dline%20editing,%3A%20Opt%20%2B%20Cmd%20%2B%20Arrow%20Keys)
Windows: Ctrl + Alt + Arrow keys
Linux: Shift + Alt + Arrow Keys
Mac: Opt + Cmd + Arrow Keys

**Comment by Kisnobeats** [comment]
> Yes, you have to do it. You can use Microsoft Visual Studio Code to complete many lines at once. (https://kencenerelli.wordpress.com/2018/03/25/visual-studio-code-multi-line-and-multi-cursor-editing/#:~:text=To%20employ%20multi%2Dline%20editing,%3A%20Opt%20%2B%20Cmd%20%2B%20Arrow%20Keys)
> Windows: Ctrl + Alt + Arrow keys
> Linux: Shift + Alt + Arrow Keys
> Mac: Opt + Cmd + Arrow Keys

You are the best! Currently doing so now. Will run after and see if it worked on my end. Thanks again

**Comment by maximedrn** [comment]
I advise you to download version 1.5.7 of the bot. It creates files in case of upload or sale failure. It allows you to avoid having to search for NFTs that are not listed, etc.
Just copy and paste the file from the `assets/` folder of the old version of the bot to the latest one.

**Comment by Kisnobeats** [comment]
> I advise you to download version 1.5.7 of the bot. It creates files in case of upload or sale failure. It allows you to avoid having to search for NFTs that are not listed, etc. Just copy and paste the file from the `assets/` folder of the old version of the bot to the latest one.

So, redownload the repository, and replace the old "assets file" with the new. Thanks
