### ISSUE TITLE
Bot default to 7 days listing with CromeDriver

### ISSUE THREAD

**Issue by f80lrg** [maximedrn/opensea-automatic-bulk-upload-and-sale#126]
**Describe the problem:**
Using Windows 10 x64
Using latest version 1.5.7
Using Python 3.8.10
When using ChromeDriver to upload and sell. Sell is defaulting to 7 days instead of 1 month as per my structure below.  

 "levels": [],
      "stats": [],
      "unlockable_content": [],
      "explicit_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Ethereum",
      "sale_type": "Fixed Price",
      "price": 0.005,
      "duration": "1 month",
      "quantity": 1,
      "dna": "a01741b0d025151e4d4e274a0f72ffdce1f14cec",
      "edition": 514,
      "date": 1644800758175,
      "compiler": "HashLips Art Engine"

![image](https://user-images.githubusercontent.com/100087597/154855385-1aa064ef-9e97-4312-86c6-9e010527350e.png)

**Comment by maximedrn** [comment]
Follow this exact format in this order:
```json
{
     "nft": [
       {
         "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": "",
         "levels": [],
         "stats": [],
         "unlockable_content": [],
         "explicit_and_sensitive_content": false,
         "supply": 1,
         "blockchain": "Ethereum",
         "sale_type": "Fixed Price",
         "price": 0.005,
         "method": "",
         "duration": "1 month",
         "specific_buyer": "",
         "quantity": 1
       }
     ]
   }
```

**Comment by f80lrg** [comment]
Thanks for your help, that did it!
