### ISSUE TITLE
The I'm facing is, when I choose the sale only option with xlsx. The error commad appears as supply as to be an integer. My supply is 1. How to fix this?

### ISSUE THREAD

**Issue by pvtchrl3** [maximedrn/opensea-automatic-bulk-upload-and-sale#132]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
A clear and concise description of what the bug is and, if possible, how and when it occurs.

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
If applicable, include screenshots to help explain your problem.

**System Information:**
 - Operating system: Windows (32 or 64 bit), MacOS or a Linux distribution.
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used.
 - Version of the bot used.

**Additional context:**
Add here any other context about the problem.

**Comment by AitrusSG** [comment]
Having this same problem.  Attached is a sample in xlsx format.  Python version 3.9.7, Bot Version 1.5.7
[xlsx_structure_sale_only_error_example.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8119500/xlsx_structure_sale_only_error_example.xlsx)
.

**Comment by maximedrn** [comment]
Price must contains a dot and not a comma.
`0.004` and not `0,004`.
Duration required the hour and minutes.
`["DD-MM-YYYY hh:mm", "DD-MM-YYYY hh:mm"]`.

**Comment by AitrusSG** [comment]
Thanks dude!  Got it working!  I must have fat fingered it.  Also, thanks for calling out my date entry.  I did not catch that.

**Comment by pvtchrl3** [comment]
I fixed it brother, in XLSX the supply number type should be plain text, when we use automatic, it turns to be 1.0 so it doesn't work. It's fixed now.
