### ISSUE TITLE
Suggestion：Can you modify the main loop, it will be perfect

### ISSUE THREAD

**Issue by CandyChristina** [maximedrn/opensea-automatic-bulk-upload-and-sale#133]
Thanks for this useful tool，excellent！ 
and i found that： there is each metamask login and opensea login before the nft upload and sell，then the main loop go metamask and opensea login again for next upload and sell, if you can just do metamask and opensea login at first once，then upload and sell all nft without opensea logout, untill the structure file xlsx records are all done. then logout the opensea and metamask, i think it would be perfect.

**Comment by maximedrn** [comment]
Indeed, it would be better. But I can't. It is necessary to bypass reCAPTCHAs on the second and every 10 downloads.

**Comment by CandyChristina** [comment]
Thanks，i got it，So can we do a multi process of login +upload+ sell at the same time? instead of single process of login+upload+sell every time. to raise the performance and save the time.
