### ISSUE TITLE
Can anyone share a conversion script for HashLips Art Engine?

### ISSUE THREAD

**Issue by madstupid** [maximedrn/opensea-automatic-bulk-upload-and-sale#138]
Can you help with a script that can generate data file(s) from json files? 

i.e in my collection I've got files as follows:

1.png
2.png
1.json
2.json
.
.
.
_metadata.json

I need a script that will read "properties" from _metadata.json/*.json and generate "json_structure_upload_and_sale.json". I have looked at the file structure, I can read it and do it for a few NFTs but when you have a collection of NFTs then automating this works out better. Sorry, I don't have any coding skills and I also looked around, and I did not come across a solution that I can implemented in less time.

TIA

_metadata.json contents:

`[
  {
    "name": "Your Collection #1",
    "description": "Remember to replace this description",
    "image": "ipfs://NewUriToReplace/1.png",
    "dna": "a62c201a9a3d636137efafdefeda96ede4c88bbe",
    "edition": 1,
    "date": 1645259891645,
    "attributes": [
      {
        "trait_type": "bg",
        "value": "bg 2"
      },
      {
        "trait_type": "body",
        "value": "body"
      },
      {
        "trait_type": "cloak",
        "value": "cloak 9"
      },
      {
        "trait_type": "skull",
        "value": "skull 6"
      },
      {
        "trait_type": "eye",
        "value": "eye 3"
      },
      {
        "trait_type": "teeth",
        "value": "teeth 7"
      }
    ],
    "compiler": "HashLips Art Engine"
  },
  {
    "name": "Your Collection #2",
    "description": "Remember to replace this description",
    "image": "ipfs://NewUriToReplace/2.png",
    "dna": "727f1901a6df1ff318427614c4f55bb0e27b473e",
    "edition": 2,
    "date": 1645259893019,
    "attributes": [
      {
        "trait_type": "bg",
        "value": "bg 5"
      },
      {
        "trait_type": "body",
        "value": "body"
      },
      {
        "trait_type": "cloak",
        "value": "cloak 5"
      },
      {
        "trait_type": "skull",
        "value": "skull 4"
      },
      {
        "trait_type": "eye",
        "value": "eye 4"
      },
      {
        "trait_type": "teeth",
        "value": "teeth 4"
      }
    ],
    "compiler": "HashLips Art Engine"
  },`

**Comment by berkaytscc** [comment]
I actually used to have this json form. I managed to manipulate the json file for this automated bot. I assume that you use the same engine as I do. I can share the code with you if you want.(But you should create the nfts again)

**Comment by maximedrn** [comment]
I'm adding the "help wanted" label. I hope someone will share a conversion script before I create one.

**Comment by berkaytscc** [comment]
Well just look up for the 142th line and replace everything with this:
let tempMetadata = {
    file_path: `${basePath}\\${_edition}.png`,
    nft_name: `${namePrefix} #${_edition}`,
    external_link: "",
    description: "",
    collection: "",
    properties: attributesList,
    levels: "",
    stats: "",
    unlockable_content: false,
    explicit_and_sensitive_content: false,
    supply: 1,
    blockchain: "",
    sale_type: "",
    price: 0.1,
    method: "",
    duration: [],
    specific_buyer: false,
    quantity: "",
  };

**Comment by berkaytscc** [comment]
Carefull! "{basePath}\\YourNftFolder"

**Comment by madstupid** [comment]
I was thinking since we had the code to work with files as indicated in my 1st post, how difficult will it be to re-integrate the code in the latest code?

To do that we will prompt users to choose between the new method and the old method. We can use a log file to track files that were successfully uploaded and which file to upload next. I hope I am making sense.

I am unable to regenerate the nfts as I don't have the original artwork. I still hope this could be addressed.

**Comment by MythicNftClub** [comment]
[SOLVED]
Ok so here is what u need 
1. Goto scr/main.js paste main.txt rename main.js to mainbackup.js 

2. Paste main.txt into same location rename main.txt to main.js done

DONT FORGET To edit the new file and update to ur sale price network etc starting at line 139-ish in notpad++ TOO BEFORE RUNNING HASHLIPS GEN

When you run hashlips artgen the newly generated json file will have all the correct metadata.

Good luck I hope this solves ur issues

[main.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8214354/main.txt)

u can also just copy all the code below goto scr/main.js open file 1. Ctrl-a, 2. Del, 3. Ctrl-v, 4. Ctrl-s., 5. close main.js

DON'T FORGET 2 EDIT 

const basePath = process.cwd();
const { NETWORK } = require(`${basePath}/constants/network.js`);
const fs = require("fs");
const sha1 = require(`${basePath}/node_modules/sha1`);
const { createCanvas, loadImage } = require(`${basePath}/node_modules/canvas`);
const buildDir = `${basePath}/build`;
const layersDir = `${basePath}/layers`;
const {
  format,
  baseUri,
  description,
  external_link_name,
  collectionName,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
} = require(`${basePath}/src/config.js`);
const canvas = createCanvas(format.width, format.height);
const ctx = canvas.getContext("2d");
ctx.imageSmoothingEnabled = format.smoothing;
var metadataList = [];
var attributesList = [];
var dnaList = new Set();
const DNA_DELIMITER = "-";
const HashlipsGiffer = require(`${basePath}/modules/HashlipsGiffer.js`);

let hashlipsGiffer = null;

const buildSetup = () => {
  if (fs.existsSync(buildDir)) {
    fs.rmdirSync(buildDir, { recursive: true });
  }
  fs.mkdirSync(buildDir);
  fs.mkdirSync(`${buildDir}/json`);
  fs.mkdirSync(`${buildDir}/images`);
  if (gif.export) {
    fs.mkdirSync(`${buildDir}/gifs`);
  }
};

const getRarityWeight = (_str) => {
  let nameWithoutExtension = _str.slice(0, -4);
  var nameWithoutWeight = Number(
    nameWithoutExtension.split(rarityDelimiter).pop()
  );
  if (isNaN(nameWithoutWeight)) {
    nameWithoutWeight = 1;
  }
  return nameWithoutWeight;
};

const cleanDna = (_str) => {
  const withoutOptions = removeQueryStrings(_str);
  var dna = Number(withoutOptions.split(":").shift());
  return dna;
};

const cleanName = (_str) => {
  let nameWithoutExtension = _str.slice(0, -4);
  var nameWithoutWeight = nameWithoutExtension.split(rarityDelimiter).shift();
  return nameWithoutWeight;
};

const getElements = (path) => {
  return fs
    .readdirSync(path)
    .filter((item) => !/(^|\/)\.[^\/\.]/g.test(item))
    .map((i, index) => {
      return {
        id: index,
        name: cleanName(i),
        filename: i,
        path: `${path}${i}`,
        weight: getRarityWeight(i),
      };
    });
};

const layersSetup = (layersOrder) => {
  const layers = layersOrder.map((layerObj, index) => ({
    id: index,
    elements: getElements(`${layersDir}/${layerObj.name}/`),
    name:
      layerObj.options?.["displayName"] != undefined
        ? layerObj.options?.["displayName"]
        : layerObj.name,
    blend:
      layerObj.options?.["blend"] != undefined
        ? layerObj.options?.["blend"]
        : "source-over",
    opacity:
      layerObj.options?.["opacity"] != undefined
        ? layerObj.options?.["opacity"]
        : 1,
    bypassDNA:
      layerObj.options?.["bypassDNA"] !== undefined
        ? layerObj.options?.["bypassDNA"]
        : false,
  }));
  return layers;
};

const saveImage = (_editionCount) => {
  fs.writeFileSync(
    `${buildDir}/images/${_editionCount}.png`,
    canvas.toBuffer("image/png")
  );
};

const genColor = () => {
  let hue = Math.floor(Math.random() * 360);
  let pastel = `hsl(${hue}, 100%, ${background.brightness})`;
  return pastel;
};

const drawBackground = () => {
  ctx.fillStyle = background.static ? background.default : genColor();
  ctx.fillRect(0, 0, format.width, format.height);
};

const addMetadata = (_dna, _edition) => {
  let dateTime = Date.now();
  let tempMetadata = {
	file_path: `${baseUri}/${_edition}.png`,
    nft_name: `${namePrefix} #${_edition}`,
	external_link: external_link_name,
    description: description,
    collection: collectionName,
	properties: attributesList,
levels: [],
stats: [],
unlockable_content: [
  true,
  "UNLOCKABLE CONTENT"
],
    explicit_and_sensitive_content: false,
    supply: 1,
    blockchain: "Polygon",
    sale_type: "Fixed Price",
    price: 0.0051,
    method: [
      "Sell to highest bidder",
      0.0091
    ],
    duration: [
      "1 month"
    ],
    "specific_buyer": [
      false
    ],
    "quantity": 1,
    dna: sha1(_dna),
    edition: _edition,
    date: dateTime,
    ...extraMetadata,
    
    compiler: "mythic NFT Club",
  };
  if (network == NETWORK.sol) {
    tempMetadata = {
      //Added metadata for solana
      name: tempMetadata.name,
      symbol: solanaMetadata.symbol,
      description: tempMetadata.description,
      //Added metadata for solana
      seller_fee_basis_points: solanaMetadata.seller_fee_basis_points,
      image: `image.png`,
      //Added metadata for solana
      external_url: solanaMetadata.external_url,
      edition: _edition,
      ...extraMetadata,
      attributes: tempMetadata.attributes,
      properties: {
        files: [
          {
            uri: "image.png",
            type: "image/png",
          },
        ],
        category: "image",
        creators: solanaMetadata.creators,
      },
    };
  }
  metadataList.push(tempMetadata);
  attributesList = [];
};

const addAttributes = (_element) => {
  let selectedElement = _element.layer.selectedElement;
  attributesList.push({
    type: _element.layer.name,
    name: selectedElement.name,
  });
};

const loadLayerImg = async (_layer) => {
  return new Promise(async (resolve) => {
    const image = await loadImage(`${_layer.selectedElement.path}`);
    resolve({ layer: _layer, loadedImage: image });
  });
};

const addText = (_sig, x, y, size) => {
  ctx.fillStyle = text.color;
  ctx.font = `${text.weight} ${size}pt ${text.family}`;
  ctx.textBaseline = text.baseline;
  ctx.textAlign = text.align;
  ctx.fillText(_sig, x, y);
};

const drawElement = (_renderObject, _index, _layersLen) => {
  ctx.globalAlpha = _renderObject.layer.opacity;
  ctx.globalCompositeOperation = _renderObject.layer.blend;
  text.only
    ? addText(
        `${_renderObject.layer.name}${text.spacer}${_renderObject.layer.selectedElement.name}`,
        text.xGap,
        text.yGap * (_index + 1),
        text.size
      )
    : ctx.drawImage(
        _renderObject.loadedImage,
        0,
        0,
        format.width,
        format.height
      );

  addAttributes(_renderObject);
};

const constructLayerToDna = (_dna = "", _layers = []) => {
  let mappedDnaToLayers = _layers.map((layer, index) => {
    let selectedElement = layer.elements.find(
      (e) => e.id == cleanDna(_dna.split(DNA_DELIMITER)[index])
    );
    return {
      name: layer.name,
      blend: layer.blend,
      opacity: layer.opacity,
      selectedElement: selectedElement,
    };
  });
  return mappedDnaToLayers;
};

/**
 * In some cases a DNA string may contain optional query parameters for options
 * such as bypassing the DNA isUnique check, this function filters out those
 * items without modifying the stored DNA.
 *
 * @param {String} _dna New DNA string
 * @returns new DNA string with any items that should be filtered, removed.
 */
const filterDNAOptions = (_dna) => {
  const dnaItems = _dna.split(DNA_DELIMITER);
  const filteredDNA = dnaItems.filter((element) => {
    const query = /(\?.*$)/;
    const querystring = query.exec(element);
    if (!querystring) {
      return true;
    }
    const options = querystring[1].split("&").reduce((r, setting) => {
      const keyPairs = setting.split("=");
      return { ...r, [keyPairs[0]]: keyPairs[1] };
    }, []);

    return options.bypassDNA;
  });

  return filteredDNA.join(DNA_DELIMITER);
};

/**
 * Cleaning function for DNA strings. When DNA strings include an option, it
 * is added to the filename with a ?setting=value query string. It needs to be
 * removed to properly access the file name before Drawing.
 *
 * @param {String} _dna The entire newDNA string
 * @returns Cleaned DNA string without querystring parameters.
 */
const removeQueryStrings = (_dna) => {
  const query = /(\?.*$)/;
  return _dna.replace(query, "");
};

const isDnaUnique = (_DnaList = new Set(), _dna = "") => {
  const _filteredDNA = filterDNAOptions(_dna);
  return !_DnaList.has(_filteredDNA);
};

const createDna = (_layers) => {
  let randNum = [];
  _layers.forEach((layer) => {
    var totalWeight = 0;
    layer.elements.forEach((element) => {
      totalWeight += element.weight;
    });
    // number between 0 - totalWeight
    let random = Math.floor(Math.random() * totalWeight);
    for (var i = 0; i < layer.elements.length; i++) {
      // subtract the current weight from the random weight until we reach a sub zero value.
      random -= layer.elements[i].weight;
      if (random < 0) {
        return randNum.push(
          `${layer.elements[i].id}:${layer.elements[i].filename}${
            layer.bypassDNA ? "?bypassDNA=true" : ""
          }`
        );
      }
    }
  });
  return randNum.join(DNA_DELIMITER);
};

const writeMetaData = (_data) => {
  fs.writeFileSync(`${buildDir}/json/_metadata.json`, _data);
};

const saveMetaDataSingleFile = (_editionCount) => {
  let metadata = metadataList.find((meta) => meta.edition == _editionCount);
  debugLogs
    ? console.log(
        `Writing metadata for ${_editionCount}: ${JSON.stringify(metadata)}`
      )
    : null;
  fs.writeFileSync(
    `${buildDir}/json/${_editionCount}.json`,
    JSON.stringify(metadata, null, 2)
  );
};

function shuffle(array) {
  let currentIndex = array.length,
    randomIndex;
  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }
  return array;
}

const startCreating = async () => {
  let layerConfigIndex = 0;
  let editionCount = 1;
  let failedCount = 0;
  let abstractedIndexes = [];
  for (
    let i = network == NETWORK.sol ? 0 : 1;
    i <= layerConfigurations[layerConfigurations.length - 1].growEditionSizeTo;
    i++
  ) {
    abstractedIndexes.push(i);
  }
  if (shuffleLayerConfigurations) {
    abstractedIndexes = shuffle(abstractedIndexes);
  }
  debugLogs
    ? console.log("Editions left to create: ", abstractedIndexes)
    : null;
  while (layerConfigIndex < layerConfigurations.length) {
    const layers = layersSetup(
      layerConfigurations[layerConfigIndex].layersOrder
    );
    while (
      editionCount <= layerConfigurations[layerConfigIndex].growEditionSizeTo
    ) {
      let newDna = createDna(layers);
      if (isDnaUnique(dnaList, newDna)) {
        let results = constructLayerToDna(newDna, layers);
        let loadedElements = [];

        results.forEach((layer) => {
          loadedElements.push(loadLayerImg(layer));
        });

        await Promise.all(loadedElements).then((renderObjectArray) => {
          debugLogs ? console.log("Clearing canvas") : null;
          ctx.clearRect(0, 0, format.width, format.height);
          if (gif.export) {
            hashlipsGiffer = new HashlipsGiffer(
              canvas,
              ctx,
              `${buildDir}/gifs/${abstractedIndexes[0]}.gif`,
              gif.repeat,
              gif.quality,
              gif.delay
            );
            hashlipsGiffer.start();
          }
          if (background.generate) {
            drawBackground();
          }
          renderObjectArray.forEach((renderObject, index) => {
            drawElement(
              renderObject,
              index,
              layerConfigurations[layerConfigIndex].layersOrder.length
            );
            if (gif.export) {
              hashlipsGiffer.add();
            }
          });
          if (gif.export) {
            hashlipsGiffer.stop();
          }
          debugLogs
            ? console.log("Editions left to create: ", abstractedIndexes)
            : null;
          saveImage(abstractedIndexes[0]);
          addMetadata(newDna, abstractedIndexes[0]);
          saveMetaDataSingleFile(abstractedIndexes[0]);
          console.log(
            `Created edition: ${abstractedIndexes[0]}, with DNA: ${sha1(
              newDna
            )}`
          );
        });
        dnaList.add(filterDNAOptions(newDna));
        editionCount++;
        abstractedIndexes.shift();
      } else {
        console.log("DNA exists!");
        failedCount++;
        if (failedCount >= uniqueDnaTorrance) {
          console.log(
            `You need more layers or elements to grow your edition to ${layerConfigurations[layerConfigIndex].growEditionSizeTo} artworks!`
          );
          process.exit();
        }
      }
    }
    layerConfigIndex++;
  }
  writeMetaData(JSON.stringify({ nft: metadataList }, null, 2));
};

module.exports = { startCreating, buildSetup, getElements };

**Comment by MythicNftClub** [comment]
[SOLVED]
Ok so here is what u need 
1. Goto scr/main.js paste main.txt rename main.js to mainbackup.js 
2. rename main.txt to main.js done


DONT FORGET To edit the new file and update to ur sale price network etc starting at line 139-ish in notpad++ TOO BEFORE RUNNING HASHLIPS GEN

When you run hashlips artgen the newly generated json file will have all the correct metadata.

Good luck I hope this solves ur issues

[main.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8214354/main.txt)



DON'T FORGET 2 EDIT
