### ISSUE TITLE
Clarification Needed: Uploads 1, closes, opens, and repeats

### ISSUE THREAD

**Issue by Kisnobeats** [maximedrn/opensea-automatic-bulk-upload-and-sale#139]
I have used this script several times, and with great luck after you have helped me with my problems.

I started a mew collection and began uploading when I realized it's only uploading 1 FT, closes Chrome, opens Chrome, signs in again, and then uploads another NFT to repeat the process. Has Opensea re-enabled Captchas and this is why the bot is programmed as such?

Thank you for all the support!

**Comment by maximedrn** [comment]
That's exactly why. ReCAPTCHAs are impossible to solve without using paid solutions. In order to get around this, I re-run the webdriver at each upload, so OpenSea doesn't ask you to prove that you are human.

**Comment by Kisnobeats** [comment]
> That's exactly why. ReCAPTCHAs are impossible to solve without using paid solutions. In order to get around this, I re-run the webdriver at each upload, so OpenSea doesn't ask you to prove that you are human.

Thank you for clarifying! You da man!
