### ISSUE TITLE
Launch Error. List index out of range

### ISSUE THREAD

**Issue by timberlineHD** [maximedrn/opensea-automatic-bulk-upload-and-sale#140]
**Before opening the issue:**
Thank you for this code.  Cleanest I've seen in my question to bulk upload to OpenSea.  I cam to your code via the Udemy guy who copied your code for his video.  I have read the READ ME, and to the best of my ability I have updated Python, etc.

**Describe the problem:**
When trying to execute and Upload Only .json file I am able to get signed in to both Metamask and to OpenSea.  However, Chrome then closes and I get the phrase "Launch error. List index out of range."  The process then loops until I terminate.

I am not a developer and my coding knowledge is extremely limited.  Fearing that my syntax was not right I started over with a new .json file duplicated directly from your demo files.  I only swapped out my data.  I have attached.

**Screenshots and excerpts:**
Error Code screenshot and .json file attached.

**System Information:**
 MacOS version 12.2.1
 - Webdriver used (I tried both of these, btw):
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used - 3.7 for MacOS
![Screen Shot 2022-02-22 at 6 42 12 PM](https://user-images.githubusercontent.com/100249390/155248993-bd3cb9da-f88c-4165-93e0-d89090b47c58.png)
<img width="582" alt="Screen Shot 2022-02-22 at 6 29 43 PM" src="https://user-images.githubusercontent.com/100249390/155248995-3514f819-4e22-495c-bf29-b517b5856ec4.png">

 - Version of the bot used - 1.5.7 I believe, the latest.

**Additional context:**
Uploaded the json file as TXT as couldn't upload as json.

Thanks again.
[_metadata.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8121310/_metadata.txt)

**Comment by alexisprevot** [comment]
Hi, I face this issue.
It seems that your data is missing some parameters.
Double check if there is all information the script need to run

**Comment by maximedrn** [comment]
This should work:
You forgot stats and levels.
```json
{
     "nft": [
       {
         "file_path": "/Users/vbhd/opensea-automatic-bulk-upload-and-sale-master/images/1.png",
         "nft_name": "Crypto Tall Ships #1",
         "external_link": "https://cryptotallships.com",
         "description": "Ahoy, Me Hearties!  Thar be treasure on the high seas! Avast ye ... ye never know what perils lurk above the waves, or in the depths below! Mermaids and mermen, vengeful whales with fiery eyes, and even the mighty kraken! Collect ye a Crypto Tall Ship, and set sail to claim your bit(coins) of eight!",
         "collection": "Crypto Tall Ships",
         "properties": [
          {
            "type": "SKY",
            "name": "BLUE HOUR "
          },
          {
            "type": "CLOUDS",
            "name": "VAR 1 "
          },
          {
            "type": "SHIP",
            "name": "CANNON L "
          },
          {
            "type": "FLAG R",
            "name": "GREEN "
          },
          {
            "type": "FLAG L",
            "name": "BLUE "
          },
          {
            "type": "SEA",
            "name": "CALM BLU "
          },
          {
            "type": "CREATURE 3",
            "name": "GULLS "
          },
          {
            "type": "CREATURE 1",
            "name": "ORG WHALE "
          }
         ],
         "stats": "",
         "levels": "",
         "unlockable_content": false,
         "explicit_and_sensitive_content": false,
         "supply": 1,
         "blockchain": "Polygon"
       }
     ]
   }

```

**Comment by timberlineHD** [comment]
Thank you!  Totally missed that. Also didn't realize the issues I was having with my file path.  This worked.  Much appreciated!
