### ISSUE TITLE
MacOS: Datetime duration format issue with XLSX

### ISSUE THREAD

**Issue by alexisprevot** [maximedrn/opensea-automatic-bulk-upload-and-sale#141]
Hi,

First thanks to your work.

System Information :
MacOS version 12.0.1

Webdriver used :
GeckoDriver - Mozilla Firefox,
ChromeDriver - Google Chrome.
Python version used - 3.9.10 for MacOS

I'm facing an issue when setting up the duration.

The NFT is uploaded correctly but when selling it, the date format is not working properly.

Here is the file : [xlsx_structure_upload_and_sale_example_model.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8124147/xlsx_structure_upload_and_sale_example_model.xlsx)

Here is a screen of the error : 
<img width="727" alt="Capture d’écran 2022-02-23 à 12 25 17" src="https://user-images.githubusercontent.com/11993949/155316538-780fb8f8-ca60-49bf-8651-fdc142c3a1f6.png">

But the date format seems pretty good in my file

Thanks for your feedback

**Comment by maximedrn** [comment]
I tried on my side with the duration of your XLSX file. It works fine.
If this error persists, can you send me a short video of what the bot is doing at that time.

**Comment by alexisprevot** [comment]
I try it with ChromeDriver - Google Chrome. and it's not working. For the 2nd one (GeckoDriver - Mozilla Firefox,) it's not working. Very strange

**Comment by maximedrn** [comment]
I'll look at this and try to fix it

**Comment by stackzwolle** [comment]
u can try this
somewhere line 474, swap d and m
def opensea_sale(self, number: int, date: str = '%d-%m-%Y %H:%M') -> None:

so u have like this
def opensea_sale(self, number: int, date: str = '%m-%d-%Y %H:%M') -> None:

my time format diff so i do that

**Comment by maximedrn** [comment]
> u can try this somewhere line 474, swap d and m def opensea_sale(self, number: int, date: str = '%d-%m-%Y %H:%M') -> None:
> 
> so u have like this def opensea_sale(self, number: int, date: str = '%m-%d-%Y %H:%M') -> None:
> 
> my time format diff so i do that

@alexisprevot is using "day-month-year" format in his file. I don't think it will change anything. My bot changes the day and month to be compatible with the OpenSea UK duration format.
The main problem comes from the OS, I think the Selenium version of macOS works differently with the `send_keys()` method.

**Comment by maximedrn** [comment]
Hello, is this error still present for MacOS (or even Linux) users?
