### ISSUE TITLE
Issue while signing in while selling

### ISSUE THREAD

**Issue by pvtchrl3** [maximedrn/opensea-automatic-bulk-upload-and-sale#144]
When I try to list the items using the xlsx, it doesn't automatically sign in when I complete listing. Always I got to click on sign in option. Can you fix this?

in open sea it doesn't show a listed in the wall, it shows only when I go into the item. When I sell manually, it shows at first time.

**Comment by maximedrn** [comment]
Edit: I've released a new version that seems to fix any problems in the `sale()` method.
However, you need to be sure that, for the Ethereum blockchain, you have done an initial listing manually and paid a gas fee to unlock your wallet on OpenSea. Next, please check your file and compare it with the examples in the `data/` file or by reading the README file on Github.

**Comment by pvtchrl3** [comment]
Please, can you check this?

**Comment by maximedrn** [comment]
This error occurs when the robot tried to click on the "Sign" button of the MetaMask popup window, right?
> There's another problem when I use the upload and sell script using JSON metadata, I couldn't enter the price as 0.001. It automatically chooses 1 ETH.

Check the structure of the files in the `assets/` folder. Even if they are empty, all details must be mentioned.

**Comment by pvtchrl3** [comment]
![IMG-20220301-WA0013](https://user-images.githubusercontent.com/99459461/156216321-99c11e4d-04da-4c51-aab3-4892fb5c47a8.jpg)
Will this help?

**Comment by maximedrn** [comment]
Right click on the button a second time to open the element inspector and select "Inspect". It should display the HTML code of the button.

**Comment by pvtchrl3** [comment]
Is this one, right?

This issue only happens when I use sale only option.
![Screenshot (6)](https://user-images.githubusercontent.com/99459461/156292234-2bdd4de2-753c-4882-826c-182b6015c6f5.png)

**Comment by maximedrn** [comment]
Thank you for your help, I have downloaded a version that _**may**_ solve this problem.
**I need feedback**, it works fine on my end so I am doing this blind.

**Comment by pvtchrl3** [comment]
No brother, it's not working. This time after the complete listing button is clicked by the robot, the Metamask pop up doesn't even open. CMD shows as unable to sign in to MetaMask. How can we fix this?

**Comment by pvtchrl3** [comment]
Screenshot of the open sea and CMD
In Open sea the complete listing button gets highlighted(maybe clicked) but it doesn't open the metamask pop-up.

CMD shows the result of what happens when it gets canceled.

![Screenshot (8)](https://user-images.githubusercontent.com/99459461/156503104-f69e217d-e6f2-4d69-ac42-6601559f8fff.png)
![Screenshot (9)](https://user-images.githubusercontent.com/99459461/156503097-e449e19d-7293-40e8-8f11-98f0db5df32c.png)

**Comment by maximedrn** [comment]
> ![Screenshot (9)](https://user-images.githubusercontent.com/99459461/156503097-e449e19d-7293-40e8-8f11-98f0db5df32c.png)

"Listing price must be greater than $5"
You have to change this in your file, try 0.002

**Comment by pvtchrl3** [comment]
I did and it stops here


![Screenshot (11)](https://user-images.githubusercontent.com/99459461/156504229-01a3eec2-7f8b-420a-bb91-de4bae74fea4.png)

**Comment by maximedrn** [comment]
New feature on Polygon, you have to click on this button and sign manually the MetaMask contract. You have to do it once. Then it should work for every NFTs :)

**Comment by pvtchrl3** [comment]
Nope, it's not working, the same old issue. It doesn't get signed in automatically. We're back to box 1

**Comment by pvtchrl3** [comment]
Here's the HTML code for the sign button


![Screenshot 2022-03-03 122032](https://user-images.githubusercontent.com/99459461/156512043-49178684-65de-4c1b-aaae-3763f8248db8.png)

**Comment by chamaeleo** [comment]
@maximedrn, @pvtchrl3 

I suggest to be sure that the sign button is visible. I have the same issue with firefox in headless mode (only in headless mode). I diagnosed it by asking the webdriver for a screenshot before clicking. 

I suggest to add the line "web.visible" to check that the button is visible.

Find this part of code in **sale()**

```
try: # Polygon blockchain requires a click on a button.
    if structure.blockchain == 'Polygon':
        #web.driver.save_screenshot('diag_when_headless.png')
        web.visible('//div[@class="ActionPanel--content"]/button[contains(text(), "Sign")]')
        web.clickable( # Click on the "Sign" button.
                '//div[@class="ActionPanel--content"]/button[contains(text(), "Sign")]')
```

**Comment by pvtchrl3** [comment]
No, it's not working. I tried both Chrome and Gecko drivers. The results are the same and the error is "MetaMask Sign-in Error" @chamaeleo Thank you but after adding your code, the script isn't even working. Please help me fix this.

**Comment by chamaeleo** [comment]
@pvtchrl3, Could you share a screenshot of the code you changed? It might just be a simple indentation issue.

**Comment by maximedrn** [comment]
This is a stupid question, but what is the resolution of your screen?
Maybe the button is not accessible for that reason.
On my side, the button is clicked, so it should be the same on yours.

**Comment by maximedrn** [comment]
So it can be from your file. Can you send me an excerpt of your file please?

**Comment by pvtchrl3** [comment]
![Screenshot_20220304_223134](https://user-images.githubusercontent.com/99459461/156807072-e6cd29aa-63ff-4e1f-85b0-f2fdd7373e0c.jpg)

**Comment by maximedrn** [comment]
URLs are auto-generated by the bot, right?

**Comment by pvtchrl3** [comment]
Yes, but it was created in csv ending with polygon and price details from json. I removed it and pasted only the links.

**Comment by maximedrn** [comment]
> Yes, but it was created in csv ending with polygon and price details from json. I removed it and pasted only the links.

Ok then every NFTs is on the Ethereum blockchain.

**Comment by pvtchrl3** [comment]
I use polygon but if I add polygon here in xlsx it doesn't work.

**Comment by maximedrn** [comment]
Which blockchain did you select when uploading your NFTs?

**Comment by maximedrn** [comment]
![](https://user-images.githubusercontent.com/91475935/156810016-0c9e317d-cd2d-4929-aa03-a04e48d4a13a.png)

Moreover, as you can see on the picture, the duration is incorrect: "Start date must be now or in the future".

**Comment by pvtchrl3** [comment]
Thanks, brother, it's working. I'm sorry for causing this trouble. It was my mistake after all. Thank you so much and you have done a great job. I appreciate it.

bio.link/pvtchrl3 is my social media link and if you like you can get connected with me.
