### ISSUE TITLE
Hashlips Art Engine conversion script (Duplicate)

### ISSUE THREAD

**Issue by acejou27** [maximedrn/opensea-automatic-bulk-upload-and-sale#150]
Hello, I made png and json with a program that automatically generates nft images, but my json format cannot meet your needs, can you guide me how to add or modify some json contents?

**Comment by berkaytscc** [comment]
if you use hashlips engine I manipulated that engine to create json files for @maximedrn's format

**Comment by Karthikg09** [comment]
> if you use hashlips engine I manipulated that engine to create json files for @maximedrn's format

Can you please send the code

**Comment by madstupid** [comment]
Look at the code on the link below:

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/138#issuecomment-1049105612

**Comment by riyadfebrian** [comment]
> Hello, I made png and json with a program that automatically generates nft images, but my json format cannot meet your needs, can you guide me how to add or modify some json contents?

I just made a python code for converting hashlip format to the bot format. ping me for the code

**Comment by maximedrn** [comment]
I close this issue (duplicate).

**Comment by MythicNftClub** [comment]
[SOLVED]
Ok so here is what u need

Goto scr/main.js paste [main.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8214354/main.txt) rename main.js to mainbackup.js
rename main.txt to main.js done
DONT FORGET To edit the new file and update to ur sale price network etc starting at line 139-ish in notpad++ TOO BEFORE RUNNING HASHLIPS GEN

When you run hashlips artgen the newly generated json file will have all the correct metadata.

Good luck I hope this solves ur issues

main.txt

DON'T FORGET 2 EDIT

**Comment by acejou27** [comment]
> [SOLVED] Ok so here is what u need
> 
> Goto scr/main.js paste [main.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8214354/main.txt) rename main.js to mainbackup.js rename main.txt to main.js done DONT FORGET To edit the new file and update to ur sale price network etc starting at line 139-ish in notpad++ TOO BEFORE RUNNING HASHLIPS GEN
> 
> When you run hashlips artgen the newly generated json file will have all the correct metadata.
> 
> Good luck I hope this solves ur issues
> 
> main.txt
> 
> DON'T FORGET 2 EDIT

I use the new main.py but the created json file still fails when uploading and selling, please help me, thanks

**Comment by MythicNftClub** [comment]
> I use the new main.py but the created JSON file still fails when uploading and selling, please help me, thanks

Ok after u replace main.py you will need to re-run the art gen so that hashlips art-gen will re-generate a new JSON along with a new collection of NFT's,
In conclusion, you will just need to re-run the hashlips Art-generator one last time to create  a new collection which will generate a new compatible JSON file for open sea.
Good luck

**Comment by acejou27** [comment]
Thanks for the guide, I'll try again, the image I regenerated before keeps failing when uploading, thank you again

**Comment by MythicNftClub** [comment]
No worries i wish u the best of luck with your NFT collection/launch

**Comment by acejou27** [comment]
The following message appears when I use the json generated by the new main.py to be put on the shelf and sold

Traceback (most recent call last):
  File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 1057, in <module>
    reader = Reader(data_file()) # Ask for a file and read it.
  File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 65, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 71, in extract_json_file
    self.file = loads(open(self.path, encoding='utf-8').read())['nft']
KeyError: 'nft'

May I ask where is the setting wrong? Or is it because I use m1 mac? Thanks

**Comment by acejou27** [comment]
> 不用擔心，我祝你在 NFT 收藏/發布中好運

The data I generated is as follows

{
  "file_path": "/Users/ace/Documents/NFT/hsahlips engine/build/images/1.png",
  "nft_name": "DAWUMA #1",
  "description": "This is DAWUMA",
  "properties": [
    {
      "type": "Background",
      "name": "grey blue"
    },
    {
      "type": "Decorate",
      "name": "flax ornament"
    },
    {
      "type": "Body",
      "name": "pink"
    },
    {
      "type": "Clothes",
      "name": "brack"
    },
    {
      "type": "Eyebrow",
      "name": "eyebrow 3"
    },
    {
      "type": "Feature",
      "name": "feature6"
    },
    {
      "type": "Lefteye",
      "name": "left eye 3"
    },
    {
      "type": "Righteye",
      "name": "right eye 3"
    },
    {
      "type": "Text",
      "name": "lucky"
    }
  ],
  "levels": [],
  "stats": [],
  "unlockable_content": [
    true,
    "UNLOCKABLE CONTENT"
  ],
  "explicit_and_sensitive_content": false,
  "supply": 1,
  "blockchain": "Polygon",
  "sale_type": "Fixed Price",
  "price": 0.0051,
  "method": [
    "Sell to highest bidder",
    0.0091
  ],
  "duration": [
    "1 month"
  ],
  "specific_buyer": [
    false
  ],
  "quantity": 1,
  "dna": "5f82cbae89616cc23644e15910654d7dca02e887",
  "edition": 1,
  "date": 1651039720550,
  "compiler": "mythic NFT Club"
}

Is there anything wrong? Thanks

**Comment by MythicNftClub** [comment]
> The following message appears when I use the json generated by the new main.py to be put on the shelf and sold
> 
> Traceback (most recent call last): File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 1057, in reader = Reader(data_file()) # Ask for a file and read it. File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 65, in **init** eval(f'self.extract_{self.extension}_file()') File "", line 1, in File "/Users/ace/Documents/NFT/opensea-automatic-bulk-upload-and-sale-master/main.py", line 71, in extract_json_file self.file = loads(open(self.path, encoding='utf-8').read())['nft'] KeyError: 'nft'
> 
> May I ask where is the setting wrong? Or is it because I use m1 mac? Thanks

tbh I'm not sure after open sea Recaptcha changes CBF   I stopped uploading my collections 
yeah I'm running win 10 not 100%  sure why ur getting these issues 

Only thing i can think of that might help main (only edit scr/main.js paste [main.txt] (https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8214354/main.txt) rename main.js
try this version: https://github.com/MythicNftClub/hashlips_art_engine
this version was working when i made the changes

**Comment by acejou27** [comment]
> 

Thank you very much, I will download the new hashlips to test, if not I will test the intel computer again, thanks

**Comment by MythicNftClub** [comment]
> > 
> 
> Thank you very much, I will download the new hashlips to test, if not I will test the intel computer again, thanks

good luck
