### ISSUE TITLE
File doesn\'t exist or path is incorrect

### ISSUE THREAD

**Issue by Karthikg09** [maximedrn/opensea-automatic-bulk-upload-and-sale#151]
Hello, I generated JSON files and edited them according to your file structure. The images are named as 1,2,3,4, ...... 10000.png
I pasted that image location in JSON file and while running the code il am getting File doesn\'t exist or path is incorrect error

Should I rename the images?
How to rename that in JSON file?
Or how can I solve this in the main code?

Please help me

**Comment by maximedrn** [comment]
Hello,
What is the file path? I cannot do anything if you do not give me an example.

**Comment by madstupid** [comment]
@Karthikg09 

Please check the link below and advise how you managed to do the JSON file? You could have a solution to my request.

[https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/138#issue-1146794383](url)

**Comment by Karthikg09** [comment]
> Hello, What is the file path? I cannot do anything if you do not give me an example.
[_metadata - Copy.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8148811/_metadata.-.Copy.txt)
I have attached my JSON file.

I think the ordering is different compared to you
I that is the case how can I correct that in bulk?

Thanks for the help

**Comment by maximedrn** [comment]
Your file structure is incorrect, you should have something that look like this: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/blob/master/data/json_structure_upload_and_sale.json
Everything must be present in this order.

**Comment by Karthikg09** [comment]
Now how can i edit that?
in bulk

**Comment by maximedrn** [comment]
You may have to regenerate the file.
Someone showed a way to create a compatible file from the HashLips engine:
[https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/138#issue-1146794383](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/url)

**Comment by maximedrn** [comment]
I close this issue, the main problem has been corrected.
