### ISSUE TITLE
Cannot login to MetaMask (GeckoDriver).

### ISSUE THREAD

**Issue by edie99** [maximedrn/opensea-automatic-bulk-upload-and-sale#154]
I am trying to use GeckoDriver to upload NTFs, but it cannot login to MetaMask. 
The MM extension is installed. It works fine with ChromeDriver

**Comment by maximedrn** [comment]
Hello, I don't have this problem on my side, everything works fine.
I need more details about your PC.
- What is your operating system?
- What version of Python are you using?
- Is Mozilla Firefox installed on your PC?
- If so, what version is it?
- Are you sure that your secret key and password are both correct?

**Comment by edie99** [comment]
Hello,

thank You for your answer

I use Windows 10 + Python 3.10.2 + Mozilla 97.01
Secret key & password are OK, it works with Chrome Extension

e


> Hello, I don't have this problem on my side, everything works fine. I need more details about your PC.
> 
> * What is your operating system?
> * What version of Python are you using?
> * Is Mozilla Firefox installed on your PC?
> * If so, what version is it?
> * Are you sure that your secret key and password are both correct?

**Comment by maximedrn** [comment]
I'm using version 3.9.9, you may try with it.
I'll try by using Python 3.10. I will keep you informed.

**Comment by maximedrn** [comment]
I've just tried with Python 3.10.2 and it works great with the GeckoDriver v0.30 (Mozilla Firefox 97.0.1).
At line 266, can you update the code with this:
```python
def firefox(self) -> webdriver:
        """Start a Firefox webdriver and return its state."""
        options = webdriver.FirefoxOptions()  # Configure options for Firefox.
        # options.add_argument('--headless')  # Headless mode.
        options.add_argument('--log-level=3')  # No logs is printed.
        options.add_argument('--mute-audio')  # Audio is muted.
        options.set_preference('intl.accept_languages', 'en,en-US')
        driver = webdriver.Firefox(service=SG(  # DeprecationWarning using
            self.browser_path), options=options)  # executable_path.
        driver.install_addon(self.metamask_extension_path)  # Add extension.
        driver.maximize_window()  # Maximize window to reach all elements.
        return driver
```
It will remove the headless mode, can you send me a video of what happens?

**Comment by maximedrn** [comment]
I close this issue due to inactivity. Reopen it if you still have this problem.
