### ISSUE TITLE
Issue while using the bot.

### ISSUE THREAD

**Issue by debpodder** [maximedrn/opensea-automatic-bulk-upload-and-sale#155]
Hello I'm getting the following error:

Traceback (most recent call last):
  File "main.py", line 903, in <module>
    reader = Reader(data_file())  # Ask for a file and read it.
  File "main.py", line 63, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "main.py", line 71, in extract_json_file
    self.file = loads(open(self.path, encoding='utf-8').read())['nft']
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 72 column 4 (char 1449)

**Comment by maximedrn** [comment]
Open your file, on line 72 you forget a "," at the end.

**Comment by debpodder** [comment]
Hello, "," it was already there. I don't know why the error was still showing? When I replaced the following part the error started. Is this part is essential? Can you kindly explain?

 "levels": [
           {
             "name": "Speed",
             "from": 2,
             "to": 5
           },
           {
             "name": "Width",
             "from": 2,
             "to": 15
           }
         ],
         "stats": [
           {
             "name": "Strenght",
             "from": 1,
             "to": 10
           },
           {
             "name": "Age",
             "from": 1,
             "to": 9
           }
         ],

**Comment by debpodder** [comment]
Now it is running after I removed that. And it is automatically selling with 1 ETH (though I've mentioned 0.01 ETH). But ultimately it is unable to sell.

**Comment by debpodder** [comment]
Ok, 1 comma was missing in line 71.

**Comment by windswept321** [comment]
> Ok, 1 comma was missing in line 71. But what about the selling?

This sounds like the issue I'm having. There were recent changes to how ETH NFTs are listed there, and it seems like the most recent commits don't fix this.

**Comment by mrandall101** [comment]
I think the json indexes are not correct.  It uses indexes to tell where it is within the json.  Make sure price is index 13 I think.

**Comment by mrandall101** [comment]
And it's based off of which data structure you used to upload, the structure I used was json_structure_upload_and_sale.
