### ISSUE TITLE
File doesn't exist or path is incorrect error

### ISSUE THREAD

**Issue by HaiderZafarKhan** [maximedrn/opensea-automatic-bulk-upload-and-sale#156]
![Screenshot (2219)](https://user-images.githubusercontent.com/51001824/156615441-ee5a9496-dade-4926-b819-e8062615afb5.png)

**Comment by maximedrn** [comment]
Can you send me an excerpt of your metadata file please?

**Comment by HaiderZafarKhan** [comment]
![Screenshot (2224)](https://user-images.githubusercontent.com/51001824/156641562-a075679a-9f12-4b1e-b0aa-5bb5da07086c.png)
![Screenshot (2225)](https://user-images.githubusercontent.com/51001824/156641576-892fbf8c-33a2-4520-80de-ec65029f7510.png)

**Comment by HaiderZafarKhan** [comment]
Please help me in this matter. I will be very thankful to you.

**Comment by maximedrn** [comment]
Are you sure that the file path is correct?

**Comment by HaiderZafarKhan** [comment]
Yes, it is correct.

**Comment by maximedrn** [comment]
It seems that the file path is incorrect :/
Copy the path and paste it into the search bar of the file explorer, then press the Enter key.
You should not be able to reach this path.

**Comment by HaiderZafarKhan** [comment]
Ok, I'll check it out.

**Comment by HaiderZafarKhan** [comment]
My recent problem has been resolved. Thank you so so much Sir. Thanks alot.
