### ISSUE TITLE
Opensea Login Fail

### ISSUE THREAD

**Issue by poc1127** [maximedrn/opensea-automatic-bulk-upload-and-sale#159]
**Describe the problem:**
All else works. Metamask login successful. As shown in the screen capture, Fails to login on Opensea.

**Screenshots and excerpts:**
Screenshot attached

**System Information:**
 - Operating system: Windows 64 bit
 - Webdriver used: ChromeDriver - Google Chrome.
- Python version used: 3.10.2
 - Version of the bot used (Version 1.5.11 - March 02, 2022).

Please help me out. I get a pop up on metamask extension as well. So I opened it and clicked connect thinking that Opensea is not logging in because metamask is not connected. But not sure.

Has anyone solved this problem? or facing the same issue? Please help

![image](https://user-images.githubusercontent.com/100990701/156874091-8ae13041-7560-4297-b1b5-11bd82feb803.png)

**Comment by maximedrn** [comment]
The bot opened 3 tabs, it should only have 2.
Can you send me a video of what's going on, please?

**Comment by poc1127** [comment]
Hi Max,

Here, I attached the video. I think it may be because of the popup 

https://user-images.githubusercontent.com/100990701/156876944-c4378464-3cb5-4887-ba78-3c8fad6b4d5d.mp4

**Comment by poc1127** [comment]
Solved the first tab issue. Solved it with this link 

https://support.leapwork.com/hc/en-us/articles/115001642052-Chrome-browser-is-opening-Settings-as-the-default-tab-and-asking-to-reset-chrome-settings

-Open a run box by pressing the Windows key + R: 
-Type ‘regedit’ and press OK, Registry Editor will open.
-There is a setting in the registry that's causing it. In the registry, it's under -
-HKEY_CURRENT_USER\Software\Google\Chrome\TriggeredReset
-Delete the TriggeredReset key and then close RegEdit.

**Comment by maximedrn** [comment]
> And after doing that , chrome shutsdown, reopens, re-logs into metamask and opensea after each upload.

This is the purpose of the "reCAPTCHA bypass" in version 1.5.X.
Now that the reCAPTCHA is for every download, it is not necessary.
For now I can't do anything and prefer to wait for updates from OpenSea team.

**Comment by maximedrn** [comment]
I close this issue. Main issue is solved and new issue come from reCAPTCHAs (duplicate).
