### ISSUE TITLE
Sale of the NFT. NFT sale cancelled. Message: Cannot sign the MetaMask contract.

### ISSUE THREAD

**Issue by poc1127** [maximedrn/opensea-automatic-bulk-upload-and-sale#161]
Not sure why I'm getting this ?

![image](https://user-images.githubusercontent.com/100990701/156894861-608aa775-133c-4162-8005-1191e45ee2ad.png)

below is my metadata.json.   Is there a problem with date? I saw that it stays at 7 days . Did not see the date change while bot was running

![image](https://user-images.githubusercontent.com/100990701/156894900-acdf188d-f096-494e-8c0c-2455fb45e554.png)

**Comment by maximedrn** [comment]
Wyvern 2.3, I'm still working on this.

**Comment by poc1127** [comment]
> Wyvern 2.3, I'm still working on this.

Ok. I hope it gets solved soooon.  suppose that there is nothing wrong with my metadata then

![image](https://user-images.githubusercontent.com/100990701/156895271-eb43949f-8dfb-4a4a-89e3-6cd73ff7015c.png)

![image](https://user-images.githubusercontent.com/100990701/156895257-62c8fa16-9ac9-45ea-8a5f-28394dcac341.png)

**Comment by poc1127** [comment]
Signing issue. Just uploading image capture for others to see. 
![image](https://user-images.githubusercontent.com/100990701/156895797-5c7a00dc-7ce9-49b4-aad2-e81be36356e1.png)

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and debug it

**Comment by poc1127** [comment]
> You will have to synchronize your wallet and debug it

What do you mean? It seems like, as it's writte, the scrolling isn't happening, therefore sign button is not clicked. That is the issue. My wallet is sychronized. Logs in all fine.

**Comment by Yuxanju** [comment]
Since your wallet is synchronize then you have to debug and then after you
reboot your device . The sign button will click afterward.. The ellipal url
have the bech13 that will help with the debugging .!i can send you the url
and all you have to do is to follow the url till you get to debug and you
click on that

**Comment by maximedrn** [comment]
I've uploaded an update that seems to work for the new Wyvern 2.3 contract.
By the way I close this issue because it's a duplicate.
