### ISSUE TITLE
.CSV file poorly structured 

### ISSUE THREAD

**Issue by stackzwolle** [maximedrn/opensea-automatic-bulk-upload-and-sale#162]
hi 

the bot created a file for some fail upload or error called "upload_and_sale_858b6c1c.csv" .
i deleted some rows cos i've already upload it but it then show me this :
   NFT n°1/54:
   Your file is poorly structured for this NFT.
   Check that elements are present and in the right order.

i didnt touch any thing just deleted some rows and it looks exactly the same. 
i used numbers, csv table tool and even just text edit all for mac didnt work. 
do i need to convert it or change unicode ? or i cant edit the file?

thanks

**Comment by maximedrn** [comment]
Can you send me the generated file, please? I may have made a mistake somewhere, so the file cannot be interpreted properly.

**Comment by stackzwolle** [comment]
the generated file works but after i deleted some rows it dont work anymore

**Comment by maximedrn** [comment]
Send me the edited file

**Comment by stackzwolle** [comment]
[upload_and_sale_858b6c1c__.csv](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8191247/upload_and_sale_858b6c1c__.csv)

**Comment by maximedrn** [comment]
[upload_and_sale_858b6c1c__.csv](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8191249/upload_and_sale_858b6c1c__.csv)

It looks like macOS messed up when you opened the file to edit it. There were two " around each ;

**Comment by stackzwolle** [comment]
ok thanks :)
