### ISSUE TITLE
Unable to sell expired NFTs

### ISSUE THREAD

**Issue by atlookat** [maximedrn/opensea-automatic-bulk-upload-and-sale#163]
Hi Maxime,
I'm unable to sell expired NFTs on Polygon Blockchain; I'm using the sell only json file since my NFTs are already on OpenSea. Despite having more than 100 MATIC on my wallet, all NFT sells are cancelled.

**Screenshots and excerpts:**
[url=https://postimages.org/][img]https://i.postimg.cc/8PWqL7NH/2022-03-05-223158.jpg[/img][/url]

**Metadata.**
`{
     "nft": [
       {
         "nft_url": "https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/99995353970554757559721471534129028266698199001274859511402524949800648966145",
         "supply": 1,
         "blockchain": "Polygon",
         "sale_type": "",
         "price": 0.02,
         "method": "",
         "duration": ["1 months"],
         "specific_buyer": "",
         "quantity": ""
       },
       {
         "nft_url": "https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/99995353970554757559721471534129028266698199001274859511402524949800648966145",
         "supply": 1,
         "blockchain": "Polygon",
         "sale_type": "",
         "price": 0.02,
         "method": "",
         "duration": [
           "05-03-2022 22:00", "05-04-2022 22:00"
         ],
         "specific_buyer": "",
         "quantity": ""
       }
     ]
   }`

**NB. I changed the NFT URLs**

**System Information:**
 - Operating system: Windows 11 ( 64 bit).
 - Webdriver used:
   - ChromeDriver - Google Chrome.
- Python version used: Python 3.9.10.
 - Version of the bot used: v1.5.11.

**Additional context:**
Add here any other context about the problem.

**Comment by maximedrn** [comment]
The duration of the first NFT is wrong. It should be like the second one (1 month is not available as a choice on OpenSea).
The second NFT seems to be correct. Have you ever listed an NFT on Polygon on OpenSea? I know they added a new button to click once.
They may have made changes to the Polygon list and the bot may not work.

**Comment by atlookat** [comment]
Yes, I have a bunch of unsold NFT on Polygon on OpenSea of which I managed to list 5 manually. I changed the duration as advised but I'm still getting the sell cancelled. When monitoring the bot on OpenSea, I noticed that when it reaches the price field, it stays there for less than a second and moves to the next step without printing the price.

**Comment by Frankdev012** [comment]
Hello @atlookat  A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)

**Comment by maximedrn** [comment]
Hello, do you still have this problem with the new versions of the bot?

**Comment by atlookat** [comment]
Hello Maxime,
Thanks for your email, I really appreciate it. I still have problem with
the latest version (1.6.2) as shown in the attachment.  For some reason, it
gets stuck at last step when trying to sign to MetaMask to complete the
listing. Either I change the duration and quantity to "27-03-2022 16:55",
"27-04-2022 16:55"  or "27-03-2022 16:55", "27-08-2022 16:55" and
"quantity": "" or "quantity": 1 , respectively, I still get the same
result. Maybe I misspelled something in the metadata file. Below is a
sample of the excerpt from my metadata file.

[image: Log.jpg]



{
     "nft": [
       {
         "nft_url": "
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/99995353970554757559721471534129028266698199001274859511402524949800648966145
",
         "supply": 1,
         "blockchain": "Polygon",
         "sale_type": "",
         "price": 0.02,
         "method": "",
         "duration": [
           "27-03-2022 16:55", "27-08-2022 16:55"
         ],
         "specific_buyer": false,
         "quantity": ""
       },
       {
         "nft_url": "
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/99995353970554757559721471534129028266698199001274859511402524949800648966145
",
         "supply": 1,
         "blockchain": "Polygon",
         "sale_type": "",
         "price": 0.02,
         "method": "",
         "duration": [
           "27-03-2022 16:55", "27-08-2022 16:55"
         ],
         "specific_buyer": false,
         "quantity": ""
       }
     ]
   }

**Comment by maximedrn** [comment]
I tried it and it works.
Can you send me a video of what's going on? Maybe there is a step that needs to be done (new OpenSea update since 2/3 months: you need to confirm your wallet once).

**Comment by atlookat** [comment]
I already confirmed my wallet, and even managed to sell some manually.
Please find the video attached.

I'm using Dell Precision 7510
OS: Windows 11 Pro 64 Bit
Processor: Intel(R) Core i7
RAM: 32 Gb
GPU: NVIDIA Quadro M2000M

Python 3.9.10

Kind regards

*CUDA Verification*
[image: CUDA Verification.jpg]

*Video*
*https://drive.google.com/file/d/1MUpJ8SxnEitvZ_u3pXi0TXPLdBHvUGAw/view?usp=sharing
<https://drive.google.com/file/d/1MUpJ8SxnEitvZ_u3pXi0TXPLdBHvUGAw/view?usp=sharing>*

**Comment by maximedrn** [comment]
> https://drive.google.com/file/d/1MUpJ8SxnEitvZ_u3pXi0TXPLdBHvUGAw/view?usp=sharing

Can you change the way to access this video on Google Drive? I can't access it.

**Comment by atlookat** [comment]
https://mega.nz/file/XhlEADAK#qLmhDMc3uXGQj-XacEzVvI4BkKOSRgLdw7vzwmUNR_I

**Comment by maximedrn** [comment]
It cannot be greater than 6 months
