### ISSUE TITLE
Sale: Help with XLSX format wanted.

### ISSUE THREAD

**Issue by Dr-Shams** [maximedrn/opensea-automatic-bulk-upload-and-sale#164]
I managed To upload But all My sales Got Cancelled/Aborted
Messages Vary from " Reserve Price Must be Higher that 1 Weth "
Or Prices Must be Enteger ...

I Need To list the NFT as a Timed Auction For Three Days With minimum Bid Of 0.02 WETH for Example
![Timed Auction](https://user-images.githubusercontent.com/101027476/156905481-110923ad-98a4-47db-a6f4-ded8c3e0fdd1.jpg)

I Need Some Help To figure This Out

**Comment by maximedrn** [comment]
Hello, do you have a column with the urls of the NFTs?
Everything is good otherwise.

**Comment by maximedrn** [comment]
I close this issue for inactivity.
