### ISSUE TITLE
Sale of the NFT. NFT sale cancelled. 

### ISSUE THREAD

**Issue by elwanm** [maximedrn/opensea-automatic-bulk-upload-and-sale#165]
Sale of the NFT. NFT sale cancelled. Message: Cannot sign the MetaMask contract.

<img width="458" alt="2022-03-06 15_16_31-main py - Visual Studio Code" src="https://user-images.githubusercontent.com/98734893/156924846-0b2e6329-f7b8-4d3a-943d-ab6cc4cf54ac.png">

I am trying to list my uploaded item. I am using Ethereum not polygon. it tries twice then cancels the sale. is there a way to make the sign manually as am going to be already doing the captcha manually

**Comment by maximedrn** [comment]
Look at the new version of the bot. It seems that the new contract is now supported.
If not, you can continue on this issue: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/152
