### ISSUE TITLE
When i put my metamask wallet it gives an error and says that it must be an integer, the metamask wallet is that thing below the name in metamask? because im putting that and it doesn't work.

### ISSUE THREAD

**Issue by fern00-n** [maximedrn/opensea-automatic-bulk-upload-and-sale#166]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
A clear and concise description of what the bug is and, if possible, how and when it occurs.

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
If applicable, include screenshots to help explain your problem.

**System Information:**
 - Operating system: Windows (32 or 64 bit), MacOS or a Linux distribution.
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used.
 - Version of the bot used.

**Additional context:**
Add here any other context about the problem.

**Comment by maximedrn** [comment]
When you select the MetaMask wallet, enter the number that is in the list. This is the same thing for browser and file.

**Comment by fern00-n** [comment]
> When you select the MetaMask wallet, enter the number that is in the list. This is the same thing for browser and file.

I am so sorry, but how do i enter that list?

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug i

**Comment by maximedrn** [comment]
If you are stucked at the beginning of the bot, you just have to select what you want in the lists.
```
Choose a wallet:
1 - MetaMask
2 - ...
3 - ...
Choice: 1 <-- this is what you have to input.
```
Then you will have to input your recovery phrase and a password.

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by fern00-n** [comment]
> If you are stucked at the beginning of the bot, you just have to select what you want in the lists.
> 
> ```
> Choose a wallet:
> 1 - MetaMask
> 2 - ...
> 3 - ...
> Choice: 1 <-- this is what you have to input.
> ```
> 
> Then you will have to input your recovery phrase and a password.

THANK YOU SO MUCH, IT WORKED. If i make some gains i'll make sure to donate some to your wallet. :)
