### ISSUE TITLE
chrome is being controlled by automated test software

### ISSUE THREAD

**Issue by hongdohyun877** [maximedrn/opensea-automatic-bulk-upload-and-sale#168]
when started python main.py

chrome show me 
chrome is being controlled by automated test software

and opensea and metamask connecting is not working 

can u help??

**Comment by hongdohyun877** [comment]
here 
chrome is being controlled by automated test software
was not there but from today they showing me that and faild login opensea

i feel like they are checking automated test software and blocking

**Comment by hongdohyun877** [comment]
here
chrome is being controlled by automated test software
was not there but from today they showing me that and faild lo

https://user-images.githubusercontent.com/89174082/157076983-2f202ad3-0660-4bd8-88dc-17bf4fc36927.mp4

gin opensea

i feel like they are checking automated test software and blocking

**Comment by maximedrn** [comment]
It's the same problem here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167
I have to check this because it works fine on my end but I don't know why it happens for you.
