### ISSUE TITLE
I dont know why but the bot doesn't solve the captcha after it list it, it just keep showing that i have to solve it and after a while it just gives an error

### ISSUE THREAD

**Issue by fern00-n** [maximedrn/opensea-automatic-bulk-upload-and-sale#171]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
A clear and concise description of what the bug is and, if possible, how and when it occurs.

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
If applicable, include screenshots to help explain your problem.

**System Information:**
 - Operating system: Windows (32 or 64 bit), MacOS or a Linux distribution.
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used.
 - Version of the bot used.

**Additional context:**
Add here any other context about the problem.

**Comment by fern00-n** [comment]
![Uploading Bug.png…]()

**Comment by divyeshrajput17** [comment]
Please check the following issue thread.. We'e been trying all the possible ways to solve this. 
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/157

**Comment by maximedrn** [comment]
> Please check the following issue thread.. We'e been trying all the possible ways to solve this. #157

I close the issue because it is duplicated.
