### ISSUE TITLE
What am i suppose to insert in the file number section. :(

### ISSUE THREAD

**Issue by cryptokhaandaan** [maximedrn/opensea-automatic-bulk-upload-and-sale#173]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
A clear and concise description of what the bug is and, if possible, how and when it occurs.

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
If applicable, include screenshots to help explain your problem.

**System Information:**
 - Operating system: Windows (32 or 64 bit), MacOS or a Linux distribution.
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used.
 - Version of the bot used.

**Additional context:**
Add here any other context about the problem.

**Comment by cryptokhaandaan** [comment]
Choose your file:
0 - Browse a file on PC.
File number: 

this is what it asks

**Comment by cryptokhaandaan** [comment]
Choose your file:
0 - Browse a file on PC.
File number: 0
Browsing on your computer...
Traceback (most recent call last):
  File "/Users/zainab/Downloads/opensea-automatic-bulk-upload-and-sale-master/main-recaptcha.py", line 908, in <module>
    reader = Reader(data_file())  # Ask for a file and read it.
  File "/Users/zainab/Downloads/opensea-automatic-bulk-upload-and-sale-master/main-recaptcha.py", line 63, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "/Users/zainab/Downloads/opensea-automatic-bulk-upload-and-sale-master/main-recaptcha.py", line 71, in extract_json_file
    self.file = loads(open(self.path, encoding='utf-8').read())['nft']
KeyError: 'nft'

**Comment by cryptokhaandaan** [comment]
this is what it shows when i try to choose a json file (I'm supposed to choose the json file right? )

**Comment by maximedrn** [comment]
Your file is badly structured.
Look at how it should be in the assets folder of this repository on Github

**Comment by cryptokhaandaan** [comment]
alright i will fix that and should there be one file only for all the nfts

**Comment by maximedrn** [comment]
A single file contains all the details of all your NFTs.
