### ISSUE TITLE
Suggestion: Mass transfer to a hardware wallet.

### ISSUE THREAD

**Issue by tenumars** [maximedrn/opensea-automatic-bulk-upload-and-sale#174]
title explains it, is there a way to move all of them (transferring) to another account automatically? would hate to have to do it one by one because polygon doesn't support mass transfers (yet)

**Comment by tenumars** [comment]
not a bug for the record, just wondering if there is a way to move them using the same script?

**Comment by maximedrn** [comment]
There are no plans to add it soon. But I can add this feature on my to-do list :)
