### ISSUE TITLE
Issue while using the bot. Cannot sign the metamask contract.

### ISSUE THREAD

**Issue by jasarmig** [maximedrn/opensea-automatic-bulk-upload-and-sale#178]
Whenever I try to upload an item I get the Cannot sign the metamask contract error message. Item is created successfully but the sale doesn't work. It clicks the Sign button in opensea but when the metamask pop-up to sign comes on screen it won't click the sign button.

![image](https://user-images.githubusercontent.com/99051984/157455384-d91878b2-b88a-4096-a7e3-6fa552313343.png)

I'm uploading from an xlsx file, I don't know if that is relevant.

**System Information:**
 - Operating system: Windows 10 64 bit
 - Webdriver used:  ChromeDriver - Google Chrome.
- Python version used: 3.10.02
 - Version of the bot used: 1.5.12

**Additional context:**
From time to time the bot fails to log in to opensea and/or metamask.

**Comment by Utsppp** [comment]
I also have this problem in the sale section with bot,
Bot can not approve the contract and does not click on the sign metamastk for sale and goes to the next to build new NFT without any sale confirmation.

**Comment by maximedrn** [comment]
This error will be fixed in the next update.
I close this issue because it's duplicated (https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167)

> I also have this problem in the sale section with bot, Bot can not approve the contract and does not click on the sign metamastk for sale and goes to the next to build new NFT without any sale confirmation.

I've to fix Wyvern 2.3 contract signature.
