### ISSUE TITLE
Encountered error after selecting the .json file

### ISSUE THREAD

**Issue by mary1012** [maximedrn/opensea-automatic-bulk-upload-and-sale#180]
Thank you for the script!
I encountered the below error, please let me know what I am doing wrong. Thank you.

Describe the problem:
After I selected the metadata json file, the below appears.

**Traceback (most recent call last):
  File "C:\Users\indychow\downloads\0311\main.py", line 897, in <module>
    reader = Reader(data_file())  # Ask for a file and read it.
  File "C:\Users\indychow\downloads\0311\main.py", line 63, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "C:\Users\indychow\downloads\0311\main.py", line 69, in extract_json_file
    self.file = loads(open(self.path, encoding='utf-8').read())['nft']
  File "C:\Users\indychow\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\indychow\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\indychow\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 48 column 19 (char 1125)**

I am sure the structure of my metadata json file is same with the template.

**System Information:**
 - Operating system: Windows 32
 - Webdriver used:
   - ChromeDriver - Google Chrome : 98.0.4758.102 (32bit)
- Python version used: 3.10
 - Version of the bot used: 1.5.12

**Comment by maximedrn** [comment]
Line 48, something is expected. It found None (`"value": ,`)

**Comment by mary1012** [comment]
You mean line 48 in my metadata json file?

In line 48 it is : "duration": ["5 months"],
I have tried 
"duration": ["5 month"],
"duration": ["12-03-2022 12:00", "09-09-2022 12:00"],

All 3 doesn't work neither :(
What is missing? :(

**Comment by maximedrn** [comment]
Send me your file. I'll tell you what's wrong :)

**Comment by mary1012** [comment]
[_metadata.json.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8245793/_metadata.json.zip)

Thank you

**Comment by maximedrn** [comment]
[_metadata.json.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8246915/_metadata.json.zip)
You used MacOS quotation marks, that was the problem :)

**Comment by mary1012** [comment]
Thank you so much for spotting the error.
I corrected and the bot now can run.

However, another error appears.
I saw the OpenSea is successfully logged in, but the terminal keeps looping:

_Login to OpenSea. Login to OpenSea failed. Retrying.
Login to OpenSea. Login to OpenSea failed. Restarting.
Login to MetaMask. Login to MetaMask failed. Retrying.
Login to MetaMask._

I tried 3 more times, I found it stopped on this page, requesting Metamask signature. Then the above code appears in terminal again.

<img width="1370" alt="Screenshot 2022-03-14 at 22 24 33" src="https://user-images.githubusercontent.com/101434225/158294058-5eac988c-0d83-46a7-a696-bf97b4bd5deb.png">

Could you please help me to tackle this?
Thank you!!!!

**Comment by maximedrn** [comment]
I am working on this issue. I'll let you know how I'm doing on this issue: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167.
