### ISSUE TITLE
Putting my uploaded collection of sale.


### ISSUE THREAD

**Issue by abdurrehmanRasheed12** [maximedrn/opensea-automatic-bulk-upload-and-sale#182]
I have uploaded my collection some times ago using another script available on github.
Now I am trying to put all the collection on sale.
Can I do it using this script.?

**Comment by stackzwolle** [comment]
i don't think so. 
the script itself make records of all the nfts link uploaded to the site for selling later

**Comment by maximedrn** [comment]
Yes, you can do it. But you must put the URL of each NFT in a file. Follow the way the exclusive sales file should be structured.

At the moment, I haven't created a script to get all the URLs of a collection automatically. It's on my to-do list :)

**Comment by abdurrehmanRasheed12** [comment]
Where can I find the sale only file structure?
I'll let you know if I was able to find out a way to get the URL's.
Thanks.

**Comment by maximedrn** [comment]
In the `data/` folder of the repository. Choose the file format that you prefer (JSON/CSV/XLSX) for Sale Only
