### ISSUE TITLE
Signature of Polygon contract fails some times.

### ISSUE THREAD

**Issue by skillsofmatthew** [maximedrn/opensea-automatic-bulk-upload-and-sale#183]
I know that there was a thread about this already but I am having the same issue that the others were having on the Ethereum network but with polygon. Bot is able to do everything but the signing of the last contract. I have checked and have the most up to date versions of everything. Is there something that I need to change to fix it? Sorry if this was the wrong way to ask, very new to github. thanks! 

![image](https://user-images.githubusercontent.com/67701654/158295449-fbc2bcf8-103d-4f7b-bec6-e95d258de6ae.png)
   
windows 32 both drivers tested  
python 3.10 
bot Version 1.5.12 - March 06, 2022

**Comment by jasarmig** [comment]
This has been reported previously and is under revision to get fixed, for now, we just need to wait for a new version. Be patient.

**Comment by skillsofmatthew** [comment]
> This has been reported previously and is under revision to get fixed, for now, we just need to wait for a new version. Be patient.

Ok sounds good, I just started messing with it today but saw that the last thread had been closed so I figured I was doing something wrong! thanks for the response

**Comment by maximedrn** [comment]
Hello, I'm going to work on this. Can you send me an excerpt of your metadata file, I will work with it.

**Comment by skillsofmatthew** [comment]
At work atm but can send my files when I get home. I actually modified the bot and got it to work but no idea if it’s technically correct. Will include that as well.

**Comment by Sequento** [comment]
![1](https://user-images.githubusercontent.com/102164388/159539685-c320c186-3808-4ddd-b438-b5c3b3f4bf5c.jpg)
![2](https://user-images.githubusercontent.com/102164388/159539688-3acbac50-1cdc-4bae-b830-f166131c8215.jpg)

**Comment by skillsofmatthew** [comment]
Here is both the metadata is used and the updated main file that works on poly network. I've tested it about 10 times and it works most of the time only failing at signing open sea a few times. 
[files.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8329187/files.zip)

**Comment by maximedrn** [comment]
> Here is both the metadata is used and the updated main file that works on poly network. I've tested it about 10 times and it works most of the time only failing at signing open sea a few times. [files.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8329187/files.zip)

Okay, it works but sometimes it fails. I have to check this.
