### ISSUE TITLE
would like to buy your nft is u can solve this https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#185]
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167
 
 login opensea issue with chrome
 also, firefox doesnt seem to work but i'll settle with chrome coz login metamask failed with gecko while it works on chrome so far. no idea why

**Comment by maximedrn** [comment]
I'm working on it but I need to work on the reCAPTCHAs first.
