### ISSUE TITLE
possible to give us the section to add delay so we can at least upload and do the recaptcha manually first?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#186]
sry to mention this but can u pls mention where we shld add the delay coz i tried but doesnt work.
currently the pressing issue is still uploading first at least so we can do the captcha manually.

thx in advance, do mention where we shld add the delay code. i tried time.sleep(3) or something somewhere and it didnt work. so not sure where to add.

will buy your art (if not more than US$50) and give 1 nft of mine as token of appreciation

**Comment by hiqsociety** [comment]
before this, i cant login to opensea.
i can login to metamask, not opensea.
how do i delay it so that it can be clicked? "Signed" is not clicked.

**Comment by hiqsociety** [comment]
hi, sorry anxious for the "signed" in opensea click. Login to opensea failed.

possible to delay or remedy this first?

where shld i put the delay code or something? i need to login opensea only first.

**Comment by maximedrn** [comment]
I've updated the bot :)
Re-download the whole repository, install the modules (`pip install -r requirements.txt`).
**Use Python 3.9.X**.
By the way, I need feedback about login - I tried on my side and it works 100% of the time.
