### ISSUE TITLE
Can't sing in to Opensea (chrome). 

### ISSUE THREAD

**Issue by Laululytia** [maximedrn/opensea-automatic-bulk-upload-and-sale#187]
Bot starts to create first NFT, opens opensea, connects to Metamask with password & phrases and doesn't press last SIGN IN button. Then repeats same action. Any suggestions?

 - Operating system: Windows (64 bit)
 - ChromeDriver - Google Chrome.
 - Version of the bot used.

Problem:

Downloading the ChromeDriver. ChromeDriver downloaded:
C:\Users\Hp\.wdm\drivers\chromedriver\win32\99.0.4844.51\chromedriver.exe

NFT n°1/1800:
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Login to OpenSea failed. Retrying.
Login to OpenSea. Login to OpenSea failed. Restarting.

NFT n°1/1800:

**Comment by hiqsociety** [comment]
same issue here. where do i put the delay line? time.sleep(3)?

**Comment by abdurrehmanRasheed12** [comment]
Same here .
this issue is going on for sometime on person opened the issue 10 days back . nobody knows if they are working on the fix.
try some other scrips available on GitHub. I you want to upload your collection

**Comment by hiqsociety** [comment]
what alternative do u suggest?

**Comment by abdurrehmanRasheed12** [comment]
https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata
If you need to upload try this.

**Comment by hiqsociety** [comment]
i actually had the csv file done. and this one  i cant upload with specific pricing for individual items.

**Comment by maximedrn** [comment]
> https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata If you need to upload try this.

Wait for my update, this above is not complete.
I'm working on this issue but I have to build the reCAPTCHA solver first. It's almost finish.

**Comment by hiqsociety** [comment]
ok thx. really appreciate it. will buy your parrot nft as token of appreciation.

**Comment by Vural78** [comment]
> > https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata If you need to upload try this.
> 
> Wait for my update, this repository above is not complete. I'm working on this issue but I have to build the reCAPTCHA solver first. It's almost finished.

Hello,
This is great news.
When I finish uploading and selling my 10K NFTs, I will transfer some Ethereum to your ETH wallet as a thank you gift. In how many days can you release the update?
I'm really looking forward to it.

**Comment by maximedrn** [comment]
I hope to correct all the problems before Monday the 21st.

**Comment by Vural78** [comment]
> I hope to correct all the problems before Monday the 21st.

Thank you so much. I really want that day to come :)

**Comment by Laululytia** [comment]
> Same here . this issue is going on for sometime , some person opened the issue 10 days back . nobody knows if they are working on the fix. try some other scrips available on GitHub. I you want to upload your collection

I have tried like 5 different scripts, every each of them has an issue ;/

**Comment by abdurrehmanRasheed12** [comment]
Wait or some days . This the most complete script available. Owner already commented above that he is trying to overcome all the bugs before 21.

**Comment by hiqsociety** [comment]
hope to give nft to owner tml too. once i figure out how to upload in bulk

**Comment by Laululytia** [comment]
> hope to give nft to owner tml too. once i figure out how to upload in bulk

Yeah me too :)

**Comment by maximedrn** [comment]
I close this issue because it is duplicated (https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/167)

**Comment by abdurrehmanRasheed12** [comment]
Running the requirements command after downloading the new zip file.
It is giving error 
`Collecting basicsr==1.3.5
  Using cached basicsr-1.3.5.tar.gz (161 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Wizzy420\AppData\Local\Temp\pip-install-qpio9v9y\basicsr_aed93818cf9348738b982909931cdb7b\setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I'm using pyhton 3.10.3

**Comment by abdurrehmanRasheed12** [comment]
let me give it a try

**Comment by abdurrehmanRasheed12** [comment]
would you mind sharing the link to downlaod 3.9.X because I have been unable to find the right version.
Thanks
