### ISSUE TITLE
saw your update. hvnt tested. is it fixed?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#189]
saw your update. hvnt tested. is it fixed?

**Comment by stackzwolle** [comment]
all eyes on this one.  .i hope it really works  . . .

**Comment by hiqsociety** [comment]
does it work?

**Comment by stackzwolle** [comment]
> does it work?

still waiting also i havent try :)

**Comment by maximedrn** [comment]
I'll tell when it will be good :)
I've just uploaded required files for the reCAPTCHA solver (Yolov5 and Real ESRGAN).
I've to update the main.py and upload the recaptcha.py but I'm currently fixing some errors (OpenSea login) and improving the solver (crosswalk pre-trained file).

**Comment by Vural78** [comment]
> all eyes on this one. .i hope it really works . . .

I think Maximedrn will solve the problem. I am sure.

**Comment by maximedrn** [comment]
Update :)
Re-download the whole repository, install the modules (`pip install -r requirements.txt`).
**Use Python 3.9.X**.
