### ISSUE TITLE
"ModuleNotFoundError: No module named 'basicsr'"

### ISSUE THREAD

**Issue by Kisnobeats** [maximedrn/opensea-automatic-bulk-upload-and-sale#191]
Hi! Hope all is well! Excited to try the update, but kept getting this error down below. I have updated Python to the latest (3.10) just now before trying this update.

"C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master>pip install -r requirements.txt
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Collecting basicsr==1.3.5
  Using cached basicsr-1.3.5-py3-none-any.whl
Requirement already satisfied: colorama==0.4.4 in c:\python310\lib\site-packages (from -r requirements.txt (line 4)) (0.4.4)
Collecting numpy==1.20.3
  Using cached numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting opencv_python==4.5.5.62
  Using cached opencv_python-4.5.5.62-cp36-abi3-win_amd64.whl (35.4 MB)
Requirement already satisfied: pandas==1.3.5 in c:\python310\lib\site-packages (from -r requirements.txt (line 7)) (1.3.5)
Requirement already satisfied: pyclick==0.0.2 in c:\python310\lib\site-packages (from -r requirements.txt (line 8)) (0.0.2)
Requirement already satisfied: requests==2.27.1 in c:\python310\lib\site-packages (from -r requirements.txt (line 9)) (2.27.1)
Requirement already satisfied: selenium==4.1.3 in c:\python310\lib\site-packages (from -r requirements.txt (line 10)) (4.1.3)
ERROR: Could not find a version that satisfies the requirement torch==1.10.1 (from versions: 1.11.0)
ERROR: No matching distribution found for torch==1.10.1
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)"

Then I went ahead and at least tried the "main.py" to see what will happen, and this is what I get down below.

"C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master>python main.py
Traceback (most recent call last):
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\main.py", line 41, in <module>
    import recaptcha
  File "C:\Users\16179\Desktop\opensea-automatic-bulk-upload-and-sale-master\recaptcha.py", line 35, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
ModuleNotFoundError: No module named 'basicsr'"

Any help would be great! Thank you for all you do!

Best!

**Comment by maximedrn** [comment]
Downgrade your Python version to 3.9. I need to do some tests with version 3.9.10 to see if this module is needed.

**Comment by maximedrn** [comment]
I made some changes in the requirements.txt file.
I added a Requirements section: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#prerequisites, follow the instructions and it should work :) If you have other problems, send a message here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/190
