### ISSUE TITLE
can you provide the dockerfile for this? or a zipped version of everything in docker?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#192]
hi, i cant even download pytorch or pyclick etc without the download breaks halfway or something.
plenty error messages when i tried to download and get it to work with python3.9

a lot of things not working on ubuntu.

even windows cant get the download complete.

can u help make into dockerfile or a docker zip of everything?

thx. appreciate it.

**Comment by poc1127** [comment]
Hi Max 

I downloaded the zip. Unzipped it. Installed PyTorch using this command " pip install torch torchvision torchaudio " 
![image](https://user-images.githubusercontent.com/100990701/159473215-5f949c53-f60b-484a-a7ce-e385efae0b68.png)

What else am I missing? 

![image](https://user-images.githubusercontent.com/100990701/159472757-435f50b4-d862-40cd-a83e-e5a35c1a2de9.png)

**Comment by maximedrn** [comment]
I have updated the requirements file and released version 1.6.1.
It seems that the necessary modules are present and that there is no conflict.
