### ISSUE TITLE
Requirements file issue.

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#193]
Can't install onnx

![1](https://user-images.githubusercontent.com/102164388/159499016-d64f33b2-6fa1-4c07-83ac-03c99f971b2e.jpg)
![2](https://user-images.githubusercontent.com/102164388/159499025-c50343a8-6e9d-4b41-aa8d-87bc78df1668.jpg)

**System Information:**
 - Operating system: Windows 10 64b
 - Webdriver used:
   - GeckoDriver - Mozilla Firefox,
   - ChromeDriver - Google Chrome.
- Python version used - 3.10
 - Version of the bot used latest! 1.6.0

dont understand why he is dont install

**Comment by Las499** [comment]
Same. MacOS. Should I try pulling from the Onnx git?
<img width="1252" alt="Screen Shot 2022-03-22 at 23 13 45" src="https://user-images.githubusercontent.com/11033794/159501894-103226ad-f478-4a3e-b627-a7f5de490a6c.png">

**Comment by Las499** [comment]
> > Same. MacOS. Should I try pulling from the Onnx git? <img alt="Screen Shot 2022-03-22 at 23 13 45" width="1252" src="https://user-images.githubusercontent.com/11033794/159501894-103226ad-f478-4a3e-b627-a7f5de490a6c.png">
> 
> for thath u need to install cmake, use - pip install cmake

Thanks, but now,
<img width="680" alt="Screen Shot 2022-03-22 at 23 46 59" src="https://user-images.githubusercontent.com/11033794/159509310-aa0e5e8e-9db3-42ea-b082-95d53a126b91.png">

I tried pip install onnxruntime too, but I get the same message. Maybe a windows is better? Unfortunately my windows laptop is intel graphics and not very powerful...

**Comment by maximedrn** [comment]
It's the same for Windows. I'm trying to fix this.

**Comment by maximedrn** [comment]
I have updated the requirements file and released version 1.6.1.
It seems that the necessary modules are present and that there is no conflict.
