### ISSUE TITLE
when upload + sell, meta mask cant sign

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#195]
**Describe the problem:**
everything works fine, the captcha is almost defeated, but at the stage of the sale, the bot cannot sign the code for the sale of nft

**Screenshots and excerpts:**
![1](https://user-images.githubusercontent.com/102164388/159520068-63a4937a-ba5b-4334-bfd2-30049a3da189.jpg)

**System Information:**
 - Operating system: Windows 10 64bit.
 - Webdriver used:
   - ChromeDriver - Google Chrome.
- Python version used 3.9.9
 - Version of the bot used 1.6.0

**Comment by maximedrn** [comment]
Are you using Polygon?

**Comment by Sequento** [comment]
> Are you using Polygon?

yes, polygon blockchain

**Comment by maximedrn** [comment]
Have you already uploaded NFTs on Polygon?
Same error here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/183

**Comment by Sequento** [comment]
> Have you already uploaded NFTs on Polygon? Same error here: #183

yep, im uploaded nfts already, and want to continue to upload.
thx, i will check that

**Comment by Sequento** [comment]
NEW VERSION 1.6.1 work pefrectly!!! Solve captcha and put them to sale!!! AWESOME! u hero!!
But work only in google chrome, mozilla doesnt work.

**Comment by maximedrn** [comment]
Mozilla is too fast after the upload so the sale URL is invalid. I've to check that, it adds "?created=True" at the end when the NFT is uploaded

**Comment by Laululytia** [comment]
> NEW VERSION 1.6.1 work pefrectly!!! Solve captcha and put them to sale!!! AWESOME! u hero!!
> But work only in google chrome, mozilla doesnt work.

What about recaptcha solving time? For me as well everything works great, but it takes 5-6 min to create 1 NFT cause bot can not properly solve recaptcha

**Comment by Sequento** [comment]
> > NEW VERSION 1.6.1 work pefrectly!!! Solve captcha and put them to sale!!! AWESOME! u hero!!
> > But work only in google chrome, mozilla doesnt work.
> 
> What about recaptcha solving time? For me as well everything works great, but it takes 5-6 min to create 1 NFT cause bot can not properly solve recaptcha

for me is 30sec - 2min maximum, have a gtx 3080
