### ISSUE TITLE
Putting up my collection on sale issue?

### ISSUE THREAD

**Issue by abdurrehmanRasheed12** [maximedrn/opensea-automatic-bulk-upload-and-sale#199]
I have uploaded my collection of 2500 , and some of them have already been put up on sale 499, I need to put other 2001 up for sale , Do I need to remove the data from JSON file for those NFT that are already put up on sale..

**Comment by abdurrehmanRasheed12** [comment]
{'nft': [{'nft_url': 'my Collection URLS',
   'supply': 1,
   'blockchain': 'Ethereum',
   'sale_type': 'Fixed Price',
   'price': 0.014,
   'method': [],
   'duration': ['01-04-2022 00:00', '30-08-2022 23:59'],
   'specific_buyer': [False],
   'quantity': 1},
}
I have structured my JSON file this way is this correct?

**Comment by abdurrehmanRasheed12** [comment]
@maximedrn

**Comment by maximedrn** [comment]
>  Do I need to remove the data from JSON file for those NFT that are already put up on sale..

Yes

> I have structured my JSON file this way is this correct?

This is good:
```json
{
  "nft": [
    {
      "nft_url": "my Collection URLS",
      "supply": 1,
      "blockchain": "Ethereum",
      "sale_type": "Fixed Price",
      "price": 0.014,
      "method": [],
      "duration": ["01-04-2022 00:00", "30-08-2022 23:59"],
      "specific_buyer": [false],
      "quantity": 1
    }
  ]
}
```
"false" and not "False", it will not be considered as a boolean.

**Comment by abdurrehmanRasheed12** [comment]
In the sale part the code is not signing the last signature .. Can you please take a look at it.
