### ISSUE TITLE
stuck at solving the recaptcha

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#207]
Uploading NFT. Solving the reCAPTCHA.
it doesnt solve it automatically. i did install requirement and i have to manually pip install some modules too.

if i have solved it by hand, it still is stuck
i'm using Windows

can u tell me how to solve by hand and skip the recaptcha automation? i'm happy to solve by hand is ok

**Comment by maximedrn** [comment]
Use the `main-manual-resolution.py` file.
