### ISSUE TITLE
Setting secondary sale fee percentage?

### ISSUE THREAD

**Issue by schwaaweb** [maximedrn/opensea-automatic-bulk-upload-and-sale#209]
### Discussed in https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/discussions/208

<div type='discussions-op-text'>

<sup>Originally posted by **schwaaweb** March 25, 2022</sup>
Is there a way to set the secondary sale fee percentage in metadata?

https://docs.opensea.io/docs/10-setting-fees-on-secondary-sales</div>

**Comment by Joseph-Z** [comment]
This program is used to upload  items. The percentage of secondary sales should be set in collections

**Comment by schwaaweb** [comment]
Thank you!
