### ISSUE TITLE
Cannot login to OpenSea (main-manual-resolution.py)

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#210]
i tried to use manual but cant login.

the main.py cant recaptcha auto verify but now i cant login with opensea with manual.

can u just help with login with opensea and manually verify human captcha will do? appreciate this.

**Comment by trutheism** [comment]
can u pls help fix this asap? appreciate it. been waiting too long.

captcha verification challenge expired coz i dont hv cuda and using quite slow laptop. will try to get nvidia cuda and faster pc. 

pls help fix this manual thing first. thx

**Comment by maximedrn** [comment]
I have tried with ChromeDriver and GeckoDriver and it works fine.
Can you send me a video of what happens?

**Comment by hiqsociety** [comment]
i ran a second time and it works now. but because some NFTs are skipped, i tried to upload again and it starts from #1. 
1. how can i continue with the rest that didnt work?
2. how do i pause the operation and resume later? coz i am doing this manually but i did suspend using Windows Task Manager but cant resume thereafter.

**Comment by maximedrn** [comment]
1) A file is generated with all the NFTs that failed for upload or sale.
2) You can stop the script using CTRL + C, then you have to edit the metadata file to remove NFTs that are already uploaded

**Comment by Vural78** [comment]
> 1. A file is generated with all the NFTs that failed for upload or sale.
> 2. You can stop the script using CTRL + C, then you have to edit the metadata file to remove NFTs that are already uploaded

Instead of editing the metadata file, I think it would be more beneficial to store the NFTs loaded from the metadata file as names in a separate file and skip the previously loaded NFTs while reloading.
At least it's more useful than editing the metadata file.

**Comment by maximedrn** [comment]
> > 1. A file is generated with all the NFTs that failed for upload or sale.
> > 2. You can stop the script using CTRL + C, then you have to edit the metadata file to remove NFTs that are already uploaded
> 
> Instead of editing the metadata file, I think it would be more beneficial to store the NFTs loaded from the metadata file as names in a separate file and skip the previously loaded NFTs while reloading. At least it's more useful than editing the metadata file.

Adding logs takes time and will not be effective. I think it's faster to delete hundreds of lines than to create a massive script to read the logs and figure out what to take from a file.

**Comment by Vural78** [comment]
> > > 1. Yükleme veya satış için başarısız olan tüm NFT'lerle bir dosya oluşturulur.
> > > 2. Komut dosyasını CTRL + C kullanarak durdurabilirsiniz, ardından zaten yüklenmiş olan NFT'leri kaldırmak için meta veri dosyasını düzenlemeniz gerekir.
> > 
> > 
> > Metadata dosyasını düzenlemek yerine metadata dosyasından yüklenen NFT'leri ayrı bir dosyada isim olarak saklamak ve yeniden yüklerken daha önce yüklenen NFT'leri atlamak daha faydalı olur diye düşünüyorum. En azından meta veri dosyasını düzenlemekten daha kullanışlıdır.
> 
> Günlük eklemek zaman alır ve etkili olmaz. Günlükleri okumak ve bir dosyadan ne alınacağını bulmak için büyük bir komut dosyası oluşturmaktan yüzlerce satırı silmek daha hızlı olduğunu düşünüyorum.

you are the author. you know better. Not a problem for me. even better :)

**Comment by jetrotal** [comment]
Hello, sometimes the uploader skips selling a file and it does not give any error or fill error doc
