### ISSUE TITLE
its not an issue just want to share

### ISSUE THREAD

**Issue by stackzwolle** [maximedrn/opensea-automatic-bulk-upload-and-sale#213]
omg 
ive been patiently uploading nft then this how up 

<img width="512" alt="Screenshot 2022-03-28 at 1 04 41 AM" src="https://user-images.githubusercontent.com/97862299/160292419-5b41838c-a7d4-453b-946e-5488830f58a6.png">

wow even captcha i have to try later 
i just did 60 nft

**Comment by maximedrn** [comment]
1 week of intensive tests to solve the reCAPTCHAs with my bot and I was never blocked by Google :/ Yet it should not block the user when he tries to solve the image challenges; the audio solution is quickly limited.

Wait 5/10 hours and retry, you should be able to continue. I hope no proxies will be needed in future..
