### ISSUE TITLE
Solving CAPTCHA not working.

### ISSUE THREAD

**Issue by ektemfg** [maximedrn/opensea-automatic-bulk-upload-and-sale#214]
Hello. My bot works, but when listing it does nothing to solve the recaptcha. I really need help. I did install all requirements but nothing helps. It just does not do anything.
MacOS both with chrome and firefox.
Sincerely,
Dimitri.

**Comment by maximedrn** [comment]
I don't know if Mac computers can use Torch to resolve reCAPTCHAs with the CPU as quickly as a PC with a GTX or RTX.
What are your Mac's specs (CPU and RAM)?

**Comment by ektemfg** [comment]
Heyy!
I have tried both on MacBook (8GB RAM, i5 2.8Ghz, 512gb ssd, Intel gpu) and PC (GTX 1060 6GB, i5 3.8/4.3GHZ) but none work.

**Comment by hiqsociety** [comment]
@maximedrn can u pls provide the spec of ur pc / graphic card?
