### ISSUE TITLE
Tor Browser & 404 error webpages.

### ISSUE THREAD

**Issue by jadedtakesthiscereal** [maximedrn/opensea-automatic-bulk-upload-and-sale#218]
Is there possibly a way to run this on the Tor Browser https://www.torproject.org/download/  ?.. it runs on firefox guts, wallet connects fine etc.

small side question - currently using the 1.6.3 manual solve, the 2 attempts for a sale helps a ton as today almost every upload then goes to a 404 page for ~7 seconds then reopens the page and sells.. it helps greatly but would it be worth it speedwise to also try a delay of 4-5 seconds from when it posts to when it attempts to list?

**Comment by maximedrn** [comment]
> Is there possibly a way to run this on the Tor Browser https://www.torproject.org/download/ ?.. it runs on firefox guts, wallet connects fine etc.

The Tor browser is very similar to Mozilla Firefox, I can do something about that.

> small side question - currently using the 1.6.3 manual solve, the 2 attempts for a sale helps a ton as today almost every upload then goes to a 404 page for ~7 seconds then reopens the page and sells.. it helps greatly but would it be worth it speedwise to also try a delay of 4-5 seconds from when it posts to when it attempts to list?

I will add something that checks if the page failed to load.

**Comment by jadedtakesthiscereal** [comment]
Thanks sir.. am hoping the workings of tor browser with ‘new indentity’ abilities can get me past cloudflare protections faster when they do arrive
