### ISSUE TITLE
What graphic card are you using?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#220]
Can you tell us what graphic card u are using? coz i cant get my driver to be upgraded and i cant get python 3.7 with the torch u mentioned to work.

**Comment by hiqsociety** [comment]
will this work?
[ASUS GeForce GT 730, 2GB](https://computers.scorptec.com.au/search?p=R&srid=S1-3SYD-AWSP&lbc=scorptec&w=nvidia&url=https%3a%2f%2fwww.scorptec.com.au%2fproduct%2fgraphics-cards%2fnvidia%2f92016-gt730-sl-2gd5-brk&lgsku=GT730-SL-2GD5-BRK&rk=5&uid=399417851&sid=1&ts=custom&SLIPid=1648535573581&rsc=dHoCcZ5pe-eqz%3a5W&method=and&isort=price&view=details)
[ASUS GeForce GT 730 (Core: 902MHz), 2GB GDDR5 (5010MHz), PCI-E 2.0, HDMI 1.4a, DVI-D, VGA, Passive Cooling](https://computers.scorptec.com.au/search?p=R&srid=S1-3SYD-AWSP&lbc=scorptec&w=nvidia&url=https%3a%2f%2fwww.scorptec.com.au%2fproduct%2fgraphics-cards%2fnvidia%2f92016-gt730-sl-2gd5-brk&lgsku=GT730-SL-2GD5-BRK&rk=5&uid=399417851&sid=1&ts=custom&SLIPid=1648535573581&rsc=dHoCcZ5pe-eqz%3a5W&method=and&isort=price&view=details)
Warranty: 3 Year | Model: GT730-SL-2GD5-BRK

**Comment by Sequento** [comment]
GIGABYTE GeForce RTX 3080 Ti GAMING OC 12gb ~ 30 seconds to solve the reCaptcha
