### ISSUE TITLE
Recaptcha solved then upload fails.

### ISSUE THREAD

**Issue by artatt** [maximedrn/opensea-automatic-bulk-upload-and-sale#222]
Upload Fails - see attached screenshot.
[[Also, there is an issue with the requirement check, but I can't where. I also attached a screenshot of the error.]] 
I solved the second issue [[]] by placing the requirements doc in the yolov5 folder.

Metadata screenshot included also.

**System Information:**
 - Operating system: MacOS(12.3) GPU Intel Iris Pro 1536 MB
 - GeckoDriver - Mozilla Firefox
 - python 3.9.7
 - bot 1.6.3

<img width="678" alt="Screen Shot 2022-03-29 at 12 43 13 PM" src="https://user-images.githubusercontent.com/102592348/160595893-284c5b35-9b51-4405-b959-5f379a3fd31a.png">
<img width="567" alt="Screen Shot 2022-03-29 at 1 17 40 PM" src="https://user-images.githubusercontent.com/102592348/160600001-6a860567-9bff-453a-96c3-b612768650b8.png">
<img width="1271" alt="Screen Shot 2022-03-29 at 3 14 37 PM" src="https://user-images.githubusercontent.com/102592348/160619653-95280349-c521-498e-be34-3f42b16cef59.png">

**Comment by artatt** [comment]
So I tried running it in Chrome, and I think I've figured out the problem since I could see what was going on. It might be my graphics card that is not good enough. Notice in the screenshot it says solved in the terminal but the reCAPTCHA says it's expired. The image is also uploading to Opensea, you can see in the pic. Thoughts?




<img width="1337" alt="Screen Shot 2022-03-29 at 3 30 47 PM" src="https://user-images.githubusercontent.com/102592348/160623709-b3b47334-d54a-4dbd-ba0d-61c1a2d6b660.png">

**Comment by maximedrn** [comment]
The robot checks if the reCAPTCHA frame is closed -> it is solved.
But if your PC takes too long, it will say exactly the same thing :s (I've to change this so).
Can you tell me what your GPU and CPU are?

**Comment by artatt** [comment]
I see, well thank you for your help. Maybe I'll find someone who will let me use a more powerful comp lol....

Nice job btw with the code, keep it up you will go far!

**Comment by maximedrn** [comment]
Thanks :) I hope someone can give you a powerful computer ;)
