### ISSUE TITLE
What graphic cards specs do u recommend? GTX or RTX and how much memory?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#223]
What graphic cards specs do u recommend? GTX or RTX and how much memory?

which edition of windows are u using? windows 10 pro / home?

**Comment by maximedrn** [comment]
I use a PC with an RTX 3060, an i5 10300H and 16GB of RAM.
A minimum/acceptable should be a GTX 1080ti or RTX 2070.
Windows 11 but 10 Home/Pro do not change anything.
