### ISSUE TITLE
Error loading Yolov5 and RealESRGAN

### ISSUE THREAD

**Issue by EjazAhmad01** [maximedrn/opensea-automatic-bulk-upload-and-sale#224]
Everything goes right but when I select the json data file the following error appears.
![Screenshot 2022-03-29 200633](https://user-images.githubusercontent.com/102550825/160645493-3ac35d75-206d-461a-a732-dc6a29660208.png)

**Comment by jadedtakesthiscereal** [comment]
Have you installed git-scm.com to run git commands?

**Comment by EjazAhmad01** [comment]
installed git from git-scm.com and the error changed to:
![Screenshot 2022-03-29 211435](https://user-images.githubusercontent.com/102550825/160657952-f9b2898c-ef58-4365-8f46-073b8fe80706.png)

**Comment by maximedrn** [comment]
The file `yolov5/yolov5x6.pt` is corrupted/badly downloaded. Delete it and restart the robot or download the file here :
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/releases/download/Yolov5x6/yolov5x6.pt; then place it in the same directory.

**Comment by jadedtakesthiscereal** [comment]
Got me then, gonna need @maximedrn .. my next attempt would be trying the pip install -r requirements.txt command again as long as you have most recent build.  You might be at the edge of plausible gpu solving power.. so manual solver may be needed (main-manual-resolution.py)  sorry I was not able to help more

**Comment by maximedrn** [comment]
> Have you installed git from git-scm.com to run git commands?

Git is not necessary :)

**Comment by EjazAhmad01** [comment]
Ok I try it , and thanks for help.

**Comment by EjazAhmad01** [comment]
now it is working well untill the captcha. And stucks at the captcha, if I solve manually it says something went wrong

**Comment by maximedrn** [comment]
> now it is working well untill the captcha. And stucks at the captcha, if I solve manually it says something went wrong

Use the manual version if your PC is not powerful enough for reCAPTCHAs.

**Comment by EjazAhmad01** [comment]
I have 2captcha api key, can you please edit the code to use that automatically. Please🥺

**Comment by maximedrn** [comment]
> where can i find this directory? need to delete it

Delete the `.pt` files from `yolov5/` and `realesrgan/` directories. Then it will download the files.
You can find these pretrained files here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/releases
