### ISSUE TITLE
Chrome Browser fails to log in Opensea

### ISSUE THREAD

**Issue by jetrotal** [maximedrn/opensea-automatic-bulk-upload-and-sale#226]
When I set up a Chrome bot, the browser open 3 tabs instead of 2:
"New tab"
"Data;"
"MetaMask Login"

I guess that "Data;" tab breaks the bot everytime, 
it looks like the bot seeks 1 tab behind or after and gets confused.

On firefox it works, and does not open a "Data;" tab

**Comment by maximedrn** [comment]
The "New tab" should not be open. The "data;" is the default on Google Chrome.
