### ISSUE TITLE
cvs setting

### ISSUE THREAD

**Issue by Many2050** [maximedrn/opensea-automatic-bulk-upload-and-sale#230]
Greetings, tremendous script, do you have a way to generate the automatic upload and sell data file for 10 k ntf, thanks

**Comment by maximedrn** [comment]
Automatically, no, but faster, yes. You can use the functions of Excel, or Micosoft Visual Studio Code to modify several lines at the same time. Otherwise you can create a simple script to generate the file.

**Comment by Many2050** [comment]
thank you very much can you send me a link to youtube or a link of how to grab an example like thank you and forgive my ignorance

**Comment by maximedrn** [comment]
I think you know the basic features of Excel but I give you this link:
- [How To Automatically Fill Increment Cells In Excel?](https://www.extendoffice.com/documents/excel/3222-excel-increment-cell-value.html)

With Visual Studio Code (for CSV file) for multi-line editing:
- Windows: `Ctrl` + `Alt` + `↑` or `↓` .
- Mac: `⌥ Opt` + `⌘ Cmd` + `↑` or `↓`.
- Linux: `Shift` + `Alt `+ `↑` or `↓`.

**Comment by Many2050** [comment]
thank you master
