### ISSUE TITLE
Datasets for crosswalks, hills, chimneys, bridges and palm trees.

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#232]
very grateful for the work. will buy ur work after collection is completely uploaded.

possible to help make the crosswalks detected? coz it's usually the ones not getting through

**Comment by maximedrn** [comment]
First, I need to find a crossover dataset that is compatible with the Yolov5 structure. Then I will train the script with this dataset to create a `pt` file.

**Comment by kingchenc** [comment]
@maximedrn if i read this correctly: https://blog.roboflow.com/how-to-train-yolov5-on-a-custom-dataset/
for build a own dataset we just need images of the crosswalk, hills and so on?

**Comment by kingchenc** [comment]
Can we help you?

**Comment by hiqsociety** [comment]
how to upgrade to use chimney etc?

**Comment by maximedrn** [comment]
If you find Yolov5 compatible datasets for crosswalks, chimneys, bridges, palm trees, etc., please let me know. You can give me its link.
I will train a model and add it to the reCAPTCHA solver. There are about 2/3 lines of code to integrate, the most time consuming part is training the dataset: about 10 hours to create a good pre-trained file.

**Comment by BooBoi3** [comment]
> If you find Yolov5 compatible datasets for crosswalks, chimneys, bridges, palm trees, etc., please let me know. You can give me its link. I will train a model and add it to the reCAPTCHA solver. There are about 2/3 lines of code to integrate, the most time consuming part is training the dataset: about 10 hours to create a good pre-trained file.

Have you seen this: https://github.com/brian-the-dev/recaptcha-dataset

**Comment by maximedrn** [comment]
> > If you find Yolov5 compatible datasets for crosswalks, chimneys, bridges, palm trees, etc., please let me know. You can give me its link. I will train a model and add it to the reCAPTCHA solver. There are about 2/3 lines of code to integrate, the most time consuming part is training the dataset: about 10 hours to create a good pre-trained file.
> 
> Have you seen this: https://github.com/brian-the-dev/recaptcha-dataset

It seems perfect, thank you!

**Comment by hiqsociety** [comment]
is it completed already?
