### ISSUE TITLE
Single JSON file can't work both on "sales only" and "upload only"

### ISSUE THREAD

**Issue by jetrotal** [maximedrn/opensea-automatic-bulk-upload-and-sale#233]
I tried to adapt the same json file I used for upload, to sale, so I added "nft_url" and other stuff, like this:
```JSON
{
            "file_path": [
                "Z:/BlackBox Material/emojiSpin/079 ️ Left Speech Bubble Spin.mp4",
                "Z:/BlackBox Material/imgSpin/079 ️ Left Speech Bubble Spin.png"
            ],
            "nft_name": "🗨️ [ EmoGenie 🔄 #079 ]",
            "nft_url": "https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/71489843576005004931781390823643678329275045699036356511894602964011057152001",
            "external_link": "",
            "description": "A catchy animation of a speech balloon (repeating pattern. moving towards the camera). over a blue background.",
            "collection": "EmoGenies",
            "properties": "",
            "levels": "",
            "stats": "",
            "unlockable_content": "",
            "explicit_and_sensitive_content": "",
            "supply": 1,
            "blockchain": "Polygon",
            "sale_type": "",
            "price": 0.011,
            "method": "",
            "duration": "6 months",
            "specific_buyer": "",
            "quantity": 1
        }
```

The thing is, when I run an only sale command, the bot detects description as price, and gives me an error:

![image](https://user-images.githubusercontent.com/45118493/161373335-67d7d56f-0180-48f4-9a96-2dbda8e99724.png)

Is it attached by the order of the JSON entries, or by the name of the JSON entries?

**Comment by maximedrn** [comment]
The bot retrieves the details iteratively, not by key name. They must be in a specific order following the examples in the data file.
For upload only, you can use a "Upload and Sale" file, but for sale, you need to create a new file with the sale details + the URL of the NFT you want to sell.

**Comment by jetrotal** [comment]
oh boy, that was made to make the data file be compatible with different formats?

I guess I'll filter out my json...
