### ISSUE TITLE
Suggestion: add support for the 2Captcha API.

### ISSUE THREAD

**Issue by EjazAhmad01** [maximedrn/opensea-automatic-bulk-upload-and-sale#239]
Sir, I have a 2captcha api key purchased. Can you please make file which use the 2captcha api automatically.
https://2captcha.com/2captcha-api

**Comment by maximedrn** [comment]
I don't know how this works. I'll look into it later and give you the part of the code to add/change :)

**Comment by EjazAhmad01** [comment]
Ok thanks bro, waiting for your code❤️

**Comment by EjazAhmad01** [comment]
@maximedrn
Please have a look on it, it has all data but I don't know how to use it as I don't know programming.
See file 10 recaptcha v2
https://youtu.be/_jV5GgbRpXA

**Comment by EjazAhmad01** [comment]
this may help writing the api calls
https://github.com/2captcha/2captcha-python#installation

**Comment by EjazAhmad01** [comment]
@maximedrn
Sir plz plz help me. It's just a code of 10 lines only. If don't know how to integrate api, I have another solution. Please reply me if you want to do it.

**Comment by maximedrn** [comment]
> @maximedrn Sir plz plz help me. It's just a code of 10 lines only. If don't know how to integrate api, I have another solution. Please reply me if you want to do it.

I'll do it, let me a day. I'll need your help to test the script (since I don't have a 2Captcha API) before merging it with the robot update :)

**Comment by EjazAhmad01** [comment]
I cant provide you my key here. Please leave me a mail on ejazliaqat3@gmail.com

**Comment by maximedrn** [comment]
It's done, the update is published :)

**Comment by EjazAhmad01** [comment]
Thank you soooooo much brother. ❤️

**Comment by Vural78** [comment]
does it work smoothly? if so i can buy apikey too.

**Comment by maximedrn** [comment]
> does it work smoothly? if so i can buy apikey too.

I tried with the API key @EjazAhmad01 and it takes at most 1 minute to solve the reCAPTCHA.
It depends on the number of "solvers" available on the platform to solve your reCAPTCHA :)

**Comment by Vural78** [comment]
I will buy and try. at least it's better than manual uploading. I guess :)

**Comment by maximedrn** [comment]
> I will buy and try. at least it's better than manual uploading. I guess :)

Of course ahah :)

**Comment by EjazAhmad01** [comment]
I am trying it but it always says 404 web page error. What does it mean?

**Comment by EjazAhmad01** [comment]
i think you need to increase the time for solving the captcha.

**Comment by maximedrn** [comment]
> I am trying it but it always says 404 web page error. What does it mean?

Let me correct that, OpenSea works differently when the token is entered in the textarea.

**Comment by maximedrn** [comment]
Done, the bot had to call a JS callback function to send the token.

**Comment by Vural78** [comment]
Excellent!
It resolves and uploads successfully.

**Comment by EjazAhmad01** [comment]
Now its working good than before But still making the same issue sometimes.

**Comment by maximedrn** [comment]
> Now its working good than before But still making the same issue sometimes.

Check if the NFT is uploaded, it is possible that it is.
I need to make an improvement to make the robot detect the 404 page error.
