### ISSUE TITLE
An error occured while loading Yolov5 and RealESRGAN.....

### ISSUE THREAD

**Issue by plusmaxz** [maximedrn/opensea-automatic-bulk-upload-and-sale#241]
Downloading the ChromeDriver. ChromeDriver downloaded:
C:\Users\USER\.wdm\drivers\chromedriver\win32\99.0.4844.51\chromedriver.exe

An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is enough powerful,
every modules are installed and files presents in the directory.
No module named 'pyclick'

**Comment by maximedrn** [comment]
Do you have installed all the required modules ?
Follow the [instructions](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#configuration-of-the-bot) for these two files:  [`requirements_recaptcha.txt`](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/blob/master/requirements_recaptcha.txt) and [`requirements.txt`](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/blob/master/requirements.txt)
