### ISSUE TITLE
Suggestion: edit already uploaded NFTs.

### ISSUE THREAD

**Issue by kais1978** [maximedrn/opensea-automatic-bulk-upload-and-sale#244]
Hello, this is not an issue but rather a question. I uploaded my collection to opensea using the repository but with no metadata, is it possible to add the metadata file now? thx

**Comment by maximedrn** [comment]
This is an NFT editor, it's on my to-do list :)
I've to look at how this work and I'll do my best to release this soon.

**Comment by kais1978** [comment]
Thank you for your great efforts.
