### ISSUE TITLE
I uploaded NFT without recaptcha !!

### ISSUE THREAD

**Issue by Vural78** [maximedrn/opensea-automatic-bulk-upload-and-sale#250]
Hi,
I clicked on "I am not a robot" at the time of upload and the upload was successful without the images appearing. 6-7 consecutive NFT uploads have been successfully completed. Then came the pictures again. ( ~ 01:00 GMT+3 )
Bot version: 1.6.7

I wasn't taking a video recording so I can't prove it, but if it comes across again, I will add a video.
 
Is this related to Opensea or is it an enhancement to your bot?

**Comment by maximedrn** [comment]
Sometimes reCAPTCHAs do not display a challenge.
This is not a feature of my bot, but OpenSea may have changed the trust score of reCAPTCHAs.

**Comment by Vural78** [comment]
Thanks for information.
I hope reCAPTCHA is removed completely.
