### ISSUE TITLE
Sale of the NFT. NFT sale cancelled. Message: Something went wrong.

### ISSUE THREAD

**Issue by Kareemuhtaseb** [maximedrn/opensea-automatic-bulk-upload-and-sale#251]
![image](https://user-images.githubusercontent.com/98393627/162736563-a056dad1-aba0-484a-b22d-d4d66ffd806b.png)

![image](https://user-images.githubusercontent.com/98393627/162736757-c78bd191-3992-4468-8063-c16d70061ea0.png) 

Here is a screenshot of the error as well as the format of my xlsx files any idea of the reason behind this error?

**Comment by maximedrn** [comment]
Can you send me a video using the Chromedriver? I would like to know when it crashes.

**Comment by Kareemuhtaseb** [comment]
The problem was with the date format I used Months-Days instead of Days-Months..
Thank you
