### ISSUE TITLE
It doesn't try to upload again when it fails the first time.

### ISSUE THREAD

**Issue by jadedtakesthiscereal** [maximedrn/opensea-automatic-bulk-upload-and-sale#253]
Using upload and sell 1.6.9 with 2captcha.  Everything is going great and I can easily fix this later.. but I noticed when the 2captcha api fails and then tries again and successfully uploads.. that the bot skips sale and moves to next upload - see red circle where sale text should be
![99EAF81D-6FB8-454E-8498-8F7FAB9339C6](https://user-images.githubusercontent.com/102177219/163063468-f69839b7-292d-45ad-ba9e-1420c220c837.jpeg)

**Comment by maximedrn** [comment]
Version 1.6.10 should fix that :)

**Comment by jadedtakesthiscereal** [comment]
Excellent
