### ISSUE TITLE
404 error page after upload.

### ISSUE THREAD

**Issue by DefZee** [maximedrn/opensea-automatic-bulk-upload-and-sale#256]
Hi Maximedrn,

With the newer version of the script, I'm having the following issue:

The script starts fine, no errors whatsoever. However, on the upload screen, I constantly get a '404' page. This happens regardless of the options I select in running the script (manual, automated, 2recaptcha or otherwise, etc.). Refreshing the page doesn't go anywhere outside the 404 page, but clicking back/return page brings it to the upload section and the script then seems to work fine, up until the captchas. Neither of the automated captcha solvers then work (assuming because I have to manually return to the previous page), and the upload fails.

I have tried running both 'upload only' and 'upload and sale,' with the same result. The same with manual captcha solving.
What's interesting is if I run the previous versions of the script (pre April 2022), everything works perfectly fine (including using the same data files as JSON - maybe I made a formatting error here with the new version or missed something?). 
The script itself isn't giving me any error message in the cmd console, so I'm guessing it might be on Opensea's end. Using a VPN doesn't solve it - same issues persist. 

Hoping I've just made a mistake somewhere; using a previous version of the script for now (again, thank you so much for this!)

Running: 
Windows 10 x64
ChromeDriver
Python 3.9.9

**Comment by maximedrn** [comment]
Can you tell me if you are using version 1.6.9.3?
The versions 1.6.9 to 1.6.9.2 do not work.

**Comment by DefZee** [comment]
Nevermind, the latest version works well! Thanks!

The working version I was using was 1.6.4

The one that didn't work was 1.6.8 (I think?)
Either way, solved now, cheers!
