### ISSUE TITLE
Collection selection error

### ISSUE THREAD

**Issue by xerac318** [maximedrn/opensea-automatic-bulk-upload-and-sale#258]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
With the latest 1.6.10 version, collection selection is somehow different from the previous version.
**Bot doesn't choose collection properly.**

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
https://www.dropbox.com/s/62yi8pv17z6cac9/GIB_POLY-xlsx_structure_upload_and_sale.xlsx?dl=0

If applicable, include screenshots to help explain your [problem.]

**System Information:**
 - Operating system: Windows 64 bit
 - Webdriver used:
   - ChromeDriver - Google Chrome.
- Python version used. => v3
- 
 - Version of the bot used.
 - 1.6.10

**Additional context:**
Add here any other context about the problem.

**Comment by maximedrn** [comment]
Version 1.6.11 should fix that :)

**Comment by jadedtakesthiscereal** [comment]
I was about to make a post about this today too (haha woke up to over 400 nfts in untitled collection.. thankfully the edit change collection drop down works so no big deal to fix)  thank you for fixing it so fast.  .. randomly one sold, (5usd each) maybe untitled collection is a better collection name.

**Comment by jadedtakesthiscereal** [comment]
@maximedrn  hey just tried the new 1.6.11  it still loads me into untitled collection (same metadata that has been working fine til 1.6.10)

**Comment by maximedrn** [comment]
Version 1.6.11 fixes this problem. Sorry about that, I tried to implement a way to download a collection from its creation page URL, not from the default creation page.

**Comment by jadedtakesthiscereal** [comment]
Working again.  Everything posting where it should, 2captcha working normally.  Thanks again!    👍
