### ISSUE TITLE
Bot returns wrong address after 2captcha

### ISSUE THREAD

**Issue by xerac318** [maximedrn/opensea-automatic-bulk-upload-and-sale#259]
**Before opening the issue:**
- Read the README file.
- Read the pinned and opened issues, look at the sample metadata files.
- Make sure you have the required version of the modules and the latest version of the browser and the bot installed.

**Describe the problem:**
With version 1.6.10, after recaptcha solved with 2captcha service,
bot says "reCAPTCHA solved", but it items cannot be found in collection.
and it seems like it returns worng address.
Returned address looks like this
~~opensea.io/DETAILED%20INFO%20IN%20MY%20EXCEL%20FILE

**Screenshots and excerpts:**
Upload the metadata file or send an excerpt from it.
https://www.dropbox.com/s/62yi8pv17z6cac9/GIB_POLY-xlsx_structure_upload_and_sale.xlsx?dl=0

If applicable, include screenshots to help explain your problem.

**System Information:**
 - Operating system: Windows 64 bit
 - Webdriver used:
   - ChromeDriver - Google Chrome.
- Python version used. ==> v3
 - Version of the bot used. ==> 1.6.10

**Additional context:**
Add here any other context about the problem.

**Comment by maximedrn** [comment]
Version 1.6.11 should fix that :)
