### ISSUE TITLE
Sometimes OpenSea displays a 404 page error.

### ISSUE THREAD

**Issue by acejou27** [maximedrn/opensea-automatic-bulk-upload-and-sale#260]
Hello
I use automatic upload and sales with the latest version, but when I reach the page for creating an item, I will suddenly jump to 404. What should I do?

There are references to other people using the old version, but it will let me log in and can't pass

please help me thanks

**Comment by maximedrn** [comment]
If you are using the 2Captcha solver, this error comes from a callback function that has changed.
If not, can you please detail this error?

**Comment by acejou27** [comment]
I use m1 mac. In terms of verification, I choose manual verification, and vscode runs. I don't know if this information is enough. Thank you again.

**Comment by maximedrn** [comment]
Have you tried with the latest bot update (1.6.11)? I don't get this error, despite the fact that the 404 error page is frequent on OpenSea without reason.

**Comment by maximedrn** [comment]
The error is from OpenSea, I didn't get it today so it should work.

**Comment by acejou27** [comment]
My nft was made using the script provided by MythicNftClub in this question
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/150#

Not sure if this will make a difference, maybe there is a formatting error?

**Comment by maximedrn** [comment]
> My nft was made using the script provided by MythicNftClub in this question #150
> 
> Not sure if this will make a difference, maybe there is a formatting error?

It is from OpenSea, sometimes it says to the page can not be found while the url is good and when refreshing the page everything is displayed correctly.
