### ISSUE TITLE
OpenSea asks to switch from Ethereum to Polygon and vice versa.

### ISSUE THREAD

**Issue by jadedtakesthiscereal** [maximedrn/opensea-automatic-bulk-upload-and-sale#262]
Midway through the afternoon today my uploads worked fine but my listing began to fail. I am loading onto polygon chain and now as stated uploads fine but at sale wants me to swap metamask to polygon mainnet (which is on my normal metamask but not in the bot browser)…

tried “beating the clock” by typing the net details in manually but I miss it by probably 10 seconds before the bot closes browser to retry.

Just started this afternoon, so my guess is change at opensea or metamask? Only thing I have done different today is since I made a small sale last night my phone metamask was on polygon mainnet as I went through to manually fix ones that dropped to untitled collection.

Now my phone also wants me on polygon mainnet to list, I do not recall having to swap from ethereum net before for listing which is why I think they changed listing ‘rules’.

**Comment by jadedtakesthiscereal** [comment]
![4B3FDE3D-9143-4176-A33C-8CAC544FACF2](https://user-images.githubusercontent.com/102177219/163490254-63f3cb87-f3a9-44dc-bac5-32f302b21a21.png)

**Comment by jadedtakesthiscereal** [comment]
Using 1.6.11

**Comment by maximedrn** [comment]
I added support for this feature on version 1.6.12, I need feedback.
It seems to work, it switches from Ethereum to Polygon, Polygon to Ethereum but I don't know if it works for a long time (some errors may appear) and I haven't tried it with Coinbase Wallet.

**Comment by jadedtakesthiscereal** [comment]
Currently using 1.6.12 (2captcha).. metamask

the blockchain switch is working great.

only fail I had so far was on sale of item 1 when it first ‘blockchain switched’

working fine currently loading and listing.

will let this run a bit then try to test a coinbase wallet collection for you

**Comment by maximedrn** [comment]
> only fail I had so far was on sale of item 1 when it first ‘blockchain switched’
This happens when it switches to Polygon. Normally, it puts the NFT up for sale the "second" time because this manipulation is voluntary.

**Comment by jadedtakesthiscereal** [comment]
Tested with metamask, 2captcha

156/156 uploaded 

155/156 listed (very first one errored then throughout 8/156 had to try twice and all 8 listed at attempt 2

.. verdict success

Attempted test with coinbase wallet

My bot logged in and hit a click wall it would not go past.  See pic1

Manually clicking it goes to this next sign button.  See pic 2

Waiting again does nothing and manually clicking sign starts to spin then bot immediately closes to restart

Verdict.. stuck at login issues with opensea (coinbase logged in just fine)


****Ps.. using both wallets in same folder with saved passcodes (private key.txt and recoveryphrase.txt) it tried to use my metamask - recoveryphrase.txt for coinbase.

See pic 3,  it asks for metamask credentials too 

(I deleted previous saved passcodes and used my coinbase stuff where it said metamask and it began to work)
Pic1
![6A7F13B3-4F90-47E8-AC3A-4A041472CB19](https://user-images.githubusercontent.com/102177219/163624020-665f71a3-bc6e-474c-8cab-236472eda72a.jpeg)
Pic2 
![0253C0D5-B2D7-4904-B51A-E590E010DE25](https://user-images.githubusercontent.com/102177219/163624137-7c73547b-d94c-4feb-8707-41fc067670f7.jpeg)
Pic3 
![AF868E32-1FB2-4C84-95A3-DE84FB9A7EFD](https://user-images.githubusercontent.com/102177219/163624210-7feeb769-8b89-461f-a3f9-ab72964a5a57.jpeg)

**Comment by maximedrn** [comment]
Hello, a new version fixes this failure problem after the blockchain change.

**Comment by jadedtakesthiscereal** [comment]
New 1.6.13 working great 
![207887BA-AB81-41F4-BF00-F8EF26B6BE06](https://user-images.githubusercontent.com/102177219/163688786-57f441a8-2a86-4006-bf04-a113bef8fee9.jpeg)
In longer test on 1.6.12 metamask 2captcha, posted 550 in last run and all were posting and listing till around 500/550.. the remaining 50 posted but failed at list because the sign window opened to a blank error each time.  Restart program everything listed as usual.  I think window error on opensea or metamask end so my opinion metamask version using 2captcha is great..   let me know if i need to try coinbase wallet again.. see long post above for why I have not tested further 👍

**Comment by maximedrn** [comment]
I will fix the blockchain change for Coinbase Wallet.
