### ISSUE TITLE
An error occured while loading Yolov5 and RealESRGAN.

### ISSUE THREAD

**Issue by denomparkour** [maximedrn/opensea-automatic-bulk-upload-and-sale#263]
An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is enough powerful,
every modules are installed and files are correctly
downloaded and presents in the directory.
list index out of range

Im getting this error after pulling last update in this repo

I tried re downloading the whole repo too..but same issue. And in previous versions it was working fine.

Thanks in Advance.

**Comment by denomparkour** [comment]
Also, 'https://opensea.io/collection/pixelated_hooman/assets/create?enable_supply=true' this link in new version is throwing 404 whereas in previous version the link was 'https://opensea.io/asset/create?enable_supply=true' and it was working fine.

**Comment by davecotefilm** [comment]
Same error

**Comment by maximedrn** [comment]
I fixed this issue for reCaptha, I'm sorry. I have tested crosswalks datasets and forgot to remove a line in the file.

**Comment by maximedrn** [comment]
@denomparkour, can you tell me the name of your collection and its url?

**Comment by denomparkour** [comment]
> @denomparkour, can you tell me the name of your collection and its url?

sure, 
https://opensea.io/collection/pixelated-hooman

**Comment by denomparkour** [comment]
> I fixed this issue for reCaptha, I'm sorry. I have tested crosswalks datasets and forgot to remove a line in the file.

No problem. Thankyou :D

**Comment by maximedrn** [comment]
I have to change something in the bot so.
Use pixelated-hooman instead of pixelated_hooman. It should work

**Comment by denomparkour** [comment]
> I have to change something in the bot so. Use pixelated-hooman instead of pixelated_hooman. It should work

ok I will try and let you know
