### ISSUE TITLE
CUDA and manual solving problems.

### ISSUE THREAD

**Issue by davecotefilm** [maximedrn/opensea-automatic-bulk-upload-and-sale#264]
Yes so I had a previous version working up to the captcha, but now after reinstall of requirements.txt and captcha txt i get the crash saying torch vision or something isn't named right. So I checked to see if python recognized cuda, it doesn't. I've tried updating to cuda 11.6 but my system says 10.1 still, though the programfiles/nvidia folder shows 11.6
But in python>>>torch.cuda.is_available() returns False
And now when I try with manual captcha it won't even start creating items WTF THIS IS A MESS A GODDAMN MESS!
HELP!

**Comment by maximedrn** [comment]
What is your computer's graphic card?

**Comment by davecotefilm** [comment]
gtx 760 M

**Comment by davecotefilm** [comment]
But now the manual option won't work either! Did my requirements packages get all screwed up now?? Windows 10

**Comment by maximedrn** [comment]
> gtx 760 M

I'm sorry you cannot use the reCAPTCHA solver with CUDA. What happened with the manual solution?

**Comment by davecotefilm** [comment]
Chrome opens browser, logs in to metamask and api. Then stops. I'm heading to bed my kids will be up soon :(

**Comment by davecotefilm** [comment]
I thought cuda was what allowed recaptcha solver?
________________________________

**Comment by maximedrn** [comment]
What error is displayed?

**Comment by davecotefilm** [comment]
I'll check tomorrow and get back to you

**Comment by davecotefilm** [comment]
When I run with headless, 2 for yolov5..:
An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is enough powerful,
every modules are installed and files are correctly 
downloaded and presents in the directory.
No module named 'torchvision.transforms.functional'; 'torchvision.transforms' is not a package

**Comment by davecotefilm** [comment]
Then with manual solver CHROME: logs into metamask wrong account (account 2 which has no funds), I quickly switch, but it continually fails. 
Then with manual solver GEKO it logs in, uploads nft and terminal says "reCAPTCHA displayed", and that's it. so.. how can I solve this reCAPTCHA that's displayed?  Useless option if there's no way to SEE the recaptcha..!!

**Comment by maximedrn** [comment]
> Then with manual solver CHROME: logs into metamask wrong account (account 2 which has no funds), I quickly switch, but it continually fails. Then with manual solver GEKO it logs in, uploads nft and terminal says "reCAPTCHA displayed", and that's it. so.. how can I solve this reCAPTCHA that's displayed? Useless option if there's no way to SEE the recaptcha..!!

I uploaded a version that fixes these little issues about the manual solver.

> When I run with headless, 2 for yolov5..: An error occured while loading Yolov5 and RealESRGAN. Please verify that your computer is enough powerful, every modules are installed and files are correctly downloaded and presents in the directory. No module named 'torchvision.transforms.functional'; 'torchvision.transforms' is not a package

I don't know. It looks like Torchvision is installed but Python doesn't detect a file as part of the module. Maybe a `__init__` file is missing somewhere. However, I remind you that your computer does not support this solver because your graphics card does not support CUDA.

**Comment by davecotefilm** [comment]
My graphics card does support cuda, its on 10.1 but python doesn't see it.
________________________________

**Comment by Vural78** [comment]
> gtx 760 M

Your graphics card has CUDA version 3.0. Therefore, you have an insufficient video card in terms of power.

Source: https://www.techpowerup.com/gpu-specs/geforce-gtx-760m.c2305

**Comment by davecotefilm** [comment]
Thanks
________________________________

**Comment by davecotefilm** [comment]
As for the geckodriver and manual captcha, I commented out headless and so it's fine now. Will take a long time to upload so next time I'm just using a dApp and smart contract, hopefully by then gas is cheap due to the merge.
________________________________
