### ISSUE TITLE
I bought your url scraper but i actually want the number scraper. 

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#265]
I bought your url scraper but i actually want the number (id) scraper because the upload is missing a lot of uploads (captcha success rate at around 60% only) so i need to scrape for the missing ones so i can reupload them.

do u know how to scrape for what is already uploaded? can u make one? i can pay for it.
i named my nft as #[number]
so i just need to scrape for the #[number] part or just the name/title of the nft will do.

can u get it done? i will pay for this title/name scrape tool

**Comment by jadedtakesthiscereal** [comment]
This was mentioned in a now closed post from a week or so ago.  Maxime said he would be adding the item name into what the scraper pulls.  So it’s on the way.  I’m also waiting patiently for that update.  😀

**Comment by hiqsociety** [comment]
0. name / title scrape.
1, i have tons of duplicates. if i can remove them as well
2. also some are missing sale pricing. if that can be added too

thx in advance

**Comment by maximedrn** [comment]
I just uploaded the new version on Gumroad, can you tell me if you have access or not?
I will send an email to all users if not.

**Comment by hiqsociety** [comment]
is it just 1 file scraper.py?

**Comment by maximedrn** [comment]
I updated `scraper.py` but I don't know if you still get an access to the download page from your account.

**Comment by jadedtakesthiscereal** [comment]
Yes you do get access to download once signed into gumroad.  

Yes it makes great json files with item names

![4E3D4DF4-A79D-4497-9504-AA6A73D35C80](https://user-images.githubusercontent.com/102177219/163627644-6190234d-616b-42d6-9c32-81d769beb618.jpeg)

the csv file I do not see item name but json works better for me anyway
![image](https://user-images.githubusercontent.com/102177219/163627848-9b93c08a-e8c4-4e31-906c-f5c4b642c46b.jpg)

**Comment by jadedtakesthiscereal** [comment]
.. slightly confused on the duplicate and full.

Duplicate list has # on it  but that # only shows 1 time when I search opensea

the # shows 3 times on the full list

the # shows 2 times in unique list

all times it appears it has same exact url, so no going through and deleting by url.

**Comment by maximedrn** [comment]
> .. slightly confused on the duplicate and full.
> 
> Duplicate list has # on it but that # only shows 1 time when I search opensea
> 
> the # shows 3 times on the full list
> 
> the # shows 2 times in unique list
> 
> all times it appears it has same exact url, so no going through and deleting by url.

I have to change something for duplicates, it only checks if there is one duplicate, not if there are two.

**Comment by jadedtakesthiscereal** [comment]
@maximedrn i just downloaded the newest version of scraper from gumroad email..  i get this now, and in the files i see the original program had a modules folder this new one does not (not sure if it makes it after running)  but at run I get this  (win10 64 bit) 
![D4422A90-1CF7-4A54-A6CD-C16B8F28BAFF](https://user-images.githubusercontent.com/102177219/163722509-4a6da3de-a33e-40de-982e-e550dfda60df.jpeg)

**Comment by maximedrn** [comment]
You need to install the JS packages.
Type `npm install`.
If minimist is not found, type `npm install minimist`.

**Comment by jadedtakesthiscereal** [comment]
> You need to install the JS packages.
> Type `npm install`.
> If minimist is not found, type `npm install minimist`.

Oh man duh..   working again, have not checked file details yet

**Comment by jadedtakesthiscereal** [comment]
Not sure what the something wrong was 
![62D78251-C5A5-4C90-9EE4-07BD240D09B4](https://user-images.githubusercontent.com/102177219/163724354-6fd5c7e0-0d46-4e67-9594-a42b13d8281d.jpeg)

**Comment by maximedrn** [comment]
I made a mistake with the remove() method of Python. I added a parameter that shouldn't be there.
I'm doing some tests to make sure everything works before releasing version 1.2.1.

**Comment by maximedrn** [comment]
I have released version 1.2.1. It fixes this problem and others mentioned in this issue: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/267
I close this issue to centralize the issues/feedbacks regarding the collection scraper. Please continue on issue #267 (link above).
