### ISSUE TITLE
Suggestion: Massive removal of NFTs.

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#266]
can u improve the scraper to also remove the duplicates?

the duplicates are caused by mutliple uploads coz of crashed / hanged instances, restarted and accidentally uploaded the same nft twice / 3 times sometimes.

can u help?

**Comment by maximedrn** [comment]
A bot to remove NFTs is on my to-do list. I don't know if there is a bot on Github for this.
For now, you have to do it manually.

**Comment by hiqsociety** [comment]
1. when's the estimated time of completion for this?
2. how to use the current scraper to check for missing items and to upload them again?
