### ISSUE TITLE
Feedback about the Collection Scraper.

### ISSUE THREAD

**Issue by xerac318** [maximedrn/opensea-automatic-bulk-upload-and-sale#267]
I ran a new scraper came out a few hours ago to check the duplicates,
but at the end of process the bot says "went something wrong", and I got only full xlsx file.
It's ok to have a 'full file only' cuz I can sort them manually, but bunch of items are missing in xlsx file.

For example, 
#0034 is in the collection => https://opensea.io/collection/musicgirl
But not in the excel file.
[full_c3f0cc65.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8501947/full_c3f0cc65.xlsx)

And it shows a lot of identical items multiple times.
See the img below.

![image](https://user-images.githubusercontent.com/103630790/163722620-8f05e44a-5027-4739-acb1-c84051fc932b.png)

For example, excel file show twice this item.

Girls In The Music #0001 - Distressful Chost
https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/42170858478275813962070746363593109487206097538066082763351105591225863897089

**Comment by maximedrn** [comment]
Can you tell me what error you get after the "Something went wrong" message?
I will fix this problem of the same duplicated NFT in the "complete" file.

In the "complete" file, all NFTs are listed.
In the "unique" file, the NFTs are listed once (based on the name).
The others are in the "duplicate" file, and the missing ones (based on the number) in the "missing" file.

Obviously, I tried it with my collection but I can't be sure that it works for all collections and in all cases.

**Comment by maximedrn** [comment]
I have released version 1.2.1. It fixes these problems. Make sure you use the new `opensea.js` file.
The only problem is that 1 NFT is still missing (#1000 for your collection and #315 for mine).
I need to check and fix this little problem.

**Comment by xerac318** [comment]
I tried with a new version of scrapers, and got same issue.

![image](https://user-images.githubusercontent.com/103630790/163997629-e2540d4a-8da5-472b-a93f-4ee3befb5b97.png)

Here is the result of python script.


[full_0dc5e0df.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8512705/full_0dc5e0df.xlsx)

And this is the xlsx file of result.

I don't know which is which, but when I run check the "find duplicates and remove" function, 
it says it removed 88 items.

I tried to scrape this collection this time.

https://opensea.io/collection/musicgirlpolygon

Issues,
#1. It scrapes identical items
#2. It doesn't scrape all items in the collection
#3. It only gives me a "full" file. (What I was trying to find was missing items this time)
#4. I just download 1.6.14 and ovewrite the scraper tool folder with what I downloaded from gumroad.com

**Comment by maximedrn** [comment]
> 1. It scrapes identical items
> 2. It doesn't scrape all items in the collection
> 3. It only gives me a "full" file. (What I was trying to find was missing items this time)
> 4. I just download 1.6.14 and ovewrite the scraper tool folder with what I downloaded from gumroad.com
> 5. I don't understand what you mean. ==> "Make sure you use the new opensea.js file."
>    Should I run like "python opensea.js" ?

Thanks for taking the time to clarify your mistakes, it helps me a lot :) Can you tell me the version of the bot you are using. I published, a few hours after the version 1.2.0, the version 1.2.1 which corrects the error present on the image.
How to check the version of the tool? Look at the green text when you launch the robot.

1) Version 1.2.1 should fix this problem, I tried with your collection as a test to be sure and it scrapes all NFTs except one (this comes from the way JS files work).
2) Version 1.2.1 forgets an NFT, I will try to fix this little problem.
3) Caused by the `remove()` error fixed.
4) Ok, but I advise to separate the bot and tool folders.
5) This means you have to replace the old `opensea.js` file with the new one, but I advise to replace the whole tool folder with the new version.

**Comment by xerac318** [comment]
![image](https://user-images.githubusercontent.com/103630790/164033657-0f5fafb9-2666-474f-a798-1181e02e1900.png)

It says it's 1.2.0

I don't know where to download 1.2.1.

I've downloaded bot from, 

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/tree/master/extension-tools/collection-scraper

here and,

![image](https://user-images.githubusercontent.com/103630790/164034017-ee462709-4e11-432e-8981-a1a5d111a16f.png)

here.

I put everything from the second link's contents to the first link contents.

**Comment by maximedrn** [comment]
> It says it's 1.2.0
> I don't know where to download 1.2.1.

The first email you received from Gumroad when you purchased the tool contains a link to download the tool and its updates.
If you can't find this tool, I will send you a receipt email again if you tell me the beginning of your email (before the @)

**Comment by xerac318** [comment]
it is 
xerac

!!!

**Comment by xerac318** [comment]
Thank you, I got your email, and it works like a charm =) (at least on this collection)
just except one NFT is missing as you already mentioned.
in this case, 
total NFT in this collection is 995, but I got 994 items in the FULL list.

[full_5a74419e.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8514297/full_5a74419e.xlsx)
[missing_bb33a48c.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8514298/missing_bb33a48c.xlsx)
[unique_a97e0fa5.xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8514299/unique_a97e0fa5.xlsx)

I have 7 more collections to check, so I will let you know if I find something else.

**Comment by xerac318** [comment]
I found an error.

In the "missing" file, 
it says 0431 is missing, but it's not.

https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/42170858478275813962070746363593109487206097538066082763351107826533003165697

**Comment by Vural78** [comment]
Hi Maxime,

I used the Collection Scraper. But even though I have all the items in my collection, the scraper tells me that items #44 to #101 are not in the collection.

Collection name: portraitvagrants
Bot version: 1.2.1

[![image](https://www.linkpicture.com/q/scraper1.png)](https://www.linkpicture.com/view.php?img=LPic626281c90f5271100046163)
[![image](https://www.linkpicture.com/q/scraper2.png)](https://www.linkpicture.com/view.php?img=LPic626281c90f5271100046163)
[![image](https://www.linkpicture.com/q/scraper3.png)](https://www.linkpicture.com/view.php?img=LPic626281c90f5271100046163)

**Comment by maximedrn** [comment]
> Hi Maxime,
> 
> I used the Collection Scraper. But even though I have all the items in my collection, the scraper tells me that items #44 to #101 are not in the collection.
> 
> Collection name: portraitvagrants Bot version: 1.2.1

I am working on version 1.3.0. It fixes this problem for collections from 0 to 10000 NFTs. I am looking for a solution for collections of 10k+ NFTs.

**Comment by Vural78** [comment]
> > Hi Maxime,
> > I used the Collection Scraper. But even though I have all the items in my collection, the scraper tells me that items #44 to #101 are not in the collection.
> > Collection name: portraitvagrants Bot version: 1.2.1
> 
> I am working on version 1.3.0. It fixes this problem for collections from 0 to 10000 NFTs. I am looking for a solution for collections of 10k+ NFTs.

You can use my collection to improve your bot. There are 10000 items in total.

**Comment by Vural78** [comment]
I am getting the following error in Versin 1.3.0. The scraper doesn't seem to be working.

[![image](https://www.linkpicture.com/q/Adsız_34.png)](https://www.linkpicture.com/view.php?img=LPic626472fb681b71596570190)

**Comment by jadedtakesthiscereal** [comment]
Also on 1.3.0 I had same error once but it began working the following try 
![DEA2D9F7-C9ED-45B9-9EB9-238D471377FB](https://user-images.githubusercontent.com/102177219/164956807-18cf7379-2c65-4433-9dcb-40cdfe70bde9.jpeg)

@maximedrn  here is where I ended up,

missing file was correct

Unique file and missing file would make the 10k exact

full file is 3165 total more (13165)

duplicate says 3184 total

 opensea says I’m at 10092 
Animalbudsnft is where i am scrapin

**Comment by maximedrn** [comment]
> I am getting the following error in version 1.3.0. The scraper doesn't seem to be working.

Check your version, 3.1.0 should not raise this error.

**Comment by maximedrn** [comment]
> Also on 1.3.0 I had same error once but it began working the following try 
> @maximedrn here is where I ended up,
> missing file was correct
> Unique file and missing file would make the 10k exact
> full file is 3165 total more (13165)
> duplicate says 3184 total
> opensea says I’m at 10092 Animalbudsnft is where i am scrapin

Error on my part, I did not remove from the list the NFTs scraped twice so there are too many items.
Also you are at 10004 in your collection.

Unfortunately it always forgets 2 NFTs and I don't know why (usually it's the ones in the first or last 10).

I will put in the evening (UTC+2) the version 3.1.1 on Gumroad. You can access it as usual by the email receipt.
If you don't have it anymore, tell me your email before the @ so I can send it back to you.
Be sure to check the version indicated.

**Comment by jadedtakesthiscereal** [comment]
Thanks sir, I will log in to gumroad and download when I get back home.

**Comment by jadedtakesthiscereal** [comment]
Version 1.3.1  from command prompt using python scraper.py failed like this again 
![80881240-AF1D-4858-B5A5-301DD863B33C](https://user-images.githubusercontent.com/102177219/165179716-fe0f9b6e-78be-4ec2-a01b-b3d32f7b9815.jpeg)  
Worked successfully by double clicking scraper.py file in directory.

found my 4 extra, shows 1 missing but it is there as expected.  Full and unique file both back to 10k~.  Successful for me.  Thank you sir.
