### ISSUE TITLE
Unable to connect to MetaMask using the private key feature.

### ISSUE THREAD

**Issue by spesivan** [maximedrn/opensea-automatic-bulk-upload-and-sale#268]
Login to MetaMask. Login to MetaMask failed. Retrying.
Login to MetaMask. Login to MetaMask failed. Restarting.

ı cant login metamask. when ı run code, driver wait on metamask and opensea didnt open
edit: Now ı understand. ıf you write private key, opensea didnt open and code waiting on metamask

**Comment by maximedrn** [comment]
> Edit: Now I understand. if you write private key, opensea didnt open and code waiting on metamask

This is a pull request feature that I have never tested. I will try to improve it as it may be useful for people who want to use a different account on the same wallet.
