### ISSUE TITLE
OpenSea has made changes to the upload page.

### ISSUE THREAD

**Issue by Vural78** [maximedrn/opensea-automatic-bulk-upload-and-sale#270]
I'm using the latest version of the bot and it's waiting on the Add features page while NFT uploads. The bot shows the error "Failed to upload NFT".

Before I got this error, when I visited my collection page, I displayed the error message "Internal Server Error".

The bot needs a minor update.

[![image](https://www.linkpicture.com/q/1_4.png)](https://www.linkpicture.com/view.php?img=LPic625fe66b728d21757344256)

**Comment by Vural78** [comment]
The problem seems to be fixed now.

**Comment by maximedrn** [comment]
Please re-open this issue if you still have this problem :)
