### ISSUE TITLE
Yolov5 not work

### ISSUE THREAD

**Issue by ajdev0** [maximedrn/opensea-automatic-bulk-upload-and-sale#271]
it show me this error
```
An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is enough powerful,
every modules are installed and files are correctly
downloaded and presents in the directory.
No module named 'basicsr.utils.diffjpeg'  
``` 
my windows info
![image](https://user-images.githubusercontent.com/42712613/164360667-01e3d2dd-42a4-49bc-a0b1-a268c974c68d.png)

**Comment by maximedrn** [comment]
The Basicsr module is not installed with your Python.
Also, your graphics card does not seem to be powerful enough.
Check this section: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#prerequisites-for-recaptcha-solver
