### ISSUE TITLE
DD-MM-YYYY format duration problem with XLSX.

### ISSUE THREAD

**Issue by Pavelrdk** [maximedrn/opensea-automatic-bulk-upload-and-sale#274]
You need to put up for sale 2000 NFT, When you put in xlsx duration "3 days" everything works, but if there is a deferred sale and I write ["25-04-2022 04:00", 28-04-2022 04:00"] then writes "NFT sale cancelled." and does not put it up for sale.
![image](https://user-images.githubusercontent.com/104226336/164780086-f60e053e-9146-459c-bfdd-7221a5851edb.png)

**Comment by maximedrn** [comment]
Let me check. Maybe try to check if it happened because of the time or because of something else.
Can you send me a short video clip of what happens at the time of the duration input?

**Comment by Pavelrdk** [comment]
the first line still runs 2 times for some reason
https://user-images.githubusercontent.com/104226336/164878953-e8ed562d-03a5-42f7-970b-bd456b08ed8c.mp4

**Comment by maximedrn** [comment]
Can you try again by correcting the yellow error below the price?
I tried it on my end and it works fine with XLSX and the same details you put in your file.

**Comment by maximedrn** [comment]
Same problem here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/141
And I don't know why :s

**Comment by Pavelrdk** [comment]
The error under the price does not affect, the warning only. When I change the duration "3 days" it works. In the video, 
![vlcsnap-2022-04-23-15h40m31s440](https://user-images.githubusercontent.com/104226336/164891158-b14b54b8-ca2c-43eb-9897-25540e4ae8a5.png)
I removed the error by raising the price, and the button is clickable in the video. Here is a video where duration is changed to "3 days"
![vlcsnap-2022-04-23-15h41m47s862](https://user-images.githubusercontent.com/104226336/164891185-90aec726-ede3-4b13-8b84-fd0bedb94fe8.png)

**Comment by maximedrn** [comment]
On your video, the robot opens the drop-down list. It should not.
You are under MacOS?
