### ISSUE TITLE
Feedback about the Generic File Maker.

### ISSUE THREAD

**Issue by Many2050** [maximedrn/opensea-automatic-bulk-upload-and-sale#275]
![Captura de pantalla (12)](https://user-images.githubusercontent.com/101189664/164800345-71c3b989-0270-4c07-9d71-d822d6dc1457.png)
I get this error can you help me

**Comment by Many2050** [comment]
can you feel me the steps to follow the script?

**Comment by maximedrn** [comment]
You already have a file generated by Hashlips (I assume).
Select "**Duplicate from an existing file**", then select a generic file (not your metadata file) that you have populated with the details you want to replicate. Finally, select your `_metadata.json` file and it will duplicate the details. The file is saved in the `data/` directory.

I recommend changing all `attributes` in your `_metadata.json` to `properties`, likewise for the `name` to `nft_name`.

**Steps:**
- Open the file on Visual Studio Code (_or any text editor_).
- Type `CTRL` + `F` (Command + `F` on MacOS).
- In the "**Search**" field type `attributes`.
- In the "**Replace**" field (click on the arrow) type `properties`.
- Click on "**Replace All**" (second button next to "Replace All" field).

If you have an error during the process. Send me a screenshot, your generic file and a part of your `_metadata.json` file.

**Comment by Many2050** [comment]
thanks, it does it like this using first the generic file of the same script and then at the end I choose my metadata created with Hashlips the 10k ntf metadata do I need another generic file? thank you

**Comment by maximedrn** [comment]
Your `_metadata.json` and a generic file from the generic folder is required. Obviously complete the generic file with what you want to add in the metadata file.

**Comment by maximedrn** [comment]
> thanks for everything is it necessary to put the properties? or does the metadata add them automatically? all

Since your `_metadata.json` file already has properties, leave the generic file properties empty if you don't want to add generic properties for all your NFTs.
That's why I mentioned these steps below to convert `attributes` from HashLips to `properties` (same for `name`):

> I recommend changing all `attributes` in your `_metadata.json` to `properties`, likewise for the `name` to `nft_name`.
>
> **Steps:**
> - Open the file on Visual Studio Code (_or any text editor_).
> - Type `CTRL` + `F` (Command + `F` on MacOS).
> - In the "**Search**" field type `attributes`.
> - In the "**Replace**" field (click on the arrow) type `properties`.
> - Do the same thing for `name` to `nft_name`.
> - Click on "**Replace All**" (second button next to "Replace All" field).

**Comment by maximedrn** [comment]
If for example the path of the file containing all your NFTs is `C:/Users/Admin/Desktop/NFTs/` and your NFTs have a name like `nft_1.png`, `nft_2.png`, etc.
You will need to enter `C:/Users/Admin/Desktop/NFTs/nft_{}.png` in the file_path part of your generic file.

**Comment by Many2050** [comment]
@maximedrn  thanks my ntf only has example number 1 2 3 4 do not have name I do not know if that will be the probrema thanks for everything
Browsing on your computer...
Something went wrong. Invalid \escape: line 4 column 29 (char 70)
PS C:\Users\Master\Documents\OpenSea_Generic_File>
