### ISSUE TITLE
Coinbase Wallet

### ISSUE THREAD

**Issue by jadedtakesthiscereal** [maximedrn/opensea-automatic-bulk-upload-and-sale#278]
Using version 1.7.0 choosing coinbase wallet the bot 

1- this may be planned?, does not ask which browser (it asks when I choose metamask)

2-choose my metadata file hit enter, screen flashes downloading chromedriver then a flash of done with green text like normal and then my cmd screen just sits at a black flashing _        No error pops no browser ever tries to open  (this version does work normally when I choose metamask)

**Comment by maximedrn** [comment]
1 - Coinbase Wallet extension is only available on Google Chrome.
2 - Let me fix that

**Comment by maximedrn** [comment]
It's fixed now :)
Problem with the parameters of the login() and sign() functions, and the exec() function was creating an infinite error because the import was incorrect.
