### ISSUE TITLE
No module named 'pyclick'

### ISSUE THREAD

**Issue by Priyarajsinh** [maximedrn/opensea-automatic-bulk-upload-and-sale#280]
Downloading the ChromeDriver. ChromeDriver downloaded: 
C:\Users\priya\.wdm\drivers\chromedriver\win32\100.0.4896.60\chromedriver.exe

An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is powerful enough,
every modules are installed and files are correctly 
downloaded and presents in the right directory.
No module named 'pyclick'

C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>

**Comment by maximedrn** [comment]
Have downloaded required modules for the Yolov5 reCAPTCHA solver?

**Comment by Priyarajsinh** [comment]
> Do you have downloaded required modules for the Yolov5 reCAPTCHA solver?

i have done everything step by step 
first i did :- pip install -r requirements.txt
second :- nvidia-smi
third i did :- pip install -r requirements_recaptcha.txt
fourth :- python main.py 
so tell me what am i missing ? and how to download this Yolov5 reCAPTCHA solver

**Comment by maximedrn** [comment]
Install Pytorch:
```
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```
And then retry to install:
```
pip install -r requirements_recaptcha.txt
```
Make sure that no error is displayed

**Comment by Priyarajsinh** [comment]
> Install Pytorch:
> 
> ```
> pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
> ```
> 
> And then retry to install:
> 
> ```
> pip install -r requirements_recaptcha.txt
> ```
> 
> Make sure that no error is displayed

I'm downloading pytorch , and can you please tell me where and in which file I have to put my nft collection and it's metadata?

**Comment by maximedrn** [comment]
> Can you please tell me where and in which file I have to put my nft collection and it's metadata?

It doesn't matter, the path to your assets (NFTs) will be specified in your metadata file. This file you can look for on your computer when starting the script (by selecting 0, a window opens).

**Comment by Priyarajsinh** [comment]
> > Can you please tell me where and in which file I have to put my nft collection and it's metadata?
> 
> It doesn't matter, the path to your assets (NFTs) will be specified in your metadata file. This file you can look for on your computer when starting the script (by selecting 0, a window opens).



> > Install Pytorch:
> > ```
> > pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then retry to install:
> > ```
> > pip install -r requirements_recaptcha.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure that no error is displayed
> 
> I'm downloading pytorch , and can you please tell me where and in which file I have to put my nft collection and it's metadata?
Downloading the ChromeDriver. ChromeDriver downloaded: 
C:\Users\priya\.wdm\drivers\chromedriver\win32\100.0.4896.60\chromedriver.exe

An error occured while loading Yolov5 and RealESRGAN.
Please verify that your computer is powerful enough,
every modules are installed and files are correctly 
downloaded and presents in the right directory.
No module named 'pyclick'

C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
Collecting torch==1.11.0+cu113
  Using cached https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp310-cp310-win_amd64.whl (2186.0 MB)
Collecting torchvision==0.12.0+cu113
  Using cached https://download.pytorch.org/whl/cu113/torchvision-0.12.0%2Bcu113-cp310-cp310-win_amd64.whl (5.4 MB)
Collecting torchaudio===0.11.0+cu113
  Using cached https://download.pytorch.org/whl/cu113/torchaudio-0.11.0%2Bcu113-cp310-cp310-win_amd64.whl (573 kB)
Requirement already satisfied: typing-extensions in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from torch==1.11.0+cu113) (4.2.0)
Requirement already satisfied: numpy in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from torchvision==0.12.0+cu113) (1.22.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from torchvision==0.12.0+cu113) (9.1.0)
Requirement already satisfied: requests in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from torchvision==0.12.0+cu113) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->torchvision==0.12.0+cu113) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->torchvision==0.12.0+cu113) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->torchvision==0.12.0+cu113) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\priya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->torchvision==0.12.0+cu113) (2021.10.8)
Installing collected packages: torch, torchvision, torchaudio


ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\priya\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths


C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>

ERROR is coming see that could not install packagesto an OSError , now what to do?

**Comment by maximedrn** [comment]
I advice to use Python 3.9.11 with my bot, so Python 3.10 can result to some crashes while installing modules.
If you don't want to downgrade your Python version, you can create an environnement (if you know how).
For this error above, maybe run the command line as administrator can solve the problem, or look at this link the error gave you: https://pip.pypa.io/warnings/enable-long-paths

**Comment by Priyarajsinh** [comment]
Bro I have graphics card RTX 3050 , then it will work right?

And you said this program will only work on this graphics card
GTX 1080.
RTX 2060, RTX 2070, RTX 2080.
RTX 3060, RTX 3070, RTX 3080, RTX 3090.
Any Ti version of these graphics cards.

**Comment by maximedrn** [comment]
It should work with an RTX 3050.

**Comment by Priyarajsinh** [comment]
> I advise to use Python 3.9.11 with my robot, because Python 3.10 can cause crashes when installing modules. If you don't want to upgrade your Python version, you can create an environment (if you know how). For the error above, maybe running the command line as an administrator can solve the problem, or check out this link the error gave you: https://pip.pypa.io/warnings/enable-long-paths, it explains how to fix long path error.

Same problem with python 3.9 version and recaptcha code has also problem :(

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\priya\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'

PS C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master> pip install -r requirements_recaptcha.txt
Collecting basicsr==1.3.5
  Using cached basicsr-1.3.5.tar.gz (161 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\priya\AppData\Local\Temp\pip-install-78nd30p_\basicsr_ce56b8e847ce445da73e847cd4dafc74\setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>

**Comment by maximedrn** [comment]
Install `requirements.txt`
Install Pytorch with the command in the README file.
Install `requirements_recaptcha.txt`, after Pytorch because some modules require the installation of Torch.

**Comment by Priyarajsinh** [comment]
give me the link to download python 3.9.11 version , so i can download it . Previous i accidentlly downloaded python version 3.9.12 .    
requirements.txt and recaptcha_requirements.txt file want python version 3.9.9 and 3.9.11 so give me the link to download version 3.9.11

**Comment by maximedrn** [comment]
Windows: https://www.python.org/ftp/python/3.9.11/python-3.9.11-amd64.exe
MacOS: https://www.python.org/ftp/python/3.9.11/python-3.9.11-macosx10.9.pkg

**Comment by Priyarajsinh** [comment]
> Windows: https://www.python.org/ftp/python/3.9.11/python-3.9.11-amd64.exe MacOS: https://www.python.org/ftp/python/3.9.11/python-3.9.11-macosx10.9.pkg

Thanks everything downloaded perfectly and the software was running but i was not having time o i will try tomorrow and tell you what happened , and thanks again for your help 😊

**Comment by Priyarajsinh** [comment]
Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.

NFT n°1/1:
Your file is poorly structured for this NFT.
Check that elements are present and in the right order.

All done!
In order to support me, you can make donations at this address:
0xDD135d5be0a23f6daAAE7D2d0580828c9e09402E (Ethereum).
PS C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>

I still didn't get that , where i have to put my nft collection and metadata , please help me :((

**Comment by maximedrn** [comment]
> Your file is poorly structured for this NFT.
> Check that elements are present and in the right order.

You forgot some details in your metadata file, send me your file and I will tell you what is missing.

**Comment by Priyarajsinh** [comment]
> > Your file is poorly structured for this NFT.
> > Check that elements are present and in the right order.
> 
> You forgot some details in your metadata file, send me your file and I will tell you what is missing.

Then i found the file and filled the details and then i again tried and i reached ''ADD ITEM'' , but then pic was not uploaded

Login to MetaMask. Logged to MetaMask.
Login to OpenSea. Logged to OpenSea.

NFT n°1/1:
Uploading NFT. Upload failed. Message: The file extension is not supported on OpenSea.

Uploading NFT. Upload failed. Message: The file extension is not supported on OpenSea.

Data saved in data/upload_and_sale_8e2597d5.csv.

All done!
In order to support me, you can make donations at this address:
0xDD135d5be0a23f6daAAE7D2d0580828c9e09402E (Ethereum).
PS C:\Users\priya\Downloads\opensea-automatic-bulk-upload-and-sale-master\opensea-automatic-bulk-upload-and-sale-master>

**Comment by Priyarajsinh** [comment]
{
    "nft": [
        {
            "file_path": "C:/Users/priya/OneDrive/Pictures/bulk-upload-to-opensea-main/src",
            "nft_name": "Chunchunmaru #",
            "external_link": "",
            "description": "The Chunchunmaru NFTs",
            "collection": "CryptoLions.",
            "properties": "C:/Users/priya/OneDrive/Pictures/bulk-upload-to-opensea-main/src",
            "levels": [],
            "stats": [],
            "unlockable_content": [
                false,
                ""
            ],
            "explicit_and_sensitive_content": false,
            "supply": 1,
            "blockchain": "polygon",
            "sale_type": "WETH",
            "price": 2,
            "method": [],
            "duration": "360",
            "specific_buyer": "",
            "quantity": "1"
        }
    ]
}

**Comment by maximedrn** [comment]
You should have something like this: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/blob/master/data/examples/json_structure_upload_and_sale.json
So in red this is what you have to change.
```json
{
    "nft": [
        {
            "file_path": "C:/Users/priya/OneDrive/Pictures/bulk-upload-to-opensea-main/src/", // File name.
            "nft_name": "Chunchunmaru #",  // I think you want a number here.
            "external_link": "",
            "description": "The Chunchunmaru NFTs",
            "collection": "CryptoLions.",
            "properties": "C:/Users/priya/OneDrive/Pictures/bulk-upload-to-opensea-main/src", // No, look at example file.
            "levels": [],
            "stats": [],
            "unlockable_content": [
                false,
                ""
            ],  // Make sure you have the latest version, this format caused a crash by my fault.
            "explicit_and_sensitive_content": false,
            "supply": 1,
            "blockchain": "polygon",  // "Polygon" is better, I do not remember if my bot understand this in lowercase.
            "sale_type": "WETH",  # No, look at example file.
            "price": 2,
            "method": [],
            "duration": "360",  # Maximum is "6 months".
            "specific_buyer": "",
            "quantity": "1"  # This should be an integer, not quotes -> 1 not "1".
        }
    ]
}
```
