### ISSUE TITLE
reCAPTCHA Bypasser error (forgot to update a file)

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#283]
![1](https://user-images.githubusercontent.com/102164388/166217974-7e1e810e-920a-4429-93fe-a08a08eeea4c.png)
New bypasser doesnt work, 
i check on polygon. and ETH, doesnt work, when windows with robot appear it show error, always

**Comment by maximedrn** [comment]
This problem is similar to this one: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/281
Sorry for my mistake, I forgot to update a file (`upload.py`).
