### ISSUE TITLE
OpenSea team doesn't know what to do: enable and disable reCAPTCHA.

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#287]
Congratulations friends!I hope a new version of the uploader will be released soon Maxime?

**Comment by maximedrn** [comment]
For now remove the line 226 in the upload file.
Select the first option at recaptcha.
It won't check for recaptcha.

**Comment by Sequento** [comment]
> For now remove the line 226 in the upload file. Select the first option at recaptcha. It won't check for recaptcha.

Is the first option manual? Will there be a fully automatic version upload and sell?

**Comment by maximedrn** [comment]
It's already full automatic. Yes select the first option but remove this specific line in the upload.py file

**Comment by Sequento** [comment]
![1](https://user-images.githubusercontent.com/102164388/166417178-c50e2a23-3a71-463c-adac-4d23236363cb.png)
Working! but cant sign the message automatic to complete listning

**Comment by YangJunHyuck** [comment]
> It's already full automatic. Yes select the first option but remove this specific line in the upload.py file

I remove line 226 but it make error message

**Comment by Sequento** [comment]
Captcha is back guys!!! LOL

**Comment by Sequento** [comment]
And Bypass not working now(( 
they fix that i think

**Comment by Sequento** [comment]
and 2 captcha way dont working too

**Comment by Sequento** [comment]
oops, my mistake) I forgot that I changed the upload file, converted for without captcha mode =) downloaded on a new one, everything works, bypass solves captcha, everything works fine!

**Comment by maximedrn** [comment]
So reCAPTCHAs are back my bypasser/solvers work?

**Comment by Sequento** [comment]
![1](https://user-images.githubusercontent.com/102164388/166458508-faa7bc15-226d-46e0-8ff7-c2761709da38.png)

**Comment by maximedrn** [comment]
Okay then, which blockchain do you list your NFTs on?

**Comment by Sequento** [comment]
> Okay then, which blockchain do you list your NFTs on?

now uploading on polygon. but i have to collection on ETH and Polygon. and ther work fine, when use google, and both dont work when use gecko

**Comment by Sequento** [comment]
> > > Okay then, which blockchain do you list your NFTs on?
> > 
> > 
> > both polygon and eth work with google, neither one nor the other does not work in geco
> 
> Ok, this can come from your side, I know that Geckodriver is quite unstable with the headless mode. I will try to fix everything for this webdriver. Thanks again for all this instant information :)

thank u, for u work friend! u awesome!
