### ISSUE TITLE
Unable to list NFT when using Geckodriver

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#288]
![1](https://user-images.githubusercontent.com/102164388/166936178-f4063edd-b767-4546-8bb0-f28ab83183e6.png)
New version 1.7.4 Canot put for sale after switch blockchain, on a polygon blockchain.
Its just stop. and thats all

**Comment by Sequento** [comment]
Working fine on ETHrerum blockchain

**Comment by maximedrn** [comment]
I made my test on Polygon and it worked.
Let me look at this.

**Comment by Sequento** [comment]
> I made my test on Polygon and it worked. Let me look at this.

its work on Polygon and ETH in Google Chrome, but Gecko driver stop when switch blockchain, and try to sale uploaded item.. i dont know why, because ETH in GEcko work fine

**Comment by maximedrn** [comment]
It works with Geckodriver when the headless mode is off. I don't know why, it was working before and now it stops at that moment.

**Comment by maximedrn** [comment]
Version 1.7.6 fixes this issue :)

**Comment by Sequento** [comment]
> Version 1.7.6 fixes this issue :)

Hell yeah!! Working great!!! can u explain when the error was?

**Comment by maximedrn** [comment]
This created a loop when signing the contract.
On Chromedriver, the Polygon contracts are the previous ones, but on Geckodriver they are Wyvern 2.3 so it required a scroll down.

**Comment by Sequento** [comment]
> This created a loop when signing the contract. On Chromedriver, the Polygon contracts are the previous ones, but on Geckodriver they are Wyvern 2.3 so it required a scroll down.

awesome!! Thank u friend!!

**Comment by Sequento** [comment]
> This created a loop when signing the contract. On Chromedriver, the Polygon contracts are the previous ones, but on Geckodriver they are Wyvern 2.3 so it required a scroll down.
![1](https://user-images.githubusercontent.com/102164388/167263123-f91b3dc6-febe-471a-b2dd-3f7790717e6c.png)
Another problem sir, some items cant put the sale.... but uploading
POLYGON GECKO

**Comment by maximedrn** [comment]
Hmm, I made a list on Polygon with Geckodriver and it works, let me check what I forgot to update.

**Comment by Sequento** [comment]
> Hmm, I'm listing on Polygon with Geckodriver and it works great, let me check what I forgot to update.

maybe it's a polygon problem? I looked at the status they have a delay more than usual now, and the network is loaded

**Comment by maximedrn** [comment]
Maybe it's coming from your file? You may have set the blockchain to Ethereum, but it's actually Polygon or vice versa.

**Comment by Sequento** [comment]
![1](https://user-images.githubusercontent.com/102164388/167263448-0df7ae8e-9412-46f0-8d8e-420a7a1152b5.png)
no, everything is in order, the collection is at the landfill, and the bot changed the blockchain at the beginning of the upload

**Comment by maximedrn** [comment]
I had the same problem after a while. I do not know if it's my bot or the Polygon network
