### ISSUE TITLE
HashLips Art Engine metadata file question.

### ISSUE THREAD

**Issue by jsbskzbakwu6568** [maximedrn/opensea-automatic-bulk-upload-and-sale#289]
i just confuse in meta data section so i used hashlibs art engine to generate images and it gives me main meta data and sperate for each NFT,,, so my qustion is This main file wont work in you bot,,, or it will work,,, or there is somthing to change to make it work,, thanks

**Comment by maximedrn** [comment]
I need to see your file, I know that some modifications are required when creating a file with the HashLips Art Engine tool in order to use it with my bot.
