### ISSUE TITLE
Unable to edit metadata file.

### ISSUE THREAD

**Issue by abdurrehmanRasheed12** [maximedrn/opensea-automatic-bulk-upload-and-sale#290]
I have purchased the Opensea generic file maker.
But I'm unable to edit the metadata .
I also have sent you email with all the details kindly have a look at it.
Looking forward to purchase 3 more of tools as soon as I get the edited metadata file.
Thank you.
@maximedrn

**Comment by maximedrn** [comment]
I sent you an email :)
