### ISSUE TITLE
fail to sale NFT in polygon with xlsx

### ISSUE THREAD

**Issue by luxingyu10** [maximedrn/opensea-automatic-bulk-upload-and-sale#292]
fistly I really thank you for your excellent codes that help us upload nft in the best way, It is the best software of uploading NFT with your tool sets!
but I fail to sale NFT in fix price, and I have checked xlsx many times without finding a single mistake............
 could you please help check what goes wrong？
![1](https://user-images.githubusercontent.com/52501223/167600720-97c17e45-8397-4400-a885-8230928f3103.jpg)

**Comment by maximedrn** [comment]
It must be `["1 month"]` or `1 month`, not `[1 month]` :)
You can let the Method and Sale Type cells empty if you want (optional).

**Comment by maximedrn** [comment]
I'm closing this issue because I think it's now resolved on your end.
Reopen it if it is not :)
