### ISSUE TITLE
Cannot login to MetaMask after clicking on the "Import" button.

### ISSUE THREAD

**Issue by blastersjack** [maximedrn/opensea-automatic-bulk-upload-and-sale#294]
![image](https://user-images.githubusercontent.com/50685805/167759908-548fc4ef-27d1-424a-896c-5cfd195794b1.png)
I tried this for a few days after I click the Import button and it keeps on failing, is there any solution for this?

**Comment by maximedrn** [comment]
Can you send me a video of what happens after clicking the import button.
Maybe an unwanted tab opened.
