### ISSUE TITLE
Collection Scraper: No such file or directory: 'node index.js'.

### ISSUE THREAD

**Issue by ricardovf** [maximedrn/opensea-automatic-bulk-upload-and-sale#295]
Using your tool opensea-collection-scraper

```
What is your collection URL (example: crypto-parrot-nfts)? xxxxx
Scraping collection https://opensea.io/collection/xxxxx.
Something went wrong.
[Errno 2] No such file or directory: 'node index.js --collection xxxxx'
```

I hided the name of the collection because it's not launched yet.

If i run node index.js --collection xxxxx it runs and generates a json file, but i guess that the process to generate the csv, etc at the data folder is on python.

Using OSX Catalina here. Python 3.9.7. Node v14.18.1

**Comment by maximedrn** [comment]
Are you sure that all files are in the same directory?
```
opensea-collection-scraper
├── requirements.txt
├── packages.json
├── scraper.py
├── index.js
├── opensea.js
╰── utils.js
```

`[Errno 2] No such file or directory` means that the file cannot be found in the current directory.

**Comment by ricardovf** [comment]
Yes...

As the python scraper.py has code obfuscation, i can't debug it... How are you calling node from it?

**Comment by maximedrn** [comment]
I made an update, it now calls this: `node "path/to/index.js" --collection "collection"`,
instead of `node index.js --collection collection`.
This should solve your problem on macOS, as it may work differently with paths 🙂.

**Comment by ricardovf** [comment]
Not, it does not work.

Something went wrong.
[Errno 2] No such file or directory: 'node "/Users/ricardo/NFT/Code/lab/xxx/opensea-collection-scraper/index.js" --collection "xxx"'

If I run directly it works:

(base)  ✘ ricardo@Ricardos-iMac  ~/NFT/Code/lab/hashlips_art_engine/opensea-collection-scraper   main ●  node "/Users/ricardo/NFT/Code/lab/xxx/opensea-collection-scraper/index.js" --collection "xxx"
100
100

Also i added

import os
os.system('node --version')
os.system('pwd')

And it shows the correct node version and folder.

Is there any command i can insert on scraper.py to help you debug?

**Comment by maximedrn** [comment]
Maybe try to run Python with sudo :s
I used the most specific command that calls from an absolute path

**Comment by lucca93** [comment]
Hi Maximedrn

This problem is solved, but its now stuck here (tried with VisualStudioCode and Ubuntu Console, both the same):
![image](https://user-images.githubusercontent.com/43188541/169464792-b80c192a-52a4-4baf-bda4-ac185cd6e7b7.png)

**Comment by lucca93** [comment]
Hi Maximedrn
its now stuck here (Tested on Ubuntu  Console and on Visual Studio Code):
![image](https://user-images.githubusercontent.com/43188541/169465067-295ab611-267d-40dd-a8fe-888e8c244804.png)

**Comment by lucca93** [comment]
Yes Google Chrome and Chromium is installed.

node index.js --collection crypto-parrot-nfts
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lucca93/OpenSea_Collection_Scraper/opensea-collection-scraper/opensea.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)


![image](https://user-images.githubusercontent.com/43188541/169564943-590fc0ab-3861-47b8-afe1-0740d7e96f70.png)

**Comment by maximedrn** [comment]
> Error: Cannot find module 'puppeteer'

`sudo apt install npm`
`sudo npm install`

**Comment by lucca93** [comment]
npm was already installed, I did it again in the tool path (also with sudo its not working):
![image](https://user-images.githubusercontent.com/43188541/169566247-8798ba13-c792-4502-a2d3-c9b1dd7f3a6c.png)

**Comment by lucca93** [comment]
Its realy much easier on windows, got it to work here fast :)
Thanks for the support.
👯

**Comment by maximedrn** [comment]
I think it is possible but difficult on Linux. = error should be fixed for macOS as it is easier to work with Python and Node.js/npm.

So I close this question, I reopen it if someone still has a problem :)
