### ISSUE TITLE
Sale only issue.

### ISSUE THREAD

**Issue by Bass2015** [maximedrn/opensea-automatic-bulk-upload-and-sale#300]
Hi, 
First of all, thanks for this great tool. 
I've used it to upload an nft, and then I want to use the generated csv to sell it. (If I choose upload +sale option it works fine). 
Every time I tried, I got the "NFT sale cancelled" message, but with no error message. I had to comment part of the code in Sale.sale() to see what was happening
![imagen](https://user-images.githubusercontent.com/78235553/168662583-206f6315-fd7a-4eb2-a56c-30519f6f8f99.png)

I also wrote a print at the beginning of every method(check_price(), quantity(), etc.) to see where the code was and where it stopped. 
After this, I saw the the error is a NoSuchElementError@chrome:, in the quantity() method (which is the first that does a "send_keys" with the driver. If I bypass the quantity method, I get the same error in the next method that does a "send_keys":
![imagen](https://user-images.githubusercontent.com/78235553/168663123-edec8f91-7415-4c55-aaad-f5a8a48e6322.png)
![imagen](https://user-images.githubusercontent.com/78235553/168663191-477a7a6a-ce6e-47a3-a558-b1cc0d722835.png)

I've been stucked with this error for a while, my problem is that I don't know selenium :(. Do you have any idea of what's happening??

Well, thanks in advance :)

**Comment by maximedrn** [comment]
Can you send me your metadata file please :)
It may say Ethereum while the NFT is on Polygon.

**Comment by Bass2015** [comment]
The NFT is on Ethereum, and the metadata says Ethereum
[sale_9bca7b67.csv](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/8706035/sale_9bca7b67.csv)

**Comment by maximedrn** [comment]
I think I fixed the problem, now it goes to the NFT URL.
Download the new version 1.7.11 and let me know if it works :)

**Comment by Bass2015** [comment]
Hey man, 
Didn't work still. It says "NFT cancelled" 
Haven't checked why yet

**Comment by maximedrn** [comment]
Hi, I just tried both ChromeDriver and GeckoDriver, "Download and Sale" and "Sale Only" with exactly the same details you have in your metadata file and it works fine. It enters the quantity and price and signs the contract.

Can you remove the headless mode from GeckoDriver and send me a video of what happens?

**Comment by Bass2015** [comment]
Hi man, 
I found the problem. The bot was saving the url of the uploaded nft with "?created=true" at the end. As I am using the generated file, then the bot used that url, added the "/sell" part and then tried to access it. Obviously that url doesn't exist. So I wrote this to the "switch_etereum" (which may not be the best solution, but it works by now 😄 
![imagen](https://user-images.githubusercontent.com/78235553/169114761-5bcf90a9-f6d0-464a-8be2-fd75a2398634.png)

**BUT THEN**
Then I'm finding another issue: 
![imagen](https://user-images.githubusercontent.com/78235553/169115607-4ff5eaba-e945-4ce2-a7db-0d3d3da2488b.png)

But when I check in opensea, I see that it has listed it twice, and it seems to work well. I run it without the headless option, and I actually saw the "confirmed listing" window.
![imagen](https://user-images.githubusercontent.com/78235553/169115977-7429322d-2619-4675-83cc-9a4592009dcf.png)


**FINALLY**
Another thing, a suggestion. 
I wanna use the bot both to upload and later sell a whole collection, but I wanna do it in two steps. So, until I don't have the whole  nfts uploaded, I don't sell any of them. The initial metadata I have has the 18 details needed for the upload+sale option. When I upload the images, I want to retrieve the information of the sale part (the last points) to generate the sale file. So, I take all of the points needed for the sale part and copy it in that new file. I'm doing it my way, on top of your code, but maybe you want to give that option too. 

Well, Thanks again for this amazing tool.

**Comment by HiHdrl** [comment]
![image](https://user-images.githubusercontent.com/98240334/169170532-ffe70991-e16e-46ca-98f8-d88b2e97a28d.png)
i have the same problem too

**Comment by maximedrn** [comment]
Maybe try the latest version. I know this error, it occurs while the bot scans the pop up that says "Your NFT is listed". (`check_listed()`, `sale.py`)

**Comment by HiHdrl** [comment]
hi, i just tried the new version and it did the same thing

**Comment by maximedrn** [comment]
![imagen](https://user-images.githubusercontent.com/78235553/169114761-5bcf90a9-f6d0-464a-8be2-fd75a2398634.png)
> 
![imagen](https://user-images.githubusercontent.com/78235553/169115607-4ff5eaba-e945-4ce2-a7db-0d3d3da2488b.png)

I solved both problems by adding your changes for the first one. For the second one, it now continues when it says "NFT seems not to be listed", it will not try a second time.
