### ISSUE TITLE
Collection Scraper wont work

### ISSUE THREAD

**Issue by lucca93** [maximedrn/opensea-automatic-bulk-upload-and-sale#301]
Hello
I cant scrap my collection, tried it with windows (VisualStudio Code) and Ubuntu.
Do you know this issue?

![image](https://user-images.githubusercontent.com/43188541/169236346-856ab693-b8d6-4885-8547-ae8dea4421f7.png)

**Comment by maximedrn** [comment]
This is exactly the same problem on MacOS (https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/295).
I'm trying to solve this problem on a Debian virtual machine.
