### ISSUE TITLE
Read this when Cloudflare protection appears.

### ISSUE THREAD

**Issue by walphar** [maximedrn/opensea-automatic-bulk-upload-and-sale#302]
We need to solve this problem somehow. OpenSea does not allow the bot to enter the site, the browser check window pops up

**Comment by gamextar** [comment]
I had some success adding some waiting to the login step but it also appears randomly after creating some nuts

**Comment by uk137** [comment]
Hi Maxime! Cloudflare's protective window is blocking the script working.

**Comment by uk137** [comment]
https://github.com/elcattivo/CloudFlareUtilities might help.

**Comment by maximedrn** [comment]
I will try to add this feature. But really, just wait a few hours.
It is working as I write this post.
