### ISSUE TITLE
Cannot delete my NFTs when it is listed (OpenSea Deletion tool)

### ISSUE THREAD

**Issue by vipsland** [maximedrn/opensea-automatic-bulk-upload-and-sale#307]
deletion script not working because... "cancel listing" first? doesnt seem to be able to delete

**Comment by maximedrn** [comment]
Hello, can you send me a video of what is going on please. I would like to make sure that I have the same problem as you.

On my end, the bot can't click the "Edit" button, so it doesn't go to the edit page.
I edit something and it seems to delete the NFT even though it is listed.

**Comment by hiqsociety** [comment]
yes same if it's listed.

also if it's not listed, it seems to click on "Sell"

**Comment by maximedrn** [comment]
> yes same problem as urs if it's listed.
> 
> also if it's not listed, it seems to click on "Sell"

Have you tried it with the new update?
It works for me on Polygon with the listed NFTs.

**Comment by maximedrn** [comment]
Hello, can you tell me if everything works fine with the latest version?
