### ISSUE TITLE
File Compatibilizer and Converter Error

### ISSUE THREAD

**Issue by hkid1412** [maximedrn/opensea-automatic-bulk-upload-and-sale#310]
i got error when i put my folder path.
'Something went wrong. list indices must be integers or slices, not str'
![image](https://user-images.githubusercontent.com/106618151/171236072-fa79bd8d-11e1-4088-b44f-1e4b38578eba.png)

**Comment by maximedrn** [comment]
If you tried to convert from Hashlips files, be sure to delete the `_metadata.json` file.
