### ISSUE TITLE
Error message displayed during the listing by OpenSea.

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#312]
https://i.postimg.cc/s1dJJ6jY/openseaerr.jpg

what's wrong?

**Comment by maximedrn** [comment]
I don't know, I have to solve this problem but I don't know if this happens during a manual upload and listing.

**Comment by hiqsociety** [comment]
upload is ok but listing failed. so i'm using upload nfts now but not able to put price.

**Comment by maximedrn** [comment]
I close this issue, it seems that it has been fixed by OpenSea
