### ISSUE TITLE
ChromeDrive Upload Problem

### ISSUE THREAD

**Issue by saiyan100** [maximedrn/opensea-automatic-bulk-upload-and-sale#313]
Hello.
When I want to upload with chromedrive, an error occurs in the last section right after the price entered part and the horse cannot be made. I would be glad if you help. Thank you.

Edit : Serially repeating the error on the page.

https://ibb.co/cYwxjbR

**Comment by maximedrn** [comment]
Same error here: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/312
I'm trying to fix it
