### ISSUE TITLE
Error in driver of chrome as well as google

### ISSUE THREAD

**Issue by amankashyapynr** [maximedrn/opensea-automatic-bulk-upload-and-sale#315]
Hello i am getting this error while running it, please help me in it
/Users/addy/.wdm/drivers/geckodriver/macos/v0.31.0/geckodriver
Something went wrong. 
Expecting property name enclosed in double quotes: line 30049 column 9 (char 720943)

**Comment by maximedrn** [comment]
It comes from your metadata file.
Open it and at the line 30049, you forgot to enclose the property name with a double quotes `"`.

**Comment by amankashyapynr** [comment]
Thanks for the solution
