### ISSUE TITLE
Switching/ signing doesn't work

### ISSUE THREAD

**Issue by saiyan100** [maximedrn/opensea-automatic-bulk-upload-and-sale#317]
Hello.

While shooting with the bot, he does not sign when he comes to the last part. He keeps returning to the beginning and still not signing. I would be glad if you help. Thank you.

https://ibb.co/Vt2gZ7z

**Comment by hidanx** [comment]
I have the same problem, since last night, she hasn't clicked on the signature part. Is there any solution?

**Comment by maximedrn** [comment]
I saw this yesterday, I started to fix it but didn't finish
Let me do it before Friday :)

**Comment by saiyan100** [comment]
> I saw this yesterday, I started to fix it but didn't finish Let me do it before Friday :)

thank you very much :)

**Comment by maximedrn** [comment]
Version 1.7.18 fixes this problem, thanks for your report!
