### ISSUE TITLE
"Failed to Fetch", "API Error 429", ... when listing on Ethereum.

### ISSUE THREAD

**Issue by maximedrn** [maximedrn/opensea-automatic-bulk-upload-and-sale#319]
### Discussed in https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/discussions/318

<div type='discussions-op-text'>

<sup>Originally posted by **Sequento** June 12, 2022</sup>
![2](https://user-images.githubusercontent.com/102164388/173248901-ee21ab39-d192-4f7e-8623-99f879e96abb.png)
![Screenshot_1](https://user-images.githubusercontent.com/102164388/173248949-63d56ac1-bf81-4edd-a5f7-b5fb942f7292.png)

</div>

**Comment by maximedrn** [comment]
~I had removed the listing check on Ethereum because it didn't work before. Test version 1.7.19.1, I added a new check which seems to work fine :)~
I removed the 404 page error verification in version 1.7.19.2. It caused the duplicate.

**Comment by Sequento** [comment]
> ~I had removed the listing check on Ethereum because it didn't work before. Test version 1.7.19.1, I added a new check which seems to work fine :)~ I removed the 404 page error verification in version 1.7.19.2. It caused the duplicate.

opensea introduced a new feature by disabling google captcha)
now you have to wait 50 seconds before listing the next nft

**Comment by Sequento** [comment]
listing through one with the latest version is better than nothin
![Screenshot_1](https://user-images.githubusercontent.com/102164388/173255291-7b032481-db18-429c-86f4-c154a930baba.png)
g

**Comment by maximedrn** [comment]
Okay, so what's really going on?
It's only on the Ethereum blockchain so that's why it doesn't list the NFT every other time.

**Comment by Sequento** [comment]
> Okay, so what's really going on?
> It's only on the Ethereum blockchain so that's why it doesn't list the NFT every other time.

I can’t say for sure, I didn’t check it at the polygon, but in ETH it’s exactly like that

**Comment by Sequento** [comment]
13.06.2022 all working perfectly!! its just was a weekend solution, because network was busy.....for now bot upload and listing perfectly!!! on a ETH chain

**Comment by ApeLife24** [comment]
> 13.06.2022 all working perfectly!! its just was a weekend solution, because network was busy.....for now bot upload and listing perfectly!!! on a ETH chain

I'm having this issue, Failed to Fetch and API error 429.
Probably on the Opensea end and not fault of this amazing script.

Did you got it solved? I honestly been having this issue for 2 or 3 day's trying to get my collection listed but is been impossible still have more than 80% of the collection unlisted, if anyone has any solution for this and can share it, I see other projects that list without problems, but is been a problem for me.

**Comment by maximedrn** [comment]
Hi, I'm currently working on a fix for this error so that I don't count this as a failure and try again until it works.

In the meantime, I propose a temporary fix. In the `app/services/processes/sale.py file`, **remove the lines from 256 to 259** and** modify line 260** (254 after removing the other lines) by removing the 4 spaces.
This gives you these:

```python
try:
    # ...
except Exception as error: # Any other error.
    if self.web.page_error(): # Check if there is a 404
        return self.sale() # page error.
    print(f'{RED}NFT sale cancelled.{RESET}',
             str(error).replace('Message: ', '').replace('\n', '')
             if 'Stacktrace' not in str(error) else '')
    self.wallet.close() # Close the wallet extension popup.
    self.sale() # Try to re-upload the NFT.
self.fails = 0 # Reset the counter for next listing.
```

When the bot will try to enumerate, it will do this:
![image](https://user-images.githubusercontent.com/91475935/173533543-60953897-0395-4591-ba87-454dbcffa9fb.png)
