### ISSUE TITLE
SSL error when the bot checks the version

### ISSUE THREAD

**Issue by spesivan** [maximedrn/opensea-automatic-bulk-upload-and-sale#323]
![image](https://user-images.githubusercontent.com/88890641/174503194-f4d8db5e-b62d-435b-b3d8-4beee4f0d7b5.jpeg)

I can't run code in new version and I don't understand what is change and what should I do

**Comment by maximedrn** [comment]
Oh.. sorry for that.
Download the latest evrsion 1.8.3
It should fix this issue with a try/except.

**Comment by spesivan** [comment]
Thanks
