### ISSUE TITLE
Looping Timed Auction Sell

### ISSUE THREAD

**Issue by spesivan** [maximedrn/opensea-automatic-bulk-upload-and-sale#324]
Code looping to time auction to fixed price. And looping again.
After ı upload code try to sell 3 times to nft
nowadays code didnt work very well 
Should you try it and can you help?

**Comment by maximedrn** [comment]
Can you send me a video of this happening, please?
If you don't want to make this video public, send it to me on [Telegram](https://t.me/maximedrn) or by email ([maxime_drean@yahoo.com](mailto:maxime_drean@yahoo.com)).

**Comment by maximedrn** [comment]
Re: can you please try the version 1.8.4 and let me know if it fixes something.
Someone had an issue with the Ethereum contract signature on the ChromeDriver and I fixed it in this version.

**Comment by spesivan** [comment]
Ok After I try if it's work or fail I will tell you

**Comment by maximedrn** [comment]
I close this issue due to inactivity.
Reopen it if necessary 🙂
