### ISSUE TITLE
put up for sale through one

### ISSUE THREAD

**Issue by Sequento** [maximedrn/opensea-automatic-bulk-upload-and-sale#325]
in the latest version 1.9.4 again puts up for sale through one. sad, because there was a working version 1.8.0, with an endless check, until it is put up for sale.

**Comment by maximedrn** [comment]
I try to get the text when an NFT is listed (`Your item has been listed!`) using this method:

```python
def check_listed(self) -> None:
        """Check if the NFT is listed."""
        try:  # Check if the "Your item has been listed" text is displayed.
            self.web.window_handles(1)  # Switch back to the OpenSea tab.
            self.web.visible('//header/h4[contains(., "list")]', 30)
        except Exception:  # The NFT is not listed.
            raise TE('NFT seems to not be listed.')
```

**Can you tell me if it works on your side?**

**Comment by Sequento** [comment]
does not work.
just like the previous version gives only thi
![Screenshot_1](https://user-images.githubusercontent.com/102164388/175825227-0b6dddca-a4bc-4290-bb06-34fdae724852.png)
s

**Comment by maximedrn** [comment]
Does the "Failed to fetch" error appear when it fails?

**Comment by Sequento** [comment]
> 

yep, need time to list another one nft, about 30 seconds must be set between listings, then each will be set

**Comment by maximedrn** [comment]
Ok, I tried it on my end and it seems to work with the latest version (1.9.6).
It correctly scrapes the text when it lists the NFT.

However, I can't do anything for the `Failed to fetch` error except an infinite loop when it detects that the item is not listed (Ethereum only).
