### ISSUE TITLE
The bot stops every 40 NFTs (Solution available but needs feedback!)

### ISSUE THREAD

**Issue by leoaless** [maximedrn/opensea-automatic-bulk-upload-and-sale#330]
Hello, every 35-40 NFTs uploaded the scripts stop.

```
NFT n°37/89:
Uploading NFT. Solving the reCAPTCHA. Solved. NFT uploaded.
Sale of the NFT. Something went wrong. 
Message: invalid session id
Stacktrace:
0   chromedriver                        0x00000001096d1079 chromedriver + 4444281
1   chromedriver                        0x000000010965d403 chromedriver + 3970051
2   chromedriver                        0x00000001092f7eef chromedriver + 409327
3   chromedriver                        0x00000001093217ee chromedriver + 579566
4   chromedriver                        0x0000000109322a95 chromedriver + 584341
5   chromedriver                        0x00000001096a255d chromedriver + 4253021
6   chromedriver                        0x00000001096a73a1 chromedriver + 4273057
7   chromedriver                        0x00000001096ac16f chromedriver + 4292975
8   chromedriver                        0x00000001096a7dea chromedriver + 4275690
9   chromedriver                        0x000000010968154f chromedriver + 4117839
10  chromedriver                        0x00000001096c1ed8 chromedriver + 4382424
11  chromedriver                        0x00000001096c205f chromedriver + 4382815
12  chromedriver                        0x00000001096d88d5 chromedriver + 4475093
13  libsystem_pthread.dylib             0x00007ff81270c4e1 _pthread_start + 125
14  libsystem_pthread.dylib             0x00007ff812707f6b thread_start + 15
```

After updating the files:

```
NFT n°31/61:
Uploading NFT. Solving the reCAPTCHA. Solved. NFT uploaded.
Sale of the NFT. NFT put up for sale.

NFT n°32/61:
Uploading NFT. Upload failed. 
Uploading NFT. Upload failed. 
Metadata saved in the data/upload_and_sale_482f9138.json file.

NFT n°33/61:
Uploading NFT. Upload failed. 
Uploading NFT. Upload failed. 
Metadata saved in the data/upload_and_sale_482f9138.json file.
```

Video: https://drive.google.com/file/d/1YAffqrH_fFJVlsTj-2WnZm8LcPyIzlk0/view?usp=sharing

**Comment by maximedrn** [comment]
Hi, I know about this problem but I can't reproduce it. Is it possible for you to send me a record of when this happens?

**Comment by leoaless** [comment]
Hi, not it just stops where it crashed -always when the price needs to be set - so the NFT upload works always but then it crashed at the price process

**Comment by maximedrn** [comment]
Can you send me a video of what's going on? I don't understand if the above file fixes anything or not.

**Comment by leoaless** [comment]
here the video: https://drive.google.com/file/d/1YAffqrH_fFJVlsTj-2WnZm8LcPyIzlk0/view?usp=sharing

**Comment by leoaless** [comment]
just tested - after 30 NFTs it crashed but now I have the logs:

showing you only the 2 first:
"nft": [
        {
            "file_path": "/Users/Alessandro/Downloads/NFT/1_Jets/V4/2_Rafal Jet/images/871.png",
            "nft_name": "Jet Aircraft Club #871 - Delta Wing Collection",
            "external_link": "https://twitter.com/JetAircraftClub",
            "description": "Jet Aircraft Club or J.A.C. is 4 collections of randomly generated NFTs that exist on the Blockchain. Centered around airplanes, jets, aircraft enthusiasts. 1000x1000 pixel - Jet Aircraft Club #871 - Delta Wing Collection",
            "collection": "Jet Aircraft Club - Delta Wing Collection",
            "properties": [],
            "levels": [],
            "stats": [],
            "unlockable_content": [],
            "explicit_and_sensitive_content": false,
            "supply": 1,
            "blockchain": "Polygon",
            "sale_type": "",
            "price": 0.01,
            "method": "",
            "duration": "6 months",
            "specific_buyer": "",
            "quantity": 1
        },
        {
            "file_path": "/Users/Alessandro/Downloads/NFT/1_Jets/V4/2_Rafal Jet/images/872.png",
            "nft_name": "Jet Aircraft Club #872 - Delta Wing Collection",
            "external_link": "https://twitter.com/JetAircraftClub",
            "description": "Jet Aircraft Club or J.A.C. is 4 collections of randomly generated NFTs that exist on the Blockchain. Centered around airplanes, jets, aircraft enthusiasts. 1000x1000 pixel - Jet Aircraft Club #872 - Delta Wing Collection",
            "collection": "Jet Aircraft Club - Delta Wing Collection",
            "properties": [],
            "levels": [],
            "stats": [],
            "unlockable_content": [],
            "explicit_and_sensitive_content": false,
            "supply": 1,
            "blockchain": "Polygon",
            "sale_type": "",
            "price": 0.01,
            "method": "",
            "duration": "6 months",
            "specific_buyer": "",
            "quantity": 1
        },

**Comment by leoaless** [comment]
message from the terminal:

NFT n°31/61:
Uploading NFT. Solving the reCAPTCHA. Solved. NFT uploaded.
Sale of the NFT. NFT put up for sale.

NFT n°32/61:
Uploading NFT. Upload failed. 
Uploading NFT. Upload failed. 
Metadata saved in the data/upload_and_sale_482f9138.json file.

NFT n°33/61:
Uploading NFT. Upload failed. 
Uploading NFT. Upload failed. 
Metadata saved in the data/upload_and_sale_482f9138.json file.

**Comment by maximedrn** [comment]
Hi back,

I think the problem is common with the "Out of memory" problem. Thus, using the latest version available on Github and changing the main.py to the one attached, the RAM should stay around 600MB.

[main.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/9021647/main.zip)

**Comment by leoaless** [comment]
it works - 130 in a row without any issues :D well done
