### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by leoaless** [maximedrn/opensea-automatic-bulk-upload-and-sale#331]
Hello, 
just now the bypasser is no longer working - post serial request I get this error:

What is your reCAPTCHA Bypasser licence key? XXXXX
Something went wrong. 
Expecting value: line 2 column 1 (char 1)

but it worked all day until now.... maybe your server to check the licence is down?

**Comment by maximedrn** [comment]
That's the problem, Gumroad seems to be down for a few minutes...
They haven't communicated about this yet

**Comment by leoaless** [comment]
I thought so - hopefully is back again :D

**Comment by maximedrn** [comment]
It seems to work now :)

**Comment by leoaless** [comment]
I confirm indeed - you can close this issue
