### ISSUE TITLE
Network problem on Polygon when signing on OpenSea.

### ISSUE THREAD

**Issue by sharjeet** [maximedrn/opensea-automatic-bulk-upload-and-sale#334]
Bot isn't working, it displays the error "There was a problem adding the network" whenever it tries to list. (Polygon NFT)

**Comment by sharjeet** [comment]
https://user-images.githubusercontent.com/4517032/176988626-7a4163c6-c4cf-4f00-9f95-ec496227bd16.jpeg

**Comment by sharjeet** [comment]
Metamask updated it's extension
![image](https://user-images.githubusercontent.com/4517032/176989809-20f429d5-70de-458e-aa6e-8364d8aa3b76.png)

Please fix the issue if possible

**Comment by sharjeet** [comment]
I tried to resolve the issue but get this "Request for method 'eth_chainId on https://polygon-rpc.com failed"

**Comment by sharjeet** [comment]
![image](https://user-images.githubusercontent.com/4517032/176992224-5149d9ba-621a-40a7-a265-b6eddb11b817.png)

https://polygon-rpc.com/ isn't working somehow

**Comment by maximedrn** [comment]
What are you trying to do? The MetaMask extension is still the same because I haven't updated the file. For sure the latest version is completely different.

**Comment by sharjeet** [comment]
I've downloaded the latest version, but your bot displaying the error when it tries to list the NFT

**Comment by sharjeet** [comment]
![image](https://user-images.githubusercontent.com/4517032/176992696-6d5c4594-f306-409a-9018-e111eda48527.png)

**Comment by sharjeet** [comment]
Please try to run the bot and list the NFT in Polygon network

**Comment by sharjeet** [comment]
> What are you trying to do? The MetaMask extension is still the same because I haven't updated the file. For sure the latest version is completely different.

Your latest version displays the error i shared the screenshot, pls resolve this :(

**Comment by maximedrn** [comment]
It works fine on my end on Polygon/Ethereum.
Make sure you confirm your account once.
If it's already done, can you send me a video of what happens?

**Comment by sharjeet** [comment]
Here's the Video: https://imgur.com/a/sm6Tm21

**Comment by sharjeet** [comment]
tried again by creating new account manually in chromedriver and your latest version but still getting same error
![image](https://user-images.githubusercontent.com/4517032/176994854-47061017-3292-4738-bcc4-46f0cfa81ede.png)

**Comment by maximedrn** [comment]
Watch this: https://www.youtube.com/watch?v=ejxfxwDw5WA

**Comment by sharjeet** [comment]
i changed the RPC link manually (tried all, i shared the list above) but now bot isn't able to detect whether the list is done or not. 
bot is listing the NFT but it shows this
![image](https://user-images.githubusercontent.com/4517032/176995367-53366f91-63e3-41b1-b7ec-0dc689ac6620.png)

**Comment by sharjeet** [comment]
> ![image](https://user-images.githubusercontent.com/4517032/176992224-5149d9ba-621a-40a7-a265-b6eddb11b817.png)
> 
> https://polygon-rpc.com/ isn't working

RPC list

**Comment by sharjeet** [comment]
![image](https://user-images.githubusercontent.com/4517032/176996137-64adc998-5250-49ee-92e3-51c99b2d40bd.png)
I found the problem but don't know how to solve or fix the bot. Bot is working after solving this captcha in new tab, but need a permanent solution

**Comment by maximedrn** [comment]
Hello, do you still have this problem with the Polygon network?
