### ISSUE TITLE
TimeoutError: navigation timeout of 30000ms exceeded.

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#355]
scrapper error when using slow connection : timeouterror navigation timeout of 30000ms exceeded

how to increase this?

**Comment by hiqsociety** [comment]
it is this

https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/305

so i needed to retry a few times i think coz the 30000ms need increase to 60s
coz my collection quite large 20000

the larger it is, the more need to wait

**Comment by hiqsociety** [comment]
it fails a lot of times, i needed to retry many times like 10 times for 11th time to work

**Comment by hiqsociety** [comment]
i am getting this forever now. no matter what i do it doesnt go away.

**Comment by maximedrn** [comment]
Do you get this at the beginning of the script or during scraping?

**Comment by hiqsociety** [comment]
beginning
sometimes during

**Comment by maximedrn** [comment]
This problem is due to the license key. You tried too many times and the Gumroad API blocked you. You have to wait a while or change your network.

**Comment by hiqsociety** [comment]
i see. i have 12 collections to scrape. possible to help increase the gumroad api or something?

**Comment by maximedrn** [comment]
1 or 2 hours. You can send me the links of the collections to scrape. I will send you back the files

**Comment by hiqsociety** [comment]
it's fine. i will wait then. thx
