### ISSUE TITLE
404 erorr after update 

### ISSUE THREAD

**Issue by Tiikou** [maximedrn/opensea-automatic-bulk-upload-and-sale#358]
After succefully uploading nft ,the bot can not sell it ,it infinitely goes to https://opensea.io/collection/collection%20name/assets/create/sell
and get this erorr . I updated from version Version 1.10.0 there bot was working very well.
![Без названия (53)](https://user-images.githubusercontent.com/106772865/178147221-c156f4de-775d-4baa-a6a3-ed380878b851.png)
![Без названия (54)](https://user-images.githubusercontent.com/106772865/178147321-719109ab-082f-4de8-aebe-82757c033b17.png)

**Comment by maximedrn** [comment]
Using latest version? I removed something for collection so maybe it causes this issue

**Comment by Tiikou** [comment]
> Using latest version? I removed something for collection so maybe it causes this issue

yes .I am using Version 1.10.3

**Comment by maximedrn** [comment]
What value did you specify in the `collection` field of your metadata file?

**Comment by Tiikou** [comment]
> What value did you specify in the `collection` field of your metadata file?

 "collection": "Collection Name",  I mean real name

**Comment by maximedrn** [comment]
Use the URL format, the format of the collection name has been removed due to some problems when the robot tries to search for it in the dropdown.
For example, https://opensea.io/collection/boredapeyachtclub will be `"collection": "boredapeyatchclub",`.

**Comment by Tiikou** [comment]
> Use the URL format, the format of the collection name has been removed due to some problems when the robot tries to search for it in the dropdown. For example, https://opensea.io/collection/boredapeyachtclub will be `"collection": "boredapeyatchclub",`.

thanks , now working perfectly as usual :)

**Comment by maximedrn** [comment]
Sorry about that, I think it's better with one format instead of 2 :)
