### ISSUE TITLE
Loading nft's without metadata

### ISSUE THREAD

**Issue by CryptoPunkFrens** [maximedrn/opensea-automatic-bulk-upload-and-sale#359]
I just don't know how to upload the images nft's without metadata or if I need to make metadata to be able to upload, please show me step by step

**Comment by CryptoPunkFrens** [comment]
because this collection is individual paintings and all of them are different, no need for metadata

**Comment by maximedrn** [comment]
Just use the Generic File Maker, create your generic file, run the `generic.py` and select `Create a new file`.
