### ISSUE TITLE
possible to update the scraper to detect first numeric?

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#360]
hving problems uploading initially and i changed my item's name to be with such pattern in a collection

same collection

example #12345
example #12346
another example #12347
another example #12348

this was because some asset name clashed so i uploaded this way.

now i have more items than the collection i think it's because the scraper cant differentiate on the first unique number(s) found.

possible to update the scraper so the collection's first number found is used as unique?

**Comment by maximedrn** [comment]
I didn't understand, can you explain better?
How many elements in the collection? First value in the collection?

**Comment by hiqsociety** [comment]
the title name of a single collection with 20000 items with each item's names are:
1. item #12345
2. item #12346
3. special item #12347
4. special item #12348

these naming are within 1 collection. but the scraper (i think) cannot detect missing / duplicates this way. possible to ensure that first numeric detection is captured? basically i made a mistake with the uploader 's naming so now i have 1 collection in unique sequence BUT the naming has an additional word in front with the word "special"
