### ISSUE TITLE
Instructions? 

### ISSUE THREAD

**Issue by bowmatty** [maximedrn/opensea-automatic-bulk-upload-and-sale#367]
Hello, do you have step by step instructions on how to use? 

Many thanks

**Comment by maximedrn** [comment]
Hello, you can watch this video on YouTube: https://youtu.be/DdqGEz0BCQ8

**Comment by bowmatty** [comment]
Thanks mate... ill let you know if i run into any issues

**Comment by bowmatty** [comment]
Am i able to run this to continue my collection? i currently have 250 nfts minted, Ill need it to start at 251-10000. 

Thanks again

**Comment by maximedrn** [comment]
You can create your file from 251 to 10000 and at runtime you will start from 1, or you can create your file from 1 to 10000 and choose to start from 251.

**Comment by bowmatty** [comment]
Hello, am i able to generate from 260-9900? 
I managed to start the generic file maker at "Start increment from" 260, is there a way to finish it at 9900, instead of 10,000? 

Many thanks

**Comment by bowmatty** [comment]
Also, for the file would i list for 6 month or 180 days?, or doesn't it matter?

**Comment by maximedrn** [comment]
You can generate from 260 to 9900. Make sure you have 9900-260=9640 NFTs and when you run the Generic File Maker, and at "Start incrementation from" type 260. The tool will increment until there are no more NFTs in the folder.

Concerning the duration of the listing, you have to use "6 months", "180 days" will not work.

**Comment by bowmatty** [comment]
Also, if i dont purchase the captcha addon, will it still auto complete for me, or will i have to manually do this part? From my understanding the purchased captcha solver will make it faster. 

Thanks for all your help, video is amazing!

**Comment by maximedrn** [comment]
You have the choice. The reCAPTCHA Bypasser is obviously the best option.

If you don't want to pay, you can choose to use the Yolov5x6 solver or manually solve the reCAPTCHA for each upload.
The bot completes everything automatically but you have to stay at your computer to solve it - you have 10 minutes maximum. 

Otherwise the 2Captcha solver is available, it is $2.99 for 10k NFTs.

**Comment by bowmatty** [comment]
> Also, for the file would i list for 6 month or 180 days?, or doesn't it matter?

Whats the cleanest way to change to "6 months", im unable to change it and when i try re-running, it errors with "details". 

Im lost :(

**Comment by maximedrn** [comment]
Make sure you select "read headers" in the command prompt, you have selected the wrong file and it does not find the "details" attribute.

In the generic JSON file, you can set the duration like this:
```json
"duration": "6 months",
```

**Comment by bowmatty** [comment]
Hey mate, all working... i have one last issue lol. Im now able to generate the NFTs, however when metamask opens it defaults to Account number 1 my NFT collection is Account number 2, any way we can edit the main.py file to open my other account? other that that all works :)

Thanks for all your help :)

**Comment by maximedrn** [comment]
In the command prompt after entering the recovery phrase, it asks for you account name or private key. Try the 2 methods until it works

**Comment by bowmatty** [comment]
all good and working.
Only issue Im having is with numbering. I have setup my files to generate from 260-9990, the image and json appear correct just the numbers are wrong, its started off on 519 instead of 260.

**Comment by bowmatty** [comment]
Same issue when ive rerun the file, it starts at 519 instead of 260. Any thoughts? :)

**Comment by bowmatty** [comment]
hold on i think i know whas happened....

**Comment by bowmatty** [comment]
Able to start generating from #260 however the metadata is still from the #519. Any thoughts? My brain is fried haha

**Comment by maximedrn** [comment]
Your start from 260. So when running the `main.py` file, at `Start from n°` type 1

**Comment by bowmatty** [comment]
Maxime, i ended up restarting from 1-10,000 and deleted the 260 nfts already minted. I still had the issue with the metadata not syncing correctly. 
10,000 have all been uploaded and minted! thank you!.

**Comment by bowmatty** [comment]
“Read headers” how to i select that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
