### ISSUE TITLE
Mint Renewal 

### ISSUE THREAD

**Issue by bowmatty** [maximedrn/opensea-automatic-bulk-upload-and-sale#368]
Do you have a code to renew the mint, once it expires? 

Thanks

**Comment by maximedrn** [comment]
If you mean re-list the NFTs when they expired, you can take a look at the [Collection Scraper](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Collection-Scraper).
It retrieves the URLs and you'll be able to complete the generated file (`unique_xxxx.json` with the [Generic File Maker](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Generic-File-Maker) or `unique_xxxx.csv`/`unique_xxxx.xlsx` with shortcuts) with the price and duration.
