### ISSUE TITLE
OpenSea & Cloudflare (firewall)

### ISSUE THREAD

**Issue by saiyan1000** [maximedrn/opensea-automatic-bulk-upload-and-sale#369]
Hello.
For those who want to buy Opensea, a new security area has been added from the first shot. The page repeats itself because the bot failed to pass the security. I will be glad if you help.

https://ibb.co/x876h87

**Comment by saiyan1000** [comment]
> Hello. For those who want to buy Opensea, a new security area has been added from the first shot. The page repeats itself because the bot failed to pass the security. I will be glad if you help.
> 
> [https://ibb.co/x876h87](url)

**Comment by maximedrn** [comment]
Are you using a VPN or VPS?

**Comment by sharjeet** [comment]
yes this has been happening since this morning. We don't use vpn or vps and after error, tried VPN and sock5 proxy too but nothing worked

**Comment by saiyan1000** [comment]
sanaldan atarken bu sorunla karşılaştım. Arkadaşlarımda kullanıyor onlarda da aynı sorun olmuş sordum onlarada.

**Comment by saiyan1000** [comment]
> evet bu sabahtan beri oluyor Vpn veya vps kullanmıyoruz ve hatadan sonra VPN ve sock5 proxy'yi de denedik ama hiçbir şey işe yaramadı

yes true.

**Comment by maximedrn** [comment]
Let me work on this, it is a new security from OpenSea

**Comment by sharjeet** [comment]
> Let me work on this, it is a new security from OpenSea

Thank you

**Comment by maximedrn** [comment]
I think a simple time.sleep(15) can bypass this.
Otherwise, I'll have to add some parameters to the webdriver.

**Comment by sharjeet** [comment]
![image](https://user-images.githubusercontent.com/4517032/189346995-7cd12f0b-137f-4582-8222-484878492290.png)

**Comment by sharjeet** [comment]
> ![image](https://user-images.githubusercontent.com/4517032/189346995-7cd12f0b-137f-4582-8222-484878492290.png)

It didn't work

**Comment by saiyan1000** [comment]
> I think a simple time.sleep(15) can bypass this. Otherwise, I'll have to add some parameters to the webdriver.

hatayı giderebilirseniz çok sevinirim. Teşekkürler

**Comment by saiyan1000** [comment]
> I think a simple time.sleep(15) can bypass this. Otherwise, I'll have to add some parameters to the webdriver.

I would be very happy if you could fix it. thanks.

**Comment by sharjeet** [comment]
everything is a game, opensea increased security to decrease the transactions. Now eth is rising.

**Comment by maximedrn** [comment]
I just tried now and there is no Cloudflare page

**Comment by maximedrn** [comment]
Can anyone tell me if it is still there?

**Comment by Tiikou** [comment]
I got this erorr, it disapears after sometime (12h-24h)

**Comment by maximedrn** [comment]
> I got this erorr, it disapears after sometime (12h-24h)

It's always the same problem since months. OpenSea adds this security when there is too much traffic.
The only thing you can do is to wait until it disappears. Unfortunately, the bot can't go through this page.

**Comment by applesin** [comment]
Unfortunately, I have not been able to get access to opensea due to this error for several days.

**Comment by maximedrn** [comment]
> Unfortunately, I have not been able to get access to opensea due to this error for several days.

You may need a paid VPN to access to OpenSea. It depends on your region.
