### ISSUE TITLE
Token selection (MATIC/WETH) and Timed Auctions for Polygon.

### ISSUE THREAD

**Issue by saiyan1000** [maximedrn/opensea-automatic-bulk-upload-and-sale#371]
Hello. Opensea has offered a price option as the new generation "MATIC", the bot cannot choose ETH as MATIC over the entered ones.
Even if I distribute it as a polygon, MATIC cannot select automatically in the price section. Can you help me? There's no need. thanks.

https://ibb.co/S3h8Xh0

**Comment by maximedrn** [comment]
It's on my list. I need to add the timed auctions for Polygon and token selection for both blockchains.

**Comment by maximedrn** [comment]
Released! (still in beta so you can have some errors 😊)
