### ISSUE TITLE
Loop on "404 page error" message.

### ISSUE THREAD

**Issue by Tiikou** [maximedrn/opensea-automatic-bulk-upload-and-sale#372]
This error started 3-4 days ago ,I was using Version 1.10.9 (got this error) and updated to Version 1.11.0 (getting it here too) 
It appears randomly , usually 99% of the time bot just refreshes the NFT page and do nothing , 1% of the time it solves the error(5-10 tries)  and working fine .
I am using Chrome , just tested on firefox I got same error.
I checked how bot go (from chrome history) - opensea.io/assets/etherium/blabla/ then opensea.io/assets/etherium/blabla/sell do not list NFT as supposed to ,then  go back to opensea.io/assets/etherium/blabla/ (same nft) and reload it constantly 
If I manually go to opensea.io/assets/etherium/blabla/sell  or https://opensea.io/collection/blabla/assets/create  it continue to refresh opensea.io/assets/etherium/blabla/  
![Без названия](https://user-images.githubusercontent.com/106772865/191119718-286b294a-d590-4611-9ed4-27d5a726b91c.png)
![Без названия (65)](https://user-images.githubusercontent.com/106772865/191119826-68eb9274-329c-418b-a951-4ac900d18f88.png)
![Без названия (66)](https://user-images.githubusercontent.com/106772865/191120529-82d415ae-01c5-47ee-a787-cecbe4d42297.png)

**Comment by maximedrn** [comment]
It is on my list, I do not know why this error happens.
For now you can edit the `app/services/webdriver.py` file:
```python
    def page_error(self) -> bool:
        """
        Check the actual state of the page and if there is an error.

        Check if the page is correctly displayed (404 page error)
        or if a red message is displayed at the bottom right.
        """
        return False
        """try:
            self.window_handles(1)  # Switch to OpenSea.
            for text in ['This page is lost', 'something went wrong']:
                if text in self.driver.page_source:
                    print(f'{YELLOW}404 page error.{RESET}')
                    return True
            return False
        except Exception:
            return False"""
```

**Comment by Tiikou** [comment]
> ```python
> """
> ```

Thanks , I will try

**Comment by saiyan1000** [comment]
Hello. I have the same problem too. It's been two days and it hangs in the same place and gives a 404 error in the program. Is there a way to fix it? Thank you.

https://ibb.co/0YPfZ7N

**Comment by saiyan1000** [comment]
> > ```python
> > """
> > ```
> 
> Thanks , I will try

were you able to solve the problem?

**Comment by maximedrn** [comment]
> It is on my list, I do not know why this error happens. For now you can edit the `app/services/webdriver.py` file:
> 
> ```python
>     def page_error(self) -> bool:
>         """
>         Check the actual state of the page and if there is an error.
> 
>         Check if the page is correctly displayed (404 page error)
>         or if a red message is displayed at the bottom right.
>         """
>         return False
>         """try:
>             self.window_handles(1)  # Switch to OpenSea.
>             for text in ['This page is lost', 'something went wrong']:
>                 if text in self.driver.page_source:
>                     print(f'{YELLOW}404 page error.{RESET}')
>                     return True
>             return False
>         except Exception:
>             return False"""
> ```

I fixed this issue but it will be released with new features on which I'm working.
For now use this code above

**Comment by saiyan1000** [comment]
> 

I will try the codes, thanks. If I can't handle it, we are waiting for your new version :)

**Comment by Tiikou** [comment]
> > > ```python
> > > """
> > > ```
> > 
> > 
> > Thanks , I will try
> 
> were you able to solve the problem?

I guess - 16 hours without 404error , either new code is working or opensea fixed the error

**Comment by saiyan1000** [comment]
> 

I will replace the passwords here with the codes above, right?

![Adsız](https://user-images.githubusercontent.com/113181992/191546388-92a4aeb6-4fb0-4bac-bbdb-b4d9e8970d51.png)

**Comment by maximedrn** [comment]
You can add a `return False` after the function's comment so it doesn't run the next lines.

**Comment by saiyan1000** [comment]
> You can add a `return False` after the function's comment so it doesn't run the next lines.

thank you very much friend
