### ISSUE TITLE
"NFT cannot be deleted."

### ISSUE THREAD

**Issue by CryptoPunkFrens** [maximedrn/opensea-automatic-bulk-upload-and-sale#373]
Hi Maxime!
I have some problem with deleting NFT's, I did run the scraper and created file but when I run deleting error is coming : NFT cannot be deleted. What I'm doing wrong? Please help

**Comment by maximedrn** [comment]
Make sure that the NFTs are not in the list. Otherwise, the "Success!" message will not appear at the bottom of the page.
Anyway, let me check if everything still works 🙂

**Comment by CryptoPunkFrens** [comment]
Make sure that the NFTs are not in the list./ how to do that???

**Comment by maximedrn** [comment]
Look at the URLs in the `duplicate_xxxx.json` file and make sure they are not listed NFTs.

**Comment by CryptoPunkFrens** [comment]
I don't have duplicate file

**Comment by maximedrn** [comment]
I mean the file with the URL.

**Comment by maximedrn** [comment]
Hi, I've tried the tool and it works well for **Polygon (listed and unlisted)** and **Ethereum (unlisted only)**.
Make sure you use a "Sale" file format of the Collection Scraper tool - **it must contain the URLs of the NFTs you want to delete.**
