### ISSUE TITLE
Unable to connect to OpenSea.

### ISSUE THREAD

**Issue by socr102** [maximedrn/opensea-automatic-bulk-upload-and-sale#375]
![image](https://user-images.githubusercontent.com/83195375/191922030-f4d110e4-3ce6-4c54-b1e4-cf979a5df335.png)
Hello
When I login with metamask, it fails
I uploaded the screenshoot
could you tell me why login is not working?

**Comment by maximedrn** [comment]
Hello, it should connect to OpenSea.
Can you send me a video as a screenshot does not solve your problem.
I think it comes from your network - it takes too long for the 2nd pop-up to appear.
