### ISSUE TITLE
Deletion tool: "Invalid control character at: line 4 column 177 (char 201)".

### ISSUE THREAD

**Issue by janbuhh** [maximedrn/opensea-automatic-bulk-upload-and-sale#378]
System: 
Windows 10 / Powershell as administrator
Chrome 105.0.5195.127
Firefox 105.0.1

```
Downloading the ChromeDriver. ChromeDriver downloaded:
C:\Users\jan\.wdm\drivers\chromedriver\win32\105.0.5195.52\chromedriver.exe
Something went wrong.
Invalid control character at: line 4 column 177 (char 201)
```

**Comment by maximedrn** [comment]
I'm sorry but this error means everything and nothing 😅
Can you try this file so I can know the full error.

Also make sure you are using Python 3 and not Python 2.

[main.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/9658191/main.zip)

**Comment by janbuhh** [comment]
Thanks for your fast answer.
I´m using Python 3.9.11

The metadata file could be the problem. I used the sales.json as a template as you wrote... errors are possible.
[delete.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/9658385/delete.zip)

Here my traceback:

Traceback (most recent call last):
  File "D:\opensea-automatic-bulk-upload-and-sale-master\main.py", line 171, in <module>
    wallet, reader, structure, save, recaptcha, delete = main(
  File "D:\opensea-automatic-bulk-upload-and-sale-master\main.py", line 133, in main
    reader = Reader(file)
  File "D:\opensea-automatic-bulk-upload-and-sale-master\app\common\reader.py", line 50, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "D:\opensea-automatic-bulk-upload-and-sale-master\app\common\reader.py", line 58, in extract_json_file
    self.file = loads(file.read())['nft']
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 177 (char 201)

**Comment by maximedrn** [comment]
It comes from the file:

It should be:
```json
{
    "nft": [
        {
            "nft_url": "https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/51160884721344825673184274006259840960010599994099796333647637833913101975553"
        },
        {
            "nft_url": "https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/51160884721344825673184274006259840960010599994099796333647637832813590347777"
        }
    ]
}
```

Instead of:
```json
{
     "nft": [
       {
         "nft_url": "https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/51160884721344825673184274006259840960010599994099796333647637833913101975553	"//,
        },
       {
         "nft_url": "https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/51160884721344825673184274006259840960010599994099796333647637832813590347777"//,
        }//,
       ]
   }
```

**Comment by janbuhh** [comment]
Thanks, that helped!
