### ISSUE TITLE
Selling Contract signing don´t work

### ISSUE THREAD

**Issue by janbuhh** [maximedrn/opensea-automatic-bulk-upload-and-sale#379]
Hello Maxime,
the upload of content is working well, but the Bot can´t handle the signature request for the selling process. 
To find out, if it is my fault I´ve changed the Computer, I´ve reinstalled the Chrome Browser and I´ve tried it with a new installation of your bot. Allways the same problem. Do you need more information?
Best regards
Jan

To sign the signature request it is necessary to scroll down the Metamask window that the "sign" button appears and the Bot don´t do it.
This is the Metamask Signature Window:
<img width="260" alt="signature window1" src="https://user-images.githubusercontent.com/48029938/192736667-96c9abe5-ef3b-4100-abb6-0ff70c98bafc.png">

This is the sinature window after a manually scroll down:

<img width="258" alt="signature window2" src="https://user-images.githubusercontent.com/48029938/192735143-54fe7f88-bde4-4e85-99b3-fb69befeaa29.png">

<img width="535" alt="message" src="https://user-images.githubusercontent.com/48029938/192738065-d4870e4e-7d70-40f9-a0f9-b2941b526a59.png">

**Comment by maximedrn** [comment]
Can you tell me the blockchain on which you are listing your NFTs?
Moreover, is it possible to have a video of the listing when it fails? I think I made an error somewhere in the script with the switch from Polygon to Ethereum.

**Comment by janbuhh** [comment]
The Blockchain is Ethereum. I will upload the video in few minutes

**Comment by janbuhh** [comment]
Hello Maxime,
here is an update from my side.
When I use the floor price (0.01 ETH) in the JSON file it happens what I described above. 
Now I have increased the price slightly (0.011 ETH) and suddenly the script works and the signature request window differs from the other (above).
Is it maybe the problem that I always took the floor price?

**Comment by maximedrn** [comment]
Version 1.12.2 fixes this
