### ISSUE TITLE
Upload fails - Not authorized contract editor

### ISSUE THREAD

**Issue by marciliocarvalho** [maximedrn/opensea-automatic-bulk-upload-and-sale#380]
![Screenshot 2022-10-01 002049](https://user-images.githubusercontent.com/9354932/193392660-0639e5a7-2f85-4486-92dd-e6067e15fee2.png)

**Comment by maximedrn** [comment]
Make sure you are uploading to the correct collection.
If you have entered an incorrect collection URL (that you are not a contributor or creator on), it will not work.
