### ISSUE TITLE
Problems with importing 2nd MetaMask account

### ISSUE THREAD

**Issue by martonovic** [maximedrn/opensea-automatic-bulk-upload-and-sale#383]
Problem as mentioned in the title. Can't log in automatically to 2nd account on MetaMask. I resolved this by logging in manually, but it currently needs a workaround. After logging in to MetaMask and pressing "Import", I need to open a second MetaMask window to import the 2nd account with my private key, then go back to the window where I originally pressed "import". Then continue from terminal...

**Comment by maximedrn** [comment]
The account name and private key are not supported for manual login.
They must be entered in the command prompt
