### ISSUE TITLE
Upload failed error

### ISSUE THREAD

**Issue by sharjeet** [maximedrn/opensea-automatic-bulk-upload-and-sale#386]
![image](https://user-images.githubusercontent.com/4517032/195135266-3950653f-f48d-4770-950d-8dd50481f1ad.png)

I am getting this error after updating to the latest version. I used to run 4 or more bots very comfortably but now only 1 bot runs or none.

**Comment by maximedrn** [comment]
May you send me your metadata file?

**Comment by sharjeet** [comment]
which one, the bot created after the error or the file which has metamask account details?

**Comment by maximedrn** [comment]
Do not share the file with MetaMask details.
I need the metadata file you created for the upload (with the NFT name, description, etc)

**Comment by sharjeet** [comment]
everything is working fine yesterday, but today i'm getting this error, like check the following image
![image](https://user-images.githubusercontent.com/4517032/195148481-ce1f35d9-9dc5-4770-912b-1ac3b1394e46.png)

2 bots are working fine but others are having an issue

**Comment by maximedrn** [comment]
With too many processes, delays can be longer.
I suggest you take a look at this discussion: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/discussions/293

**Comment by sharjeet** [comment]
> I tried the Google chrome option instead of Geckodriver, bot can't able to sign the metamsk contract window after login.

**Comment by sharjeet** [comment]
after opensea login, bot tries to fillup the details but the popup windows which requires sign in, bot doesn't sign in the window

**Comment by maximedrn** [comment]
> With too many processes, delays can be longer. I suggest you take a look at this discussion: #293

And this?

**Comment by sharjeet** [comment]
not working

**Comment by sharjeet** [comment]
I'm using one account in multiple processes, it was working fine but now, from today, having errors

**Comment by maximedrn** [comment]
For me, I think it takes too long to complete the upload.
You can try disabling headless mode for Chrome to see what happens.

**Comment by sharjeet** [comment]
I tried older versions (attaching screenshot) and maybe opensea updated its platform

![image](https://user-images.githubusercontent.com/4517032/195174850-5f33d407-f6ca-472e-837c-73719689f2e8.png)

**Comment by xavier238** [comment]
Hi  @sharjeet  This is an opensea error. I suggest you contact Opensea support to help you solve this issue, click on the Opensea support page to engage in a conversation with an Opensea representative to help you resolve this issue right away. [SUPPORT](https://opensea.opns.support/)

**Comment by maximedrn** [comment]
Do not click on this link, it is a scam

**Comment by rubensben** [comment]
Hi! Same problem here, the only way I made it work was with GeckoDriver and manual reCAPTCHA solving.

1 - When using the ChromeDriver and the reCAPTCHA Bypasser

![When using the ChromeDriver and the reCAPTCHA Bypasser](https://user-images.githubusercontent.com/4449630/195407336-1a6ed51c-5eed-4085-a075-975ef1e1f036.jpg)

2 - When using the Geckodriver and the reCAPTCHA Bypasser

<img width="362" alt="image" src="https://user-images.githubusercontent.com/4449630/195407267-47a006c9-5393-4954-b062-298753438ab7.png">


The metadata file is not showing any error

Any clue @maximedrn ?

**Comment by maximedrn** [comment]
> With too many processes, delays can be longer. I suggest you take a look at this discussion: #293

Follow this. If it still doesn't work, can you send me a video of the process (log manually to OpenSea so the window is displayed)?

**Comment by rubensben** [comment]
Same situation (I've doubled the numbers). By logging manually and doing the reCAPTCHA manually, everything is working fine (with ChromeDriver)

**Comment by sharjeet** [comment]
Program can't able to sign the metamask contract after opensea login

**Comment by maximedrn** [comment]
> Program can't able to sign the metamask contract after opensea login, when we goto Create NFT page, a metamask window appears to sign the contract but program doesn't click on "sign" it continuously refreshes the page and displays "upload failed"

He signs the contract when your network or OpenSea's network is not overloaded. Otherwise, the connection to OpenSea may fail.

**Comment by rubensben** [comment]
ok, fixed when putting very high numbers in the upload.py, the OpenSea network must be congested.

**Comment by maximedrn** [comment]
The last version should fix this issue! :)
