### ISSUE TITLE
for sale listing

### ISSUE THREAD

**Issue by infinitelost** [maximedrn/opensea-automatic-bulk-upload-and-sale#387]
Hi, not sure if its ok to post, sorry about that.
So, I have a 10,000 collection ALREADY MINTED(i mint them myself) on the polygon network. im trying to do the listing for sale but opensea and metamask are infuriating  slow and could take me literally 6 months to finish listing them all. so i was wondering… to ONLY list my nfts for sale with your program? and how can I do it?
perhaps short tutorial… im not to smart with coding.. lol.

**Comment by maximedrn** [comment]
If you only want to list your NFTs to OpenSea, you will need a file with the URLs of each NFT.
You can have a look at this discussion: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/discussions/345

**Comment by infinitelost** [comment]
yes, i already have created an excel file with the 10,000 urls. that was a very simple process actually that takes less 1 minute without using any “url scrapper”. but my question was if it is possible to only do the listing for sale, and if so what are the best steps to achieve it.
