### ISSUE TITLE
How to only sale my NFTs?

### ISSUE THREAD

**Issue by infinitelost** [maximedrn/opensea-automatic-bulk-upload-and-sale#388]
yes, i already have created an excel file with the 10,000 urls. that was a very simple process actually that takes less 1 minute without using any “url scrapper”. but my question was if it is possible to only do the listing for sale, and if so what are the best steps to achieve it.

_Originally posted by @infinitelost in https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/issues/387#issuecomment-1279617018_

**Comment by maximedrn** [comment]
Make sure to have this format: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Creation-of-the-metadata-file#sale-only-metadata-file
And select "Sale only" when running the bot.

**Comment by infinitelost** [comment]
hey thank you so much for answering. yes I have the excel file but I have couple dumb questions… like in the “Method” column should I use [false] because the price is fixed?? as in no high offers accepted nor high bidding accepted, only accepting the fixed price.

and the same for “Quantity” should i put [false] or [0] or just live “blank” if I don’t have an “Specific Buyer”?? im using [false] in “Specific Buyer” just to be clear.

also the the NFT are minted on polygon so should I live “blank” the blockchain column??

Sorry for the dumb questions. i downloaded the example “xlsx_structure_sale_only” file and read the instructions but i still need some clarity in how to go about filling those.

thank you very much.

**Comment by maximedrn** [comment]
> For the **method** column, should I use `[False]` because the price is fixed?
<table>
<tbody>
<tr>
<td>Method</td>
<td>|</td>
<td>Method</td>
</tr>
<tr>
<td>Fixed Price</td>
<td>|</td>
<td>Timed Auction</td>
</tr>
</body>
</table>

> For the **quantity** column, should I put `[False]` or `0` or just let it blank?

If the supply is equal to `1`, the quantity must be equal to `1`.
If the supply is higher than `1`, the quantity can be any number between `1` and the supply number (included).
<table>
<tbody>
<tr>
<td>Supply</td>
<td>Quantity</td>
<td>|</td>
<td>Supply</td>
<td>Quantity</td>
</tr>
<tr>
<td>1</td>
<td>1</td>
<td>|</td>
<td>4</td>
<td>3</td>
</tr>
</body>
</table>

> If I don't have a **specific buyer**, should I use `[False]` or let it blank?

Let the field blank.

> The NFTs are hit on Polygon so I have to clear the blockchain column?
<table>
<tbody>
<tr>
<td>Blockchain</td>
</tr>
<tr>
<td>Polygon</td>
</tr>
</body>
</table>

**Comment by infinitelost** [comment]
hey thanks. but i was reffering to the  the “Method” Column not the “Sale Type” column..
the “Method” column takes [“sell with declining price”, 0.002] in your example file so my question was if im using “Fixed Price” in the “Sell Type” column, then in the “Method” column should I lived blank??
The “Method” Column only takes [“Sell with declining price”, 0.02] and [“Sell to highest budder”, 0.0] and [“Sell to highest bidder”, “”] in your example file.

**Comment by maximedrn** [comment]
Updated
