### ISSUE TITLE
Version 1.12.10 Bot Can not login to opensea

### ISSUE THREAD

**Issue by Tiikou** [maximedrn/opensea-automatic-bulk-upload-and-sale#393]
Bot working good with Version 1.12.5 .
I updated bot to Version 1.12.10 and it connects to metamask but not to opensea just lopping this errors
![Без названия (69)](https://user-images.githubusercontent.com/106772865/197361085-cb3d93b6-fe81-44e4-91f8-0c42e656058f.png)
Here is the upload and sale json (just for first nft) (if I put 0.01 in price instead of [0.01, "ETH"] - not working too)
![Без названия (70)](https://user-images.githubusercontent.com/106772865/197361145-ec82031d-b717-4039-8a3b-c1e189525f05.png)

**Comment by maximedrn** [comment]
`app/services/webdriver.py`, quotes lines 65 to 67 like this:
```python
def chrome(self) -> webdriver:
        """Start a Chrome webdriver and return its state."""
        options = webdriver.ChromeOptions()  # Configure options for Chrome.
        # Add wallet extension according to user choice.
        options.add_extension(eval(f'self.{self.wallet_name}_extension_path'))
        """if self.solver != 1 and self.wallet.recovery_phrase != '' and \
                self.wallet.password != '':  # Not manual solver.
            options.add_argument('--headless=chrome')  # Headless mode."""
        etc ...
```

And run the bot again, can you tell me what happens (you can record if needed)?

**Comment by Tiikou** [comment]
> ```python
> def chrome(self) -> webdriver:
> ```
The Chrome window pop up and bot logined to opensea all working good now , I added the """ marks
