### ISSUE TITLE
Cannot load properties (old version? / wrong format?)

### ISSUE THREAD

**Issue by CryptoPunkFrens** [maximedrn/opensea-automatic-bulk-upload-and-sale#394]
Hi Maxime!
Please can you help with this issue. Can't load property and error is: 404 page error.
What I'm doing wrong????
Many Thanks

**Comment by CryptoPunkFrens** [comment]
I really need your help. I tried 1000 time and the same error all the time
![404 page error](https://user-images.githubusercontent.com/108060093/198543565-55da2dbe-5c6f-45ad-be43-801a3843af9b.png)

**Comment by maximedrn** [comment]
Hello, I need more details...
Can you tell me what version of the tool you are using?
Also, can I have an extract of the properties?

**Comment by CryptoPunkFrens** [comment]
how I can see the version of the tool? Do you need version of all the tools?

**Comment by maximedrn** [comment]
![image](https://user-images.githubusercontent.com/91475935/198589448-4aca0808-cb2c-474d-9194-66882a77abf0.png)

**Comment by CryptoPunkFrens** [comment]
![extract of the properties](https://user-images.githubusercontent.com/108060093/198589130-da92d2d2-fadc-480a-8f27-478654c812ad.png)

**Comment by CryptoPunkFrens** [comment]
![version](https://user-images.githubusercontent.com/108060093/198589789-48a3c7e4-876b-4838-9203-03f94e8a8d87.png)

**Comment by maximedrn** [comment]
Download the last version. You have a version with bugs because OpenSea changed his webpage.

**Comment by CryptoPunkFrens** [comment]
ok I see 1.12.10 is available,  I should go and update

**Comment by CryptoPunkFrens** [comment]
ok
where I should download

**Comment by CryptoPunkFrens** [comment]
please send me the link

**Comment by maximedrn** [comment]
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/archive/refs/heads/master.zip

**Comment by CryptoPunkFrens** [comment]
thank you I will let you know letter

**Comment by CryptoPunkFrens** [comment]
hi
I have now another problem, I don't have "order" file
this is the error: \order.py': [Errno 2] No such file or directory

**Comment by CryptoPunkFrens** [comment]
ok I just add that file from previse version

**Comment by CryptoPunkFrens** [comment]
but now I can't log to opensea
![error](https://user-images.githubusercontent.com/108060093/198745416-95eab930-a143-46e6-8a2b-906af394475e.png)

**Comment by maximedrn** [comment]
In the `app/services/webdriver.py` file, can you remove lines from 65 to 67:

```python
if self.solver != 1 and self.wallet.recovery_phrase != '' and \
        self.wallet.password != '':  # Not manual solver.
    options.add_argument('--headless=chrome')  # Headless mode.
```

I think the issue comes from the headless on Chrome.
If it still not fix the issue, can you send me a video please?

**Comment by CryptoPunkFrens** [comment]
hi
how to open webdriver.py ?

**Comment by maximedrn** [comment]
With Notepad

**Comment by CryptoPunkFrens** [comment]
it's working but for some reasen generic.py only made file of 210 nfts instead 10.000

**Comment by CryptoPunkFrens** [comment]
now I have this problem. My googlr page is not going to create new item and Upload failed.
![image](https://user-images.githubusercontent.com/108060093/199425867-74449955-24b3-45e6-a40d-f691ddb5a726.png)

**Comment by maximedrn** [comment]
I think it's an error with OpenSea or your account. Check that there is no red message at the bottom of the creation page.
If there is, you may be uploading to a collection that you are not the creator or contributor.
