### ISSUE TITLE
MetaMask login

### ISSUE THREAD

**Issue by schwedyt** [maximedrn/opensea-automatic-bulk-upload-and-sale#395]
Having an issue logging in to metamask.  Keeps saying retrying...restarting. I've updated python version, selenium, webdriver

![Screenshot 2022-11-01 125459](https://user-images.githubusercontent.com/42848479/199379571-14c086a7-90ff-47d0-952d-15b479c26542.jpg)

**Comment by maximedrn** [comment]
Hi, I already tried to run the tool on Google Colab but it crashes at the OpenSea connection.
It seems you forgot something like Chromium or a screen emulator (like Xvf if I'm not wrong).
