### ISSUE TITLE
NFT cannot be deleted error

### ISSUE THREAD

**Issue by pickacrowd** [maximedrn/opensea-automatic-bulk-upload-and-sale#397]
I get NFT cannot be deleted error when I try to delete a collection. Can you please help me to solve this error?
![delete](https://user-images.githubusercontent.com/67396205/201330905-deffdc48-4855-4a78-bc8c-c4a7db064b58.jpg)

**Comment by maximedrn** [comment]
I have released a new version with a fix for this.
By the way, if you try to delete NFTs listed on Ethereum, it won't work.

**Comment by pickacrowd** [comment]
Issue solved. Thank you so much!
