### ISSUE TITLE
NFT cannot be deleted.

### ISSUE THREAD

**Issue by Lanza0635** [maximedrn/opensea-automatic-bulk-upload-and-sale#399]
I did the steps one by one.

I extracted it from the delete.py zip file.

I put it in the app-services-processess folder
 I ran it and chose option 4 but got an error.
![123](https://user-images.githubusercontent.com/113182796/201765501-eccfbb0c-af0e-4f1f-8236-25fd4878e9de.jpg)

**Comment by maximedrn** [comment]
Hi, can you send me the file used?

**Comment by Lanza0635** [comment]
I tried to use this file in the attached file.
[delete.py.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/10015647/delete.py.zip)

I think this file you want from me does not exist, if you say it is the last bot file I used, I used the last bot program on your page.

**Comment by maximedrn** [comment]
I mean the metadata file used

**Comment by Lanza0635** [comment]
Is this the file you want to try? This is the "data" folder in the file where I got the error.
[data.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/10015718/data.zip)

**Comment by maximedrn** [comment]
But which one of them did you use to delete?

**Comment by Lanza0635** [comment]
I threw 20k nft and wanted to delete it from the site, I downloaded the file and put it in "...\opensea-automatic-bulk-upload-and-sale-master\app\services\processes". When I run the bot and select delete nft, I got the error I sent you. Is there anything I did or missed?

**Comment by maximedrn** [comment]
Can you answer my question? Which file did you use among all the ones you sent me?

I only see the upload and dirty files. It seems that none of them contain 20k URLs.

If you want to delete NFTs and you don't have the URLs, you will need the [Collection Scraper](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Collection-Scraper). It will retrieve all the URLs from the collection, and you will be able to remove the NFTs using one of the files it generates.
