### ISSUE TITLE
No module named "colorama"

### ISSUE THREAD

**Issue by mullaghori** [maximedrn/opensea-automatic-bulk-upload-and-sale#400]
Hey sir, i have successfully generated the NFT's, and 
ISSUE#1 now with the uploader code, i have successfully installed all of the modules, but when i try with `python main.py` or with `python3 main.py`, there appears that "no module named colorama"
and the 
ISSUE#2 is that when i try with simply `main.py`, then after entering the metamask password and the phrase, the code is simply creating a csv file in the directory of the images, means nothing else it is not uploading the NFT not even launching the chrome browser.

![Untitled](https://user-images.githubusercontent.com/87578912/201914528-ed7664cf-1d08-48cb-8d08-621f785be78c.png)
![Untitled](https://user-images.githubusercontent.com/87578912/201914757-edc12877-f24a-443c-8eea-b03bb862d5e7.png)

**Comment by maximedrn** [comment]
`pip list` != `python -m pip list`
Try this command instead to install the packages:
```
python -m pip install -r requirements.txt
```
