### ISSUE TITLE
The collection URL cannot contain spaces

### ISSUE THREAD

**Issue by Illusiveman931** [maximedrn/opensea-automatic-bulk-upload-and-sale#401]
Hello, sorry for broken English

I was try upload mp3 file with preview image and I get this response in terminal

> NFT n°1/1:
Uploading NFT. Upload failed. The collection URL cannot contain spaces.
Uploading NFT. Upload failed. The collection URL cannot contain spaces.
Cannot save the metadata in a file.

Tested in Windows, Linux, Firefox, Chrome, MetaMask. In every metadata format with full URL and just collection name
 
[Metadata.zip](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/10015381/Metadata.zip)

**Comment by maximedrn** [comment]
What is the version of your tool?
On my side, it works perfectly.

**Comment by Illusiveman931** [comment]
thanks for the help, I tried to find in the documentation how to write this correctly and did not find it, but I found the wrong spelling in one of the old issues
