### ISSUE TITLE
Hidden NFT and ReCAPTCHA

### ISSUE THREAD

**Issue by schwedyt** [maximedrn/opensea-automatic-bulk-upload-and-sale#406]
Whenever I'm uploading NFTs they seem to be uploaded as hidden and I have to manually unhide them. Is there a setting I can change so they are uploaded as unhidden?

Using the ReCAPTCHA, I am able to login to MetaMask but the script keeps failing at logging in to OpenSea. Just repeats restarting and retrying.

**Comment by maximedrn** [comment]
> Whenever I'm uploading NFTs they seem to be uploaded as hidden and I have to manually unhide them. Is there a setting I can change so they are uploaded as unhidden?

What is the name of your NFTs? OpenSea's algorithm can hide NFTs if the name looks like a copy of NFTs from other collections.

> Using the ReCAPTCHA, I am able to login to MetaMask but the script keeps failing at logging in to OpenSea. Just repeats restarting and retrying.

How? This script does not affect the connection to OpenSea, it is only active at reCAPTCHA.

**Comment by schwedyt** [comment]
I was using generic names like IMG_6580 but I just tried one Carotid Stent and it was still hidden.

Attached is a screenshot when I use the ReCAPTCHA. When I use option 1 the manual solver, everything works ok. The Chrome screen opens and I can manually solve. But when I choose the bypasser option I can't login in. The Chrome window doesn't open so I don't know if that is normal or not. I'm relatively new with Python so let me know what you need to know to help me

![Screenshot 2022-12-03 174613](https://user-images.githubusercontent.com/42848479/205465252-b60208d1-89f0-4ea5-9477-3f8c798c9582.jpg)

**Comment by maximedrn** [comment]
Can you disable the headless mode following this:
- Open the `app/services/webdriver.py` file.
- Quote lines 65-67 as follows:
  
   ```python
   # From:
   if self.solver != 1 and self.wallet.recovery_phrase != '' and \
                self.wallet.password != '':  # Not manual solver.
            options.add_argument('--headless=chrome')  # Headless mode.
   # To:
   """if self.solver != 1 and self.wallet.recovery_phrase != '' and \
                self.wallet.password != '':  # Not manual solver.
            options.add_argument('--headless=chrome')  # Headless mode."""
   ```

Then restart the bot and try again, the window will appear on the screen and you will know what is wrong.

**Comment by schwedyt** [comment]
That worked! Thanks
