### ISSUE TITLE
Reserve price must be higher than 1 WETH and the price.

### ISSUE THREAD

**Issue by xerac318** [maximedrn/opensea-automatic-bulk-upload-and-sale#411]
![image](https://user-images.githubusercontent.com/103630790/215419471-203c5a19-47fc-4f01-acc4-5c4037e28b8a.png)

I'm having this issue.
Can you check what is my problem?

[6. xeracold (34D6) - Girls In The Box (POLY).xlsx](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/10533613/6.xeracold.34D6.-.Girls.In.The.Box.POLY.xlsx)

**Comment by maximedrn** [comment]
This problem means that you have set the reserve price too low. This reserve price depends on the default price and must be higher than 1 (W)ETH.

Looking at your file, this is not the case:
`["Sell to highest bidder", 0.002]`, `0.002` is less than `1` and equal to the price: `0.002` (must be higher).
Also make sure you put a `.` for your price, I see a `,`.
