### ISSUE TITLE
Inquiries about how to find duplicate listed NFTs.

### ISSUE THREAD

**Issue by thkpartners** [maximedrn/opensea-automatic-bulk-upload-and-sale#413]
I listed 10,000 of my NFTs on OpenSea.
However, not 10000 but 10001 were listed.
It seems that one is listed as duplicate.

1. Can I find a duplicate NFT I created?
2. Can I find NFTs that are not listed and are only created?

**Comment by maximedrn** [comment]
The Collection Scraper can find you the duplicate(s) but cannot separate listed and non-listed.

For 1 duplicate, I can tell you which one it is if you give me the URL of your collection.
