### ISSUE TITLE
Repeated "Oops, something went wrong" Error

### ISSUE THREAD

**Issue by saiyan1000** [maximedrn/opensea-automatic-bulk-upload-and-sale#417]
Hello. I'm getting this error in two information opensea. It keeps getting the same error. It is very difficult for them to load. Can you help me ?

![Error](https://user-images.githubusercontent.com/113181992/230226246-48cc32de-972a-43b5-8fd5-b4f45921abc4.png)

**Comment by maximedrn** [comment]
Hello, can you send me the file you selected for the upload/sale process?

**Comment by saiyan1000** [comment]
> Hello, can you send me the file you selected for the upload/sale process?


https://easyupload.io/fzm88b

**Comment by saiyan1000** [comment]
> 

thank you so much. the problem with opensea then.
