### ISSUE TITLE
Access Denied Error Code 1020 Opensea !!

### ISSUE THREAD

**Issue by saiyan100** [maximedrn/opensea-automatic-bulk-upload-and-sale#420]
While running the bot, it gives this error during the signature when first entering the metamask, and then the other one in the picture gives it wrong. Can you help me ?

I deleted the cookies. My ip address. My PC Mac address. I can't nft in any way.

Note: the same error occurred with me and a friend of mine.

https://ibb.co/fGLt22d

https://ibb.co/K56fnjC

**Comment by maximedrn** [comment]
Please install a VPN. I recommend you to use the free plan of ProtonVPN (or you can use another VPN).
You are blocked by Cloudflare but the tool blocks its requests and OpenSea generates this error.

**Comment by saiyan100** [comment]
Tried with the obtained vpn, the same mistake is given. What if I format the computer or is there a different method?

**Comment by Tiikou** [comment]
I can log in without bot and add items(same pc same ip) , but using bot I have the same issue

**Comment by Tiikou** [comment]
It can be random opensea error ,we should wait 24-48hrs may be it will disappear

**Comment by saiyan100** [comment]
yes like that. i tried to install it manually without bot, it happens normally without vpn. It doesn't happen when you throw it with a bot.

**Comment by maximedrn** [comment]
I am working on the implementation of the undetected_chromedriver module.
It works with it, the patch will be published as soon as possible.

**Comment by maximedrn** [comment]
Fix released!
Don't forget to reinstall the packages: `pip install -r requirements.txt`.
Let me know if you find errors in the script, I only tried one upload and sale and it worked.
