### ISSUE TITLE
How to sell NFTs after the upload?

### ISSUE THREAD

**Issue by hackcript** [maximedrn/opensea-automatic-bulk-upload-and-sale#422]

**Comment by maximedrn** [comment]
First of all, please open an issue and post a message... The title is not the message itself...

Second, this tool is the command line version, you are talking about OpenSea Workshop.

Finally, once you have uploaded your NFTs using the tool, you should have a sale file that has been generated: if it contains sale details, select it and run the Sale process; if it does not, complete it and do the previous case.
