### ISSUE TITLE
Question: Inquiry About Uploading NFT and Using OpenSea Workshop Tool

### ISSUE THREAD

**Issue by Abubakr22** [maximedrn/opensea-automatic-bulk-upload-and-sale#423]
Dear OpenSea Workshop Team,

I hope this email finds you well. I am reaching out to you because I am interested in uploading an NFT to the OpenSea marketplace and would like to use your tool for a fee of $20. I have heard great things about your service and I am excited to use it.

Before proceeding, I would like to clarify a few things. Firstly, I would like to know if there are any additional fees such as gas fees that I would need to pay for uploading & minting NFTs after $20 fee for using your tool. Secondly, I would like to confirm that thsi is an ERC 721 personal smart contract?

Thank you for your time and assistance. I look forward to hearing from you soon.

Best regards,

**Comment by maximedrn** [comment]
I already answered to your email
