### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by schwedyt** [maximedrn/opensea-automatic-bulk-upload-and-sale#430]
### Discussed in https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **hiqsociety** May 27, 2022</sup>
I get this error when I run the Collection Scraper:

![image](https://user-images.githubusercontent.com/91475935/174766762-e88484f5-da73-4f2c-a6d5-d3b3876f78c1.png)</div>

**Comment by schwedyt** [comment]
I tried the node index.js solution and I got another error. Cannot find module './opensea'. I tried re-installing node and restarting but still getting this issue

**Comment by maximedrn** [comment]
Hi, sorry for the late reply.
Please make sure all the files are present and that you ran `npm install` before running the Collection Scraper.
https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/wiki/Collection-Scraper
