### ISSUE TITLE
Duration (date format) issue

### ISSUE THREAD

**Issue by lucasredway** [maximedrn/opensea-automatic-bulk-upload-and-sale#67]
![Uploading Képernyőkép 2022-01-23 122437.jpg…]()

**Comment by maximedrn** [comment]
I do not see the picture

**Comment by lucasredway** [comment]
> I do not see the picture

![Képernyőkép 2022-01-23 122437](https://user-images.githubusercontent.com/56044384/150676678-f6a9af27-7ea3-4ce2-b106-b3356b0b9c7d.jpg)

**Comment by maximedrn** [comment]
Please do not open 2 issues for the same thing.
https://github.com/maximedrn/opensea_automatic_uploader/issues/66#issuecomment-1019464851

**Comment by lucasredway** [comment]
sorry.  Here is my json file: https://www.mediafire.com/file/q5d0tuq52gf3044/_metadata.json/file

**Comment by lucasredway** [comment]
> Please do not open 2 issues for the same thing. [#66 (comment)](https://github.com/maximedrn/opensea_automatic_uploader/issues/66#issuecomment-1019464851)

sorry. Here is my json file: https://www.mediafire.com/file/q5d0tuq52gf3044/_metadata.json/file

**Comment by maximedrn** [comment]
Your JSON file is correct. Did you select "upload only"?
You are using Python 3.10 and you get a Selenium exception that I don't know about. If it really doesn't work, try uninstalling Python and installing the 3.9.9 version I'm currently using. Python 3.10 is very bad when trying to ensure compatibility, especially with a module like Selenium that can be very quickly unstable.

**Comment by lucasredway** [comment]
> Your JSON file is correct. Did you select "upload only"? You are using Python 3.10 and you get a Selenium exception that I don't know about. If it really doesn't work, try uninstalling Python and installing the 3.9.9 version I'm currently using. Python 3.10 is very bad when trying to ensure compatibility, especially with a module like Selenium that can be very quickly unstable.

Updatet, but same error. Please show video:  https://www.youtube.com/watch?v=MYwT_5V2mNo

**Comment by maximedrn** [comment]
Is your path correct ?
``"file_path": "C:/generate-nfts-main/biuld/images/1.png",``
should be ``"file_path": "C:/generate-nfts-main/build/images/1.png",``?

**Comment by maximedrn** [comment]
By the way I upload a version that show errors. So please show me the error with this new version.

**Comment by lucasredway** [comment]
> 



> Is your path correct ? `"file_path": "C:/generate-nfts-main/biuld/images/1.png",` should be `"file_path": "C:/generate-nfts-main/build/images/1.png",`?

Yes correct!!

**Comment by lucasredway** [comment]
> By the way I upload a version that show errors. So please show me the error with this new version.

downloaded but getting this error: An error occured. Message: File doesn't exist or path is incorrect. but my path is good. please view in video:  https://www.youtube.com/watch?v=ul_7-KsH0X4

**Comment by maximedrn** [comment]
"biuld" is correct in your path?

**Comment by lucasredway** [comment]
> "biuld" is correct in your path?

omg thanks :DDD

**Comment by maximedrn** [comment]
Bot never lies ahah 👍

**Comment by lucasredway** [comment]
> Bot never lies ahah 👍

New problem. After upload inserted 1 ethereum price. But my metadata.json file price is 0.0005. Why not inserted this value?

**Comment by maximedrn** [comment]
This is correct:
```json
      "file_path": "C:/generate-nfts-main/biuld/images/1.png",
      "nft_name": "Crypto Mario #1",
      "external_link": "https://www.google.com/",
      "description": "Crypto Mario Collection",
      "collection": "Crypto Mario",
      "properties": [
        {
          "type": "Background",
          "name": "3"
        },
        {
          "type": "Body",
          "name": "White"
        },
        {
          "type": "Button",
          "name": "Purple"
        },
        {
          "type": "Eye",
          "name": "Black"
        },
        {
          "type": "Hair",
          "name": "Brown"
        },
        {
          "type": "Hat",
          "name": "Blue"
        },
        {
          "type": "Mustache",
          "name": "Green"
        },
        {
          "type": "Pants",
          "name": "Purple"
        },
        {
          "type": "Shoes",
          "name": "Black"
        },
        {
          "type": "T-Shirt",
          "name": "Green"
        }
      ],
      "levels": [],
      "stats": [],
      "unlockable_content": [],
      "explicit_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Polygon",
```
But this is not:
```json
    "price": 0.005,
    "quantity": 1,
    "dna": "362212b635d21a556446821a254529648dce5eb0",
    "edition": 1,
    "date": 1642772373143,
    "compiler": "HashLips Art Engine"
```
In my code, price is the 14th element. In yours the 14th is the quantity which is equal to 1.
Please follow this format for the sale part:
```json
    "sale_type": "",
    "price": 0.0005,
    "method": "",
    "duration": [
        "25-01-2022 14:20", "18-02-2022 17:40"
    ],
    "specific_buyer": "",
    "quantity": 1
```

**Comment by lucasredway** [comment]
> This is correct:
> 
> ```json
>       "file_path": "C:/generate-nfts-main/biuld/images/1.png",
>       "nft_name": "Crypto Mario #1",
>       "external_link": "https://www.google.com/",
>       "description": "Crypto Mario Collection",
>       "collection": "Crypto Mario",
>       "properties": [
>         {
>           "type": "Background",
>           "name": "3"
>         },
>         {
>           "type": "Body",
>           "name": "White"
>         },
>         {
>           "type": "Button",
>           "name": "Purple"
>         },
>         {
>           "type": "Eye",
>           "name": "Black"
>         },
>         {
>           "type": "Hair",
>           "name": "Brown"
>         },
>         {
>           "type": "Hat",
>           "name": "Blue"
>         },
>         {
>           "type": "Mustache",
>           "name": "Green"
>         },
>         {
>           "type": "Pants",
>           "name": "Purple"
>         },
>         {
>           "type": "Shoes",
>           "name": "Black"
>         },
>         {
>           "type": "T-Shirt",
>           "name": "Green"
>         }
>       ],
>       "levels": [],
>       "stats": [],
>       "unlockable_content": [],
>       "explicit_and_sensitive_content": false,
>       "supply": 1,
>       "blockchain": "Polygon",
> ```
> 
> But this is not:
> 
> ```json
>     "price": 0.005,
>     "quantity": 1,
>     "dna": "362212b635d21a556446821a254529648dce5eb0",
>     "edition": 1,
>     "date": 1642772373143,
>     "compiler": "HashLips Art Engine"
> ```
> 
> In my code, price is the 14th element. In yours the 14th is the quantity which is equal to 1. Please follow this format for the sale part:
> 
> ```json
>     "sale_type": "",
>     "price": 0.0005,
>     "method": "",
>     "duration": [
>         "25-01-2022 14:20", "18-02-2022 17:40"
>     ],
>     "specific_buyer": "",
>     "quantity": 1
> ```

Price is good, but the date is not working. please view my video: https://www.youtube.com/watch?v=QLD2cyk8X7s

**Comment by maximedrn** [comment]
I see that the date format is different in your country. I uploaded a version where the default language of ChromeDriver is English. Now the date is set correctly. I'm sorry for that, I live in Europe and have the European date format, not the American one. :/

**Comment by maximedrn** [comment]
You should have a duration pop up like this with this format of date and time.
24h format is automatically changed to 12h by OpenSea.

![Sans titre 1](https://user-images.githubusercontent.com/91475935/150691708-1783b192-f0eb-46bd-8a35-b2164b5db812.png)

**Comment by lucasredway** [comment]
> You should have a duration pop up like this with this format of date and time. 24h format is automatically changed to 12h by OpenSea.
> 
> ![Sans titre 1](https://user-images.githubusercontent.com/91475935/150691708-1783b192-f0eb-46bd-8a35-b2164b5db812.png)

thank you working

**Comment by stackzwolle** [comment]
hi 
im getting crazy here. everything works 1 week works, 1 month works but when i input date in doesnt work.
opensea date format is dd/mm/yy

and this my .json file date format

    duration: [
      "06-02-2022 02:40", "05-08-2022 02:40"
  ],

**Comment by maximedrn** [comment]
Send me a video, I need to know when the bot crashes.

**Comment by maximedrn** [comment]
> hi im getting crazy here. everything works 1 week works, 1 month works but when i input date in doesnt work. opensea date format is dd/mm/yy
> 
> and this my .json file date format
> 
> ```
> duration: [
>   "06-02-2022 02:40", "05-08-2022 02:40"
> ],
> ```

I tried with Polygon and Ethereum (Fixed Price & Timed Auction), 1 and 1+ supplies. It works great :/
Try using:
```json
"duration": ["06-02-2022 02:40", "05-08-2022 02:40"],
```
(Change the date).

**Comment by stackzwolle** [comment]
Omg slept at 5am. 
well thanks for reply. I nearly read all the issues :) 
Been changing time a lot of times so tired I stop then woke up do it again and things just fine maybe cos opensea have some maintenance going on. And I found out you can set start date within a week only. 

Thanks for the code
Great job cheers.
