### ISSUE TITLE
Cannot Upload 

### ISSUE THREAD

**Issue by calvinlinardy** [maximedrn/opensea-automatic-bulk-upload-and-sale#68]
![image](https://user-images.githubusercontent.com/39586129/150677885-08d99594-204c-4930-b0ac-9fc0d3e3ea20.png)
![image](https://user-images.githubusercontent.com/39586129/150677911-f7488eca-bedd-4492-8d01-2d0f2d65da77.png)
Please help

**Comment by maximedrn** [comment]
See this: https://github.com/maximedrn/opensea_automatic_uploader#known-issues-and-important-things-to-know

**Comment by calvinlinardy** [comment]
thanks! now it worked, but the upload failed.
I chose upload and sale and you can see my json file above
![image](https://user-images.githubusercontent.com/39586129/150679765-8dbf3365-6ecd-45d6-b47e-4a7e0a46eebc.png)

**Comment by maximedrn** [comment]
See what "Upload an Sale" requires: https://github.com/maximedrn/opensea_automatic_uploader#upload-and-sale
Example for JSON: https://github.com/maximedrn/opensea_automatic_uploader/blob/master/data/json_structure_upload_and_sale.json

**Comment by calvinlinardy** [comment]
![image](https://user-images.githubusercontent.com/39586129/150680072-2c789ed5-159d-4a87-9e90-7af8bd9306a9.png)
Now I have changed the json requirements and it still didn't work, does the order matter?

**Comment by calvinlinardy** [comment]
Or is there anything I did wrong?

**Comment by maximedrn** [comment]
Your file is correct. Now if you have an error please send me a video :)

**Comment by calvinlinardy** [comment]
I have solved the NFT upload problem, but now the issue is the sales got canceled, and I couldn't figure out anything is wrong in my json file
![image](https://user-images.githubusercontent.com/39586129/150680964-fcf5408a-7f06-48d5-b6d8-680e38b482a8.png)
![image](https://user-images.githubusercontent.com/39586129/150681234-6e142138-1ae0-48c1-b8bc-7bc2d0d5ef1d.png)

**Comment by maximedrn** [comment]
I publish a version that show errors can you please copy paste the content from the main.py and try to run this new script. It should print the error. Your file is correct don't worry.

**Comment by calvinlinardy** [comment]
![image](https://user-images.githubusercontent.com/39586129/150681903-2471ba05-1ac5-48dc-b9d9-f1870cfad2bc.png)
I guess the problem is in the duration, did I input the wrong format?

**Comment by maximedrn** [comment]
Add this at lines 159-160:
```python
self.nft_data_list = nft_data  # For development.
print(self.nft_data_list)
```
You will see your data printed. Send me what it is.

**Comment by calvinlinardy** [comment]
![image](https://user-images.githubusercontent.com/39586129/150687637-ec9f82fd-4dbe-4649-8fc6-78804fcc3b07.png)

**Comment by maximedrn** [comment]
Oh! Quantity should be the last element of each data. That why you get this error.
![image](https://user-images.githubusercontent.com/39586129/150680964-fcf5408a-7f06-48d5-b6d8-680e38b482a8.png)
Remove the quantity and add it after the specific buyer.

**Comment by calvinlinardy** [comment]
It worked! But, again there is another problem
![image](https://user-images.githubusercontent.com/39586129/150690311-f77259d8-3970-4d72-a6bf-a63b836b58b1.png)

**Comment by maximedrn** [comment]
Send me the metadata of the NFTs n°4 and 5.

**Comment by calvinlinardy** [comment]
![image](https://user-images.githubusercontent.com/39586129/150690741-89c098d0-9043-49bc-931f-ed9b6c1110a7.png)
![image](https://user-images.githubusercontent.com/39586129/150690745-9c180773-b500-4aff-bd38-9c69ca43b4ce.png)

**Comment by maximedrn** [comment]
When does the error occur? After sending the image, the collection?

**Comment by calvinlinardy** [comment]
after the 3rd NFT's sales, the browser froze and didn't do anything

**Comment by maximedrn** [comment]
Be sure to let the browser in foreground.

**Comment by calvinlinardy** [comment]
It was in the foreground and I didn't even use the PC, it was like a pattern happened after 1-2 sales and it skipped the next one
![image](https://user-images.githubusercontent.com/39586129/150691845-067ddd84-d20c-42d4-9d8b-d4d1613f9228.png)

**Comment by maximedrn** [comment]
What is your configuration?
I know one or two out of 1000 NFTs failed to upload, but not that many. And I uploaded them with a 4GB / i3 6th PC.

**Comment by calvinlinardy** [comment]
do you mean my PC specs? 
i7 10th 16GB RAM RTX 2070

**Comment by maximedrn** [comment]
Your PC is enough powerful.
Can you send me a video of the upload like 5 NFTs. This is very strange and it only happens during the sale.

**Comment by calvinlinardy** [comment]
I can record tomorrow, but I've tried upload only and it worked fine
![image](https://user-images.githubusercontent.com/39586129/150694270-2f408e16-6a98-47cd-a86d-7249db6b07d9.png)

**Comment by maximedrn** [comment]
Yes, something wrong during the sale but I don't know what.

**Comment by AndroidTutorialsyt** [comment]
All these errors occurs because of duration mistake

**Comment by Ugijago** [comment]
happen to mee when bot try to sell it stuck in drop down duration menu, then just skip to next nft upload

**Comment by maximedrn** [comment]
> happen to mee when bot try to sell it stuck in drop down duration menu, then just skip to next nft upload

Can you specify for which type of sale?
Polygon or Ethereum, 1 supply or 1+ supplies?
I will take a look

**Comment by Ugijago** [comment]
> > happen to mee when bot try to sell it stuck in drop down duration menu, then just skip to next nft upload
> 
> Can you specify for which type of sale? Polygon or Ethereum, 1 supply or 1+ supplies? I will take a look

polygon only 1 , bot open duration calendar menu then just chilling then no sale at all ordinale something... then continue to upload next nft. btw i set to 1 month its okay before, now eror weird only failed in sale the nft

i want continue upload my nft after opensea remove limit please fix 😭 never finish my 10k upload

**Comment by Ugijago** [comment]
after update chrome to 98 and chrme driver now work flawlessly again 🙄

**Comment by maximedrn** [comment]
I tried it on my side and it works. Selenium is buggy at some point.
I recommend you to have the chromedriver and the Selenium module at the last version.

https://user-images.githubusercontent.com/91475935/152636766-f2aa0b23-e4a4-484e-b9e1-49800ae201e6.mp4

**Comment by maximedrn** [comment]
I close this issue. @calvinlinardy please reopen it if you have encountered the same problem.
