### ISSUE TITLE
cannot login opensea ddsos protection 

### ISSUE THREAD

**Issue by Ugijago** [maximedrn/opensea-automatic-bulk-upload-and-sale#70]
now bot stuck with ddos protection page
![image](https://user-images.githubusercontent.com/97956998/150707022-e26e590e-9994-4d11-8f94-ddb03ab3a346.png)

**Comment by nvanrysseghem** [comment]
Me as well...hopefully less traffic will solve this issue. Will try again in a few hours.

**Comment by maximedrn** [comment]
> Me as well...hopefully less traffic will solve this issue. Will try again in a few hours.

You are right, OpenSea is protected by Cloudflare when there is massive traffic.
