### ISSUE TITLE
NFT sale cancelled

### ISSUE THREAD

**Issue by mounir82** [maximedrn/opensea-automatic-bulk-upload-and-sale#75]
Hi everyone. i get this message  NFT sale cancelled. Message: You need to make a deposit before proceeding to listing of your NFTs. I have already 29 matic on my wallet. the script upload the picture and stop in the price. Thanks in advance for help. My metadata is

{"nft":[{"file_path":"D:/mynft/test/10k/1.jpg","nft_name":"my NFT #1","external_link":"https://opensea.io/binol","description":"nft #1","collection":"My NFTs Collection","properties":[{"type":"Type","name":"Gold"},{"type":"Color","name":"Yellow"},{"type":"Array","name":"1-10k"}],"levels":[],"stats":[],"unlockable_content":[],"expliciet_and_sensitive_content":false,"supply":1,"blockchain":"Polygon","price":0.043,"quantity":1,"dna":"d4dfa23f393bc57ab7511b37cbb2409d8004cd53","edition":1,"date":1643273678829,"compiler":"My nft"}]}

**Comment by mounir82** [comment]
Strange. it ss working now. But only the price stay in 1 eth.

**Comment by maximedrn** [comment]
Please follow the data structure for upload and sale. Some elements are missing (sale type, etc).

**Comment by rosegreen2090** [comment]
please my everything is working fine but my price stays in 1 eth, please how can i change it to 0.007 eth. thanks for this wonderful project. i await your response.

**Comment by maximedrn** [comment]
Here what you need to have in your metadata file. Your upload part is correct but not the sale one.

```json
{
  "nft": [
    {
      "file_path": "D:/mynft/test/10k/1.jpg",
      "nft_name": "my NFT #1",
      "external_link": "https://opensea.io/binol",
      "description": "nft #1",
      "collection": "My NFTs Collection",
      "properties": [
        {
          "type": "Type",
          "name": "Gold"
        },
        {
          "type": "Color",
          "name": "Yellow"
        },
        {
          "type": "Array",
          "name": "1-10k"
        }
      ],
      "levels": [],
      "stats": [],
      "unlockable_content": [],
      "expliciet_and_sensitive_content": false,
      "supply": 1,
      "blockchain": "Polygon",
      "sale_type": "", // Required even if empty.
      "price": 0.043,
      "method": "", // Required even if empty.
      "duration":  ["", ""], // Required even if empty.
      "specific_buyer": "", // Required even if empty.
      "quantity": 1,
    }
  ]
}
```

**Comment by rosegreen2090** [comment]
thanks for your quick response. this is what i have now. is this ok? or i have to still add? lastly must it be in the order as you have sent? thanks
"levels": [],
    "stats": [],
    "unlockable_content": [],
    "explicit_and_sensitive_content": false,
    "supply": 1,
    "blockchain": "Polygon",
    "sale_type": "",
    "price": 0.007,
    "method": "",
    "duration": [
      "27-01-2022 15:10",
      "30-04-2022 15:00"
    ],
    "quantity": 1,
    "specific_buyer": "",
    "dna": "7ced55b418494bf050ecac9a076cd1b0751511fa",
    "edition": 1,
    "date": 1643301476693,

**Comment by maximedrn** [comment]
That's good :) dna, edit and date are useless but you can leave them as it doesn't change anything.
And yes, it has to be in that order because my code takes the data iteratively and not with their name.

**Comment by mounir82** [comment]
> Here what you need to have in your metadata file. Your upload part is correct but not the sale one.
> 
> ```json
> {
>   "nft": [
>     {
>       "file_path": "D:/mynft/test/10k/1.jpg",
>       "nft_name": "my NFT #1",
>       "external_link": "https://opensea.io/binol",
>       "description": "nft #1",
>       "collection": "My NFTs Collection",
>       "properties": [
>         {
>           "type": "Type",
>           "name": "Gold"
>         },
>         {
>           "type": "Color",
>           "name": "Yellow"
>         },
>         {
>           "type": "Array",
>           "name": "1-10k"
>         }
>       ],
>       "levels": [],
>       "stats": [],
>       "unlockable_content": [],
>       "expliciet_and_sensitive_content": false,
>       "supply": 1,
>       "blockchain": "Polygon",
>       "sale_type": "", // Required even if empty.
>       "price": 0.043,
>       "method": "", // Required even if empty.
>       "duration":  ["", ""], // Required even if empty.
>       "specific_buyer": "", // Required even if empty.
>       "quantity": 1,
>     }
>   ]
> }
> ```

merci mon ami .i'm going to try this. I saw on twitter  opensea allows only 50 item for upload.  I hope that you make one for rarible marketplace. I promise you if i earn money from my collection i will give you 10k euro.

**Comment by maximedrn** [comment]
OpenSea has backtracked, as you can see here https://twitter.com/opensea/status/1486843201352716289.
The limit has been removed. 

I'm working on a Rarible bot, but I want to make a paid version of it first that will offer more tools (obviously I will continue to provide patches for the free version).

I wish you the best for your art project :)
