### ISSUE TITLE
Problem when the bot enter the price

### ISSUE THREAD

**Issue by WinCoins2** [maximedrn/opensea-automatic-bulk-upload-and-sale#79]
Hi everyone! The code is perfect but I have a little problem.

When I start the robot to publish and sell, everything works except that at the time of selling, when it enters the price, it puts 1 ETH instead of the price I wanted to put in the base and that is in the metadata file.
I need help please, and if possible, adjust the code because I can't change the metadata file too much because it contains 10000 NFTs. Thanks a lot!
Here is the metadata file:
[metadata.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/7970664/metadata.txt)

**Comment by WinCoins2** [comment]
[metadata.txt](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/files/7970598/metadata.txt)

**Comment by maximedrn** [comment]
Hello, you must follow the format indicated [here](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/blob/master/data/json_structure_upload_and_sale.json).
