### ISSUE TITLE
nft genorator + meta data ? 

### ISSUE THREAD

**Issue by omowanai** [maximedrn/opensea-automatic-bulk-upload-and-sale#81]
what nft generator did you use to produce the nfts with proper meta data ? or am i not understanding how this up loader reads/uses metadata am i missing something ? , i used https://github.com/Jon-Becker/nft-generator-py  to generate my collection with metadata and gives metedata = 

{
    "image": "./images/2.png",
    "tokenId": 2,
    "name": "NFT #0002",
    "description": " NFT Collection.",
    "attributes": [
        {
            "trait_type": "Background",
            "value": "blue"
        },
        {
            "trait_type": "Fur",
            "value": "green fur"
        },
        {
            "trait_type": "Coat",
            "value": "coulds"
        },
        {
            "trait_type": "Tail",
            "value": "green"
        },
        {
            "trait_type": "Shoes",
            "value": "tan feet"
        },
        {
            "trait_type": "Ears",
            "value": "charcoal_green"
        },
        {
            "trait_type": "Tattoos",
            "value": "3,7"
        },
        {
            "trait_type": "Shirt",
            "value": "none"
        },
        {
            "trait_type": "Whiskers",
            "value": "grey"
        },
        {
            "trait_type": "Eyes",
            "value": "trippin"
        },
        {
            "trait_type": "Mouth",
            "value": "red"
        },
        {
            "trait_type": "Items",
            "value": "none"
        },
        {
            "trait_type": "Hats",
            "value": "pink"
        },
        {
            "trait_type": "Earings",
            "value": "1 red"
        },
        {
            "trait_type": "Alpha",
            "value": "2"
        },
        {
            "trait_type": "Zeta",
            "value": "2"
        }
    ]
}

**Comment by omowanai** [comment]
what do we use to get the supported format ? can you please explain what/how we need to do to get metadata into the proper format? i see how i needs to be, but how do we get it there? is it done inside of the the uploader? is it when we are creating the nfts ? do we have to edit the nfts json files?  if ou could give an explanation that would be great! thanks much

**Comment by omowanai** [comment]
so i have edited my nft generator to produce proper metadata format, but im trying to test it to make sure everything working right but im getting error 

Uploading NFT n°1/4. An error occured. Message: File doesn't exist or path is incorrect.

Uploading NFT n°2/4. An error occured. Message: File doesn't exist or path is incorrect.

Uploading NFT n°3/4. An error occured. Message: File doesn't exist or path is incorrect.

Uploading NFT n°4/4. An error occured. Message: File doesn't exist or path is incorrect.

 i have what i tihnk is correct file path to where the nft png are stored, is there something i am missing ?

**Comment by omowanai** [comment]
{
    "file_path": "/home/teleporsche/Desktop/nftgentool/images/2.png",
    "nft_name": "nft#0002",
    "external_link": "officcial.nft",
    "tokenId": 2,
    "description": " NFT Collection.",
    "collection": "nft ",
    "properties": [
        {
            "type": "Background",
            "name": "grey"
        },
        {
            "type": "Fur",
            "name": "blue fur"
        },
        {
            "type": "Coat",
            "name": "purple"
        },
        {
            "type": "Tail",
            "name": "burgandy"
        },
        {
            "type": "Shoes",
            "name": "red"
        },
        {
            "type": "Ears",
            "name": "red_blue"
        },
        {
            "type": "Tattoos",
            "name": "none"
        },
        {
            "type": "Shirt",
            "name": "none"
        },
        {
            "type": "Whiskers",
            "name": "grey"
        },
        {
            "type": "Eyes",
            "name": "sleepy left"
        },
        {
            "type": "Mouth",
            "name": "white  braces"
        },
        {
            "type": "Items",
            "name": "cucumber"
        },
        {
            "type": "Hats",
            "name": "none"
        },
        {
            "type": "Earings",
            "name": "4 blue"
        },
        {
            "type": "Alpha",
            "name": "3"
        },
        {
            "type": "Zeta",
            "name": "6"
        }
    ],
    "levels": "",
    "stats": "",
    "unlockable_content": "false",
    "explicit_and_sensitive_content": "false",
    "supply": "1",
    "blockchain": "polygon"
}

**Comment by omowanai** [comment]
im running ubuntu 20 so im not sure how the file path should be written, from what i looked uo its how it should be, but idk if it matters the location of the file ? any help would be appreciated

**Comment by maximedrn** [comment]
I don't remember the architecture of the file tree in Linux. I recommend you to put the file containing your NFTs in the same directory as the bot. So you just have to write the path like this : "nft_file/nft_0000.png". In addition you must remove the "tokenId".

**Comment by maximedrn** [comment]
Unlockable content and explicit & sensitive content must be boolean (true or false - not "true" or "false"), the supply must be an integer, so you should have 1 and not "1".

**Comment by stackzwolle** [comment]
which nft generator i can use? or should i edit the generator itself?

**Comment by maximedrn** [comment]
For now, you must create and complete the metadata file manually.

**Comment by omowanai** [comment]
thanks for getting back to me, does the bot read the all_items.json or does it read each of the individual json? im asking because i was able to edit my nft genorator to produce right format in individual files but the all_files.json didnt get changed,   i can just edit things by copy/paste others, or guess and try things till it works cuz idk what im doing, so if it could get it to read from individual files that would be great thanks again!

**Comment by omowanai** [comment]
or maybe could you point me in the right direction for how to compile the individual json files into one ? thanks

**Comment by maximedrn** [comment]
Your NFT generator generates one file per NFT?

**Comment by omowanai** [comment]
it does both, it generates a idividual json for each nft, and a all-objects.json 
right now im trying to figure out how to edit the all-objects.json , as of right now the all-objects.json only list the attributes and nft number, nothing els so im trying to figure out how to make it fill in rest of metadata

**Comment by maximedrn** [comment]
Follow the pattern of the file that is compatible with the bot:
```json
{
     "nft": [
       {
         "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": [
           {
             "type": "",
             "name": ""
           },
           {
             "type": "",
             "name": ""
           }
         ],
         "levels": [
           {
             "name": "",
             "from": 0,
             "to": 0
           },
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "stats": [
           {
             "name": "",
             "from": 0,
             "to": 0
           },
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "unlockable_content": [true, ""],
         "explicit_and_sensitive_content": false,
         "supply": 1,
         "blockchain": "",
         "sale_type": "",
         "price": 0,
         "method": ["", 0],
         "duration": [ "", ""],
         "specific_buyer": [true, ""],
         "quantity": 1
       },
       {
         "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": [
           {
             "type": "",
             "name": ""
           },
           {
             "type": "",
             "name": ""
           }
         ],
         "levels": [
           {
             "name": "",
             "from": 0,
             "to": 0
           },
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "stats": [
           {
             "name": "",
             "from": 0,
             "to": 0
           },
           {
             "name": "",
             "from": 0,
             "to": 0
           }
         ],
         "unlockable_content": [true, ""],
         "explicit_and_sensitive_content": false,
         "supply": 1,
         "blockchain": "",
         "sale_type": "",
         "price": 0,
         "method": ["", 0],
         "duration": [ "", ""],
         "specific_buyer": [true, ""],
         "quantity": 1
       },
     ]
   }
```

**Comment by maximedrn** [comment]
The NFT generator you used is incomplete. I don't know of any generator that gives the maximum information.
I am building one that is compatible with my robot but it takes time, so for now the creation of metadata files is entirely manual.

**Comment by omowanai** [comment]
yeah im assuming theres something missing, im not sure what it is as i dont know what ide be looking for, but my all-objects makes this output format[
    {
        "Background": "orange",
        "Fur": "blue fur",
        "Coat": "gold",
        "Tail": "red",
        "Shoes": "black",
        "Ears": "brown_green",
        "Tattoos": "2,3,5",
        "Shirt": "grey",
        "Whiskers": "grey",
        "Eyes": "regular",
        "Mouth": "drool",
        "Items": "tnt",
        "Hats": "green",
        "Earings": "none",
        "Alpha": "4",
        "Zeta": "7",
        "tokenId": 1
    },
    {
        "Background": "green",
        "Fur": "charcoal fur",
        "Coat": "charcoal",
        "Tail": "blue",
        "Shoes": "tan feet",
        "Ears": "red_pink",
        "Tattoos": "3,7",
        "Shirt": "retro green",
        "Whiskers": "blue",
        "Eyes": "trippin",
        "Mouth": "ohh",
        "Items": "cucumber",
        "Hats": "none",
        "Earings": "1 gold",
        "Alpha": "6",
        "Zeta": "6",
        "tokenId": 2
    },

**Comment by omowanai** [comment]
and ive gotten the individual json files to output like this, 

{
    "nft": [
        {
            "file_path": "./images/1.png",
            "nft_name": "PolyRabbit #0001",
            "external_link": "polyrabbitsofficcial.nft",
            "description": "Poly Rabbits Official NFT Collection.",
            "collection": "poly rabbits official",
            "properties": [
                {
                    "type": "Background",
                    "name": "orange"
                },
                {
                    "type": "Fur",
                    "name": "blue fur"
                },
                {
                    "type": "Coat",
                    "name": "gold"
                },
                {
                    "type": "Tail",
                    "name": "red"
                },
                {
                    "type": "Shoes",
                    "name": "black"
                },
                {
                    "type": "Ears",
                    "name": "brown_green"
                },
                {
                    "type": "Tattoos",
                    "name": "2,3,5"
                },
                {
                    "type": "Shirt",
                    "name": "grey"
                },
                {
                    "type": "Whiskers",
                    "name": "grey"
                },
                {
                    "type": "Eyes",
                    "name": "regular"
                },
                {
                    "type": "Mouth",
                    "name": "drool"
                },
                {
                    "type": "Items",
                    "name": "tnt"
                },
                {
                    "type": "Hats",
                    "name": "green"
                },
                {
                    "type": "Earings",
                    "name": "none"
                },
                {
                    "type": "Alpha",
                    "name": "4"
                },
                {
                    "type": "Zeta",
                    "name": "7"
                }
            ],
            "levels": "",
            "stats": "",
            "unlockable_content": false,
            "explicit_and_sensitive_content": false,
            "supply": 1,
            "blockchain": "polygon"
        }
    ]
}

**Comment by omowanai** [comment]
im realy close, just need to get proper formatting on all-objects.json output,, but thank you for answering my questions! i think im on the home stretch at this point

**Comment by stackzwolle** [comment]
hi
how to input or what format the date here?

"duration": [ "", ""],

thanks

**Comment by stackzwolle** [comment]
> hi how to input or what format the date here?
> 
> "duration": [ "", ""],
> 
> thanks

and also what is this     "method": ["", 0],

**Comment by maximedrn** [comment]
Follow this link: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale#upload-and-sale
The table explains everything for each file and metadata :)
