### ISSUE TITLE
Blockchain is unknown or badly written.

### ISSUE THREAD

**Issue by efinskiy** [maximedrn/opensea-automatic-bulk-upload-and-sale#83]
Hello! Whats wrong with my config? blockchain writen correctly, but on stage of choosing blockchain script frozing ang goes to error

![image](https://user-images.githubusercontent.com/20232815/152330112-78ca1d11-29be-43ea-97d2-e7634533d855.png)
![image](https://user-images.githubusercontent.com/20232815/152330228-d0045053-83a7-4de6-bec8-d04c3ebd55e9.png)

**Comment by efinskiy** [comment]
Okey, i checked your code, and found what json elements positions are hardcoded 
`self.blockchain: str = str(nft_data[11]).capitalize()`  
i rebuild my config to yours like structrure and still nft_data[11] equals json price element
![image](https://user-images.githubusercontent.com/20232815/152334937-f5084cba-7ec9-4ebb-87bc-0434ceb8ccd6.png)

**Comment by efinskiy** [comment]
i changed in my local copy `self.blockchain: str = str(nft_data[11]).capitalize()` to `self.blockchain: str = str(nft_data[9]).capitalize()` and upload successfully started

**Comment by maximedrn** [comment]
Hi! That's because the blockchain is after the supply. My code takes the element iteratively and not with its data type.
As you can see here:
```json
          "file_path": "",
         "nft_name": "",
         "external_link": "",
         "description": "",
         "collection": "",
         "properties": "",
         "levels": "",
         "stats": "",
         "unlockable_content": "",
         "explicit_and_sensitive_content": "",
         "supply": "",
         "blockchain": "",
         "sale_type": "",
         "price": 0,
         "method": "",
         "duration": "",
         "specific_buyer": "",
         "quantity": ""
```
