### ISSUE TITLE
Unlock currency step

### ISSUE THREAD

**Issue by anjarsuryo** [maximedrn/opensea-automatic-bulk-upload-and-sale#87]
Process stop when filling duration. I do some check on Opensea that max duration is 1 Month. I Change the xlsx data on "Duration" Column from 6 Months to 1 Month. But still i got stuck on the setting up the duration. Can anybody give me the solution...

**Comment by maximedrn** [comment]
Send me an excerpt of your file.

**Comment by anjarsuryo** [comment]
Done..it solved..
but new problem come after that...after Listing Button, precisely when Unlock Currency step...the script stop working...

**Comment by anjarsuryo** [comment]
> Done..it solved.. but new problem come after that...after Listing Button, precisely when Unlock Currency step...the script stop working...

Should I Open new Issue? @maximedrn

**Comment by maximedrn** [comment]
You have to unlock the currency manually for the first time. After that, you will not have this step anymore.

**Comment by anjarsuryo** [comment]
> You have to unlock the currency manually for the first time. After that, you will not have this step anymore.

That's work bro...thanks a lot...

the problem solved
