### ISSUE TITLE
not gererating csv data 

### ISSUE THREAD

**Issue by omowanai** [maximedrn/opensea-automatic-bulk-upload-and-sale#89]
im trying to upload to opensea im doing tests, im doing upload only and i have noticed its not populating the generated .csv used to re list the nfts,  any ideas? thanks a lot!!

**Comment by maximedrn** [comment]
Can you explain your situation precisely?

**Comment by omowanai** [comment]
sorry for late reply, i thought for some reason the bot created a csv file of what it uploaded, but i dont think thats the case, ?

**Comment by maximedrn** [comment]
The CSV file is generated for sale. If you only upload your NFTs to OpenSea, you will surely sell them in the future. So my bot creates a file that you can fill in (it only contains the NFT's URL, its blockchain and its supply number).
