### ISSUE TITLE
you need to make deposit error while putting on sale on polygon network

### ISSUE THREAD

**Issue by tuncaym** [maximedrn/opensea-automatic-bulk-upload-and-sale#91]
I started to get this error while putting on sale:
Uploading NFT n°1/832. NFT uploaded.
Sale of the NFT n°1/832. NFT sale cancelled. Message: You need to make a deposit before proceeding to listing of your NFTs.

I can manually put same item on sale without any fee. I get error only with script

**Comment by maximedrn** [comment]
Send me an excerpt of your metadata file.

**Comment by maximedrn** [comment]
Closed for inactivity.
