### ISSUE TITLE
Unlockable Content

### ISSUE THREAD

**Issue by Cronos0670** [maximedrn/opensea-automatic-bulk-upload-and-sale#92]
Hello.
I'm trying to insert unlockable content into NFT.
When I insert one line, everything goes fine.
As soon as I do a line break according to Markdown syntax (<Space><Space><Enter>) the script starts ignoring the unlockable content.
Is there any way to solve this problem?

**Comment by maximedrn** [comment]
Send me an excerpt of your file, I will look at this.

**Comment by Cronos0670** [comment]
> Send me an excerpt of your file, I will look at this.

[True, "###Congratulations!  
Now you have access to the hidden section of the site.  
  
[Go to the secure resourse](https://site.com/closed-resource.php).  
Password: ** Password**"]
