### ISSUE TITLE
0.05 ETH requirement

### ISSUE THREAD

**Issue by trung23** [maximedrn/opensea-automatic-bulk-upload-and-sale#97]
Hi,
Is the 0.05 ETH still required if I've already paid gas fee for the very first (initialization) selling transaction? Or would it proceed as usual even when ETH is not enough?
Thanks,
TC

**Comment by maximedrn** [comment]
For the first time, you must have an activated account with a minimum deposit. You can try to sell a second NFT, if you don't have any gas charges appearing, it will be good.

**Comment by trung23** [comment]
Thank you!
