### ISSUE TITLE
Mac M1, Error after  "python3 main.py"

### ISSUE THREAD

**Issue by Stabrus77777** [maximedrn/opensea-automatic-bulk-upload-and-sale#99]
Hi there, 

I`m using a mac m1 and I`m having trouble with the command: python3 main.py 

I get that Error:

 python3 main.py
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: can't open file '/Users/stabrus/Desktop/NFT/Umpoad /Infotex/bulk-upload-to-opensea-main/main.py': [Errno 2] No such file or directory

**Comment by maximedrn** [comment]
This means that Python cannot open the `main.py` file because it does not exist or is in the wrong path. Try opening your command line in the same path as the Python file (`main.py`).
